/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HolidayFrame.java
 *
 * Created on Aug 26, 2011, 5:30:05 PM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.AbstractListModel;
import smack.comm.SBXPCProxy;
import smack.comm.output.GetDeviceLongInfoOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author Administrator
 */
public class HolidayFrame extends javax.swing.JFrame {

    public class DbHoliday
    {
        public final int index;
        
        public int month;
        public int day;
        public int period;
        
        public DbHoliday(int index)
        {
            this.index = index;
            month = 1;
            day = 1;
            period = 0;
        }
        
        @Override
        public String toString()
        {
            NumberFormat formatter = new DecimalFormat("00");
            String ret;
            ret = "[No.] " + index + " ";
            ret += "[Month/Day] " + formatter.format(month) + ":" + formatter.format(day) + " ";
            ret += "[Period] " + period;
            
            return ret;
        }
    }
    
    public class TModeListModel extends AbstractListModel
    {
        public static final int HOLIDAY_COUNT = 256;
        public static final int ELEM_CNT = 3;
        
        DbHoliday[] holidayList = new DbHoliday[HOLIDAY_COUNT];
        
        public TModeListModel()
        {
            for(int i = 0; i< HOLIDAY_COUNT; i ++)
                holidayList[i] = new DbHoliday(i);
        }
        
        public void setAllData(GetDeviceLongInfoOutput data)
        {
            if(data.value.length < HOLIDAY_COUNT * ELEM_CNT)
                return;
            
            for(int i = 0; i < HOLIDAY_COUNT; i ++)
            {
                holidayList[i].month     = data.value[i * ELEM_CNT + 0];
                holidayList[i].day       = data.value[i * ELEM_CNT + 1];
                holidayList[i].period    = data.value[i * ELEM_CNT + 2];
            }
            fireContentsChanged(this, 0, getSize());
        }
        
        public int[] getAllData()
        {
            int[] ret = new int[HOLIDAY_COUNT * ELEM_CNT];
            
            int index;
            
            for(int i = 0; i < HOLIDAY_COUNT; i ++)
            {
                index = i * ELEM_CNT;
                ret[index + 0] = holidayList[i].month;
                ret[index + 1] = holidayList[i].day;
                ret[index + 2] = holidayList[i].period;
            }
            
            return ret;
        }
        
        public void setElementAt(int index, DbHoliday holiday)
        {
            if(index < 0 || index >= HOLIDAY_COUNT)
                return;

            holidayList[index] = holiday;
            
            fireContentsChanged(this, index, index);
        }
        
        public int getSize() {
            return HOLIDAY_COUNT;
        }

        public Object getElementAt(int index) {
            return holidayList[index];
        }        
    }
    
    TModeListModel listModel = new TModeListModel();

    /** Creates new form HolidayFrame */
    public HolidayFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtHoliday = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstHoliday = new javax.swing.JList();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnWrite = new javax.swing.JButton();
        txtPeriod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(HolidayFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 553, 31));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, 20));

        txtHoliday.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd"))));
        txtHoliday.setFont(resourceMap.getFont("txtHoliday.font")); // NOI18N
        txtHoliday.setName("txtHoliday"); // NOI18N
        getContentPane().add(txtHoliday, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstHoliday.setModel(listModel);
        lstHoliday.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstHoliday.setName("lstHoliday"); // NOI18N
        lstHoliday.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstHolidayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstHoliday);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, 380));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 90, 40));

        btnUpdate.setFont(resourceMap.getFont("btnUpdate.font")); // NOI18N
        btnUpdate.setText(resourceMap.getString("btnUpdate.text")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, 40));

        btnRead.setFont(resourceMap.getFont("btnRead.font")); // NOI18N
        btnRead.setText(resourceMap.getString("btnRead.text")); // NOI18N
        btnRead.setName("btnRead"); // NOI18N
        btnRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadMouseClicked(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 40));

        btnWrite.setFont(resourceMap.getFont("btnWrite.font")); // NOI18N
        btnWrite.setText(resourceMap.getString("btnWrite.text")); // NOI18N
        btnWrite.setName("btnWrite"); // NOI18N
        btnWrite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWriteMouseClicked(evt);
            }
        });
        getContentPane().add(btnWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 40));

        txtPeriod.setFont(resourceMap.getFont("txtPeriod.font")); // NOI18N
        txtPeriod.setText(resourceMap.getString("txtPeriod.text")); // NOI18N
        txtPeriod.setName("txtPeriod"); // NOI18N
        getContentPane().add(txtPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 100, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-584)/2, (screenSize.height-521)/2, 584, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void lstHolidayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstHolidayMouseClicked
        DbHoliday holiday = (DbHoliday)lstHoliday.getSelectedValue();
        if(holiday == null)
            return;
        
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MONTH, holiday.month - 1);
        calendar.set(Calendar.DATE, holiday.day);
        txtHoliday.setValue(calendar.getTime());
        
        txtPeriod.setText(String.valueOf(holiday.period));
}//GEN-LAST:event_lstHolidayMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
}//GEN-LAST:event_btnExitMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        
        int index = lstHoliday.getSelectedIndex();
        if(index == -1)
            return;
        
        DbHoliday holiday = new DbHoliday(index);
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime((Date)txtHoliday.getValue());
        holiday.month = calendar.get(Calendar.MONTH) + 1;
        holiday.day = calendar.get(Calendar.DATE);
        
        try{
            holiday.period = Integer.parseInt(txtPeriod.getText());
        }catch(NumberFormatException e){}
        
        listModel.setElementAt(index, holiday);
}//GEN-LAST:event_btnUpdateMouseClicked

    private void btnReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret) {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetDeviceLongInfoOutput output;
        output = SBXPCProxy.GetDeviceLongInfo(SysUtil.MachineNumber, 6);
        
        if(output.isSuccess()) {
            listModel.setAllData(output);
            errorCode = 0;
        }else {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
}//GEN-LAST:event_btnReadMouseClicked

    private void btnWriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret) {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDeviceLongInfo(SysUtil.MachineNumber, 6, listModel.getAllData());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
}//GEN-LAST:event_btnWriteMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWrite;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JList lstHoliday;
    private javax.swing.JFormattedTextField txtHoliday;
    private javax.swing.JTextField txtPeriod;
    // End of variables declaration//GEN-END:variables
}
