/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProductCodeFrame.java
 *
 * Created on Aug 20, 2011, 5:44:16 PM
 */
package smack.comm.sample;

import smack.comm.SBXPCProxy;
import smack.comm.output.OneStringOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class ProductCodeFrame extends javax.swing.JFrame {

    /** Creates new form ProductCodeFrame */
    public ProductCodeFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSerialNumber = new javax.swing.JTextField();
        txtBackupNumber = new javax.swing.JTextField();
        txtProductCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGetSerialNumber = new javax.swing.JButton();
        btnGetBackupNumber = new javax.swing.JButton();
        btnGetProductCode = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(ProductCodeFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 470, 31));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 70, 50));

        jLabel4.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        txtSerialNumber.setFont(resourceMap.getFont("jTextField2.font")); // NOI18N
        txtSerialNumber.setText(resourceMap.getString("txtSerialNumber.text")); // NOI18N
        txtSerialNumber.setName("txtSerialNumber"); // NOI18N
        getContentPane().add(txtSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 230, -1));

        txtBackupNumber.setFont(resourceMap.getFont("txtBackupNumber.font")); // NOI18N
        txtBackupNumber.setText(resourceMap.getString("txtBackupNumber.text")); // NOI18N
        txtBackupNumber.setName("txtBackupNumber"); // NOI18N
        getContentPane().add(txtBackupNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 230, -1));

        txtProductCode.setFont(resourceMap.getFont("jTextField2.font")); // NOI18N
        txtProductCode.setText(resourceMap.getString("txtProductCode.text")); // NOI18N
        txtProductCode.setName("txtProductCode"); // NOI18N
        getContentPane().add(txtProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 230, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 20));

        jLabel6.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        btnGetSerialNumber.setFont(resourceMap.getFont("btnGetSerialNumber.font")); // NOI18N
        btnGetSerialNumber.setText("<html><center>Get<br>Serial Number</center></html>");
        btnGetSerialNumber.setName("btnGetSerialNumber"); // NOI18N
        btnGetSerialNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetSerialNumberMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetSerialNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, 50));

        btnGetBackupNumber.setFont(resourceMap.getFont("btnGetBackupNumber.font")); // NOI18N
        btnGetBackupNumber.setText("<html><center>Get<br>Backup Number</center></html>");
        btnGetBackupNumber.setName("btnGetBackupNumber"); // NOI18N
        btnGetBackupNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetBackupNumberMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetBackupNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 130, 50));

        btnGetProductCode.setFont(resourceMap.getFont("btnGetProductCode.font")); // NOI18N
        btnGetProductCode.setText("<html><center>Get<br>Product Code</center></html>");
        btnGetProductCode.setName("btnGetProductCode"); // NOI18N
        btnGetProductCode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetProductCodeMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetProductCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 120, 50));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-501)/2, (screenSize.height-322)/2, 501, 322);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnGetSerialNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetSerialNumberMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        OneStringOutput output;
        output = SBXPCProxy.GetSerialNumber(SysUtil.MachineNumber);
        
        if(output.isSuccess())
        {
            txtSerialNumber.setText(output.value);
            errorCode = 0;
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetSerialNumberMouseClicked

    private void btnGetBackupNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetBackupNumberMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        long output;
        output = SBXPCProxy.GetBackupNumber(SysUtil.MachineNumber);
        
        txtBackupNumber.setText(String.valueOf(output));
        errorCode = 0;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetBackupNumberMouseClicked

    private void btnGetProductCodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetProductCodeMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        OneStringOutput output;
        output = SBXPCProxy.GetProductCode(SysUtil.MachineNumber);
        
        if(output.isSuccess())
        {
            txtProductCode.setText(output.value);
            errorCode = 0;
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetProductCodeMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetBackupNumber;
    private javax.swing.JButton btnGetProductCode;
    private javax.swing.JButton btnGetSerialNumber;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtBackupNumber;
    private javax.swing.JTextField txtProductCode;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables
}
