/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TModeMngFrame.java
 *
 * Created on Aug 26, 2011, 4:54:41 PM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.AbstractListModel;
import smack.comm.SBXPCProxy;
import smack.comm.output.GetDeviceLongInfoOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author Administrator
 */
public class TModeMngFrame extends javax.swing.JFrame {

    public class DbTMode
    {
        public final int index;
        
        public int startHour;
        public int startMinute;
        public int endHour;
        public int endMinute;
        public int doorStatus;
        
        public DbTMode(int index)
        {
            this.index = index;
            startHour = 0;
            startMinute = 0;
            endHour = 0;
            endMinute = 0;
            doorStatus = 0;
        }
        
        @Override
        public String toString()
        {
            NumberFormat formatter = new DecimalFormat("00");
            String ret;
            ret = "[No.] " + index + " ";
            ret += "[S] " + formatter.format(startHour) + ":" + formatter.format(startMinute) + " ";
            ret += "[E] " + formatter.format(endHour) + ":" + formatter.format(endMinute) + " ";
            ret += "[Status] " + cmbTrStatus.getItemAt(doorStatus);
            
            return ret;
        }
    }
    
    public class TModeListModel extends AbstractListModel
    {
        public static final int TMODE_COUNT = 10;
        public static final int ELEM_CNT = 5;
        
        DbTMode[] tModeList = new DbTMode[TMODE_COUNT];
        
        public TModeListModel()
        {
            for(int i = 0; i< TMODE_COUNT; i ++)
                tModeList[i] = new DbTMode(i);
        }
        
        public void setAllData(GetDeviceLongInfoOutput data)
        {
            if(data.value.length < TMODE_COUNT * ELEM_CNT)
                return;
            
            for(int i = 0; i < TMODE_COUNT; i ++)
            {
                tModeList[i].doorStatus      = data.value[i * ELEM_CNT + 0];
                tModeList[i].startHour     = data.value[i * ELEM_CNT + 1];
                tModeList[i].startMinute   = data.value[i * ELEM_CNT + 2];
                tModeList[i].endHour       = data.value[i * ELEM_CNT + 3];
                tModeList[i].endMinute     = data.value[i * ELEM_CNT + 4];
            }
            fireContentsChanged(this, 0, getSize());
        }
        
        public int[] getAllData()
        {
            int[] ret = new int[TMODE_COUNT * ELEM_CNT];
            
            int index;
            
            for(int i = 0; i < TMODE_COUNT; i ++)
            {
                index = i * ELEM_CNT;
                ret[index + 0] = tModeList[i].doorStatus;
                ret[index + 1] = tModeList[i].startHour;
                ret[index + 2] = tModeList[i].startMinute;
                ret[index + 3] = tModeList[i].endHour;
                ret[index + 4] = tModeList[i].endMinute;
            }
            
            return ret;
        }
        
        public void setElementAt(int index, DbTMode tMode)
        {
            if(index < 0 || index >= TMODE_COUNT)
                return;

            checkData(tMode);
            
            tModeList[index] = tMode;
            
            fireContentsChanged(this, index, index);
        }
        
        private boolean checkData(DbTMode tMode)
        {
            if(tMode.doorStatus < 0)
            {
                tMode.doorStatus = 0;
                return false;
            }
            if(tMode.doorStatus >= cmbTrStatus.getItemCount())
            {
                tMode.doorStatus = cmbTrStatus.getItemCount() - 1;
                return false;
            }
            
            return true;
        }
        
        public int getSize() {
            return TMODE_COUNT;
        }

        public Object getElementAt(int index) {
            return tModeList[index];
        }        
    }
    
    TModeListModel listModel = new TModeListModel();

    /** Creates new form TModeMngFrame */
    public TModeMngFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtEnd = new javax.swing.JFormattedTextField();
        txtStart = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTrStatus = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstTModeList = new javax.swing.JList();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnWrite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(TModeMngFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 553, 31));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 20));

        txtEnd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtEnd.setFont(resourceMap.getFont("txtEnd.font")); // NOI18N
        txtEnd.setName("txtEnd"); // NOI18N
        getContentPane().add(txtEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, -1));

        txtStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        txtStart.setFont(resourceMap.getFont("txtStart.font")); // NOI18N
        txtStart.setName("txtStart"); // NOI18N
        getContentPane().add(txtStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 90, -1));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        cmbTrStatus.setFont(resourceMap.getFont("cmbTrStatus.font")); // NOI18N
        cmbTrStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "FP&CD", "FP&PWD", "CD&PWD", "FP&CD&PWD", " " }));
        cmbTrStatus.setName("cmbTrStatus"); // NOI18N
        getContentPane().add(cmbTrStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 190, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstTModeList.setModel(listModel);
        lstTModeList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstTModeList.setName("lstTModeList"); // NOI18N
        lstTModeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstTModeListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstTModeList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 450, 350));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 90, 40));

        btnUpdate.setFont(resourceMap.getFont("btnUpdate.font")); // NOI18N
        btnUpdate.setText(resourceMap.getString("btnUpdate.text")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 90, 40));

        btnRead.setFont(resourceMap.getFont("btnRead.font")); // NOI18N
        btnRead.setText(resourceMap.getString("btnRead.text")); // NOI18N
        btnRead.setName("btnRead"); // NOI18N
        btnRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadMouseClicked(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 40));

        btnWrite.setFont(resourceMap.getFont("btnWrite.font")); // NOI18N
        btnWrite.setText(resourceMap.getString("btnWrite.text")); // NOI18N
        btnWrite.setName("btnWrite"); // NOI18N
        btnWrite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWriteMouseClicked(evt);
            }
        });
        getContentPane().add(btnWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 40));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-588)/2, (screenSize.height-524)/2, 588, 524);
    }// </editor-fold>//GEN-END:initComponents

    private void lstTModeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstTModeListMouseClicked
        
        DbTMode tMode = (DbTMode)lstTModeList.getSelectedValue();
        if(tMode == null)
            return;
        
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.HOUR_OF_DAY, tMode.startHour);
        calendar.set(Calendar.MINUTE, tMode.startMinute);
        txtStart.setValue(calendar.getTime());
        
        calendar.set(Calendar.HOUR_OF_DAY, tMode.endHour);
        calendar.set(Calendar.MINUTE, tMode.endMinute);
        txtEnd.setValue(calendar.getTime());
        
        cmbTrStatus.setSelectedIndex(tMode.doorStatus);
}//GEN-LAST:event_lstTModeListMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
}//GEN-LAST:event_btnExitMouseClicked

    private void btnWriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret) {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDeviceLongInfo(SysUtil.MachineNumber, 4, listModel.getAllData());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
}//GEN-LAST:event_btnWriteMouseClicked

    private void btnReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret) {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetDeviceLongInfoOutput output;
        output = SBXPCProxy.GetDeviceLongInfo(SysUtil.MachineNumber, 4);
        
        if(output.isSuccess()) {
            listModel.setAllData(output);
            errorCode = 0;
        }else {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
}//GEN-LAST:event_btnReadMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        
        int index = lstTModeList.getSelectedIndex();
        if(index == -1)
            return;
        
        DbTMode tMode = new DbTMode(index);
        
        Calendar calendar = Calendar.getInstance();
        calendar.setTime((Date)txtStart.getValue());
        tMode.startHour = calendar.get(Calendar.HOUR_OF_DAY);
        tMode.startMinute = calendar.get(Calendar.MINUTE);
        
        calendar.setTime((Date)txtEnd.getValue());
        tMode.endHour = calendar.get(Calendar.HOUR_OF_DAY);
        tMode.endMinute = calendar.get(Calendar.MINUTE);
        
        tMode.doorStatus = cmbTrStatus.getSelectedIndex();
        
        listModel.setElementAt(index, tMode);
}//GEN-LAST:event_btnUpdateMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWrite;
    private javax.swing.JComboBox cmbTrStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JList lstTModeList;
    private javax.swing.JFormattedTextField txtEnd;
    private javax.swing.JFormattedTextField txtStart;
    // End of variables declaration//GEN-END:variables
}
