#NOI18N
lblMessage.font=Times New Roman-Bold-18
#NOI18N
jLabel3.font=Times New Roman-Bold-14
jLabel3.text=Start Time
jLabel4.text=Point 12:
jLabel5.text=Use Flag
jLabel6.text=Start Time
jLabel7.text=Bell Count
jLabel8.text=Bell Point
jLabel9.text=Use Flag
#NOI18N
jLabel10.font=Times New Roman 14 Bold
jLabel10.text=Bell Point
jLabel11.text=:
#NOI18N
jLabel11.font=Times New Roman 14 Bold
jLabel12.text=Point 2:
#NOI18N
jLabel12.font=Times New Roman 14 Bold
jLabel13.text=Point 3:
#NOI18N
jLabel13.font=Times New Roman 14 Bold
jLabel14.text=Point 4:
#NOI18N
jLabel14.font=Times New Roman 14 Bold
jLabel15.text=Point 5:
#NOI18N
jLabel15.font=Times New Roman 14 Bold
jLabel16.text=Point 6:
#NOI18N
jLabel16.font=Times New Roman 14 Bold
jLabel17.text=Point 7:
#NOI18N
jLabel17.font=Times New Roman 14 Bold
jLabel18.text=Point 8:
#NOI18N
jLabel18.font=Times New Roman 14 Bold
jLabel19.text=Point 9:
#NOI18N
jLabel19.font=Times New Roman 14 Bold
jLabel20.text=Point 10:
#NOI18N
jLabel20.font=Times New Roman 14 Bold
jLabel21.text=Point 11:
#NOI18N
jLabel21.font=Times New Roman 14 Bold
jLabel33.text=Point 23:
#NOI18N
jLabel33.font=Times New Roman 14 12 Bold
jLabel32.text=Point 22:
#NOI18N
jLabel32.font=Times New Roman 14 12 Bold
jLabel31.text=Point 21:
#NOI18N
jLabel31.font=Times New Roman 14 12 Bold
jLabel30.text=Point 20:
#NOI18N
jLabel30.font=Times New Roman 14 12 Bold
jLabel29.text=Point 19:
#NOI18N
jLabel29.font=Times New Roman 14 12 Bold
jLabel28.text=Point 18:
#NOI18N
jLabel28.font=Times New Roman 14 12 Bold
jLabel27.text=Point 17:
#NOI18N
jLabel27.font=Times New Roman 14 12 Bold
jLabel26.text=Point 16:
#NOI18N
jLabel26.font=Times New Roman 14 12 Bold
jLabel25.text=Point 15:
#NOI18N
jLabel25.font=Times New Roman 14 12 Bold
jLabel24.text=Point 14:
#NOI18N
jLabel24.font=Times New Roman 14 12 Bold
jLabel23.text=Point 13:
#NOI18N
jLabel23.font=Times New Roman 14 12 Bold
jLabel22.text=Point 24:
#NOI18N
jLabel22.font=Times New Roman 14 Bold
#NOI18N
jLabel34.font=Times New Roman 14 12 Bold
jLabel34.text=Point 1:
#NOI18N
jLabel35.font=Times New Roman 14 12 Bold
#NOI18N
jTextField5.font=Times New Roman 14 12 Plain
#NOI18N
jTextField4.font=Times New Roman 14 12 Plain
jLabel35.text=:
#NOI18N
jLabel36.font=Times New Roman 14 12 Bold
#NOI18N
jTextField9.font=Times New Roman 14 12 12 Plain
#NOI18N
jTextField8.font=Times New Roman 14 12 12 Plain
jLabel37.text=:
#NOI18N
jLabel37.font=Times New Roman 14 12 12 Bold
jLabel36.text=:
#NOI18N
jTextField13.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField12.font=Times New Roman 14 12 12 12 Plain
jLabel39.text=:
#NOI18N
jLabel39.font=Times New Roman 14 12 12 12 Bold
jLabel38.text=:
#NOI18N
jLabel38.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField25.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField24.font=Times New Roman 14 12 12 12 12 Plain
jLabel45.text=:
#NOI18N
jLabel45.font=Times New Roman 14 12 12 12 12 Bold
jLabel44.text=:
#NOI18N
jLabel44.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField21.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField20.font=Times New Roman 14 12 12 12 Plain
jLabel43.text=:
#NOI18N
jLabel43.font=Times New Roman 14 12 12 12 Bold
jLabel42.text=:
#NOI18N
jLabel42.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField17.font=Times New Roman 14 12 12 Plain
#NOI18N
jTextField16.font=Times New Roman 14 12 12 Plain
jLabel41.text=:
#NOI18N
jLabel41.font=Times New Roman 14 12 12 Bold
jLabel40.text=:
#NOI18N
jLabel40.font=Times New Roman 14 12 Bold
#NOI18N
jTextField49.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
jTextField48.font=Times New Roman 14 12 12 12 12 12 Plain
jLabel57.text=:
#NOI18N
jLabel57.font=Times New Roman 14 12 12 12 12 12 Bold
jLabel56.text=:
#NOI18N
jLabel56.font=Times New Roman 14 12 12 12 12 Bold
#NOI18N
jTextField45.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField44.font=Times New Roman 14 12 12 12 12 Plain
jLabel55.text=:
#NOI18N
jLabel55.font=Times New Roman 14 12 12 12 12 Bold
jLabel54.text=:
#NOI18N
jLabel54.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField41.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField40.font=Times New Roman 14 12 12 12 Plain
jLabel53.text=:
#NOI18N
jLabel53.font=Times New Roman 14 12 12 12 Bold
jLabel52.text=:
#NOI18N
jLabel52.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField37.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField36.font=Times New Roman 14 12 12 12 12 Plain
jLabel51.text=:
#NOI18N
jLabel51.font=Times New Roman 14 12 12 12 12 Bold
jLabel50.text=:
#NOI18N
jLabel50.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField33.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField32.font=Times New Roman 14 12 12 12 Plain
jLabel49.text=:
#NOI18N
jLabel49.font=Times New Roman 14 12 12 12 Bold
jLabel48.text=:
#NOI18N
jLabel48.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField29.font=Times New Roman 14 12 12 Plain
#NOI18N
jTextField28.font=Times New Roman 14 12 12 Plain
jLabel46.text=:
#NOI18N
jLabel46.font=Times New Roman 14 12 Bold
#NOI18N
jLabel47.font=Times New Roman 14 12 Bold
#NOI18N
jTextField97.font=Times New Roman 14 12 12 12 12 12 12 Plain
#NOI18N
jTextField96.font=Times New Roman 14 12 12 12 12 12 12 Plain
jLabel79.text=:
#NOI18N
jLabel79.font=Times New Roman 14 12 12 12 12 12 12 Bold
jLabel78.text=:
#NOI18N
jLabel78.font=Times New Roman 14 12 12 12 12 12 Bold
#NOI18N
jTextField93.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
jTextField92.font=Times New Roman 14 12 12 12 12 12 Plain
jLabel77.text=:
#NOI18N
jLabel77.font=Times New Roman 14 12 12 12 12 12 Bold
jLabel76.text=:
#NOI18N
jLabel76.font=Times New Roman 14 12 12 12 12 Bold
#NOI18N
jTextField89.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField88.font=Times New Roman 14 12 12 12 12 Plain
jLabel75.text=:
#NOI18N
jLabel75.font=Times New Roman 14 12 12 12 12 Bold
jLabel74.text=:
#NOI18N
jLabel74.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField85.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
jTextField84.font=Times New Roman 14 12 12 12 12 12 Plain
jLabel73.text=:
#NOI18N
jLabel73.font=Times New Roman 14 12 12 12 12 12 Bold
jLabel72.text=:
#NOI18N
jLabel72.font=Times New Roman 14 12 12 12 12 Bold
#NOI18N
jTextField81.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField80.font=Times New Roman 14 12 12 12 12 Plain
jLabel71.text=:
#NOI18N
jLabel71.font=Times New Roman 14 12 12 12 12 Bold
jLabel70.text=:
#NOI18N
jLabel70.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField77.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField76.font=Times New Roman 14 12 12 12 Plain
jLabel69.text=:
#NOI18N
jLabel69.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField73.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
jTextField72.font=Times New Roman 14 12 12 12 12 12 Plain
jLabel68.text=:
#NOI18N
jLabel68.font=Times New Roman 14 12 12 12 12 12 Bold
jLabel67.text=:
#NOI18N
jLabel67.font=Times New Roman 14 12 12 12 12 Bold
#NOI18N
jTextField69.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField68.font=Times New Roman 14 12 12 12 12 Plain
jLabel66.text=:
#NOI18N
jLabel66.font=Times New Roman 14 12 12 12 12 Bold
jLabel65.text=:
#NOI18N
jLabel65.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField65.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField64.font=Times New Roman 14 12 12 12 Plain
jLabel64.text=:
#NOI18N
jLabel64.font=Times New Roman 14 12 12 12 Bold
jLabel63.text=:
#NOI18N
jLabel63.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField61.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
jTextField60.font=Times New Roman 14 12 12 12 12 Plain
jLabel62.text=:
#NOI18N
jLabel62.font=Times New Roman 14 12 12 12 12 Bold
jLabel61.text=:
#NOI18N
jLabel61.font=Times New Roman 14 12 12 12 Bold
#NOI18N
jTextField57.font=Times New Roman 14 12 12 12 Plain
#NOI18N
jTextField56.font=Times New Roman 14 12 12 12 Plain
jLabel60.text=:
#NOI18N
jLabel60.font=Times New Roman 14 12 12 12 Bold
jLabel59.text=:
#NOI18N
jLabel59.font=Times New Roman 14 12 12 Bold
#NOI18N
jTextField53.font=Times New Roman 14 12 12 Plain
#NOI18N
jTextField52.font=Times New Roman 14 12 12 Plain
jLabel58.text=:
#NOI18N
jLabel58.font=Times New Roman 14 12 12 Bold
jLabel47.text=:
btnRead.text=Read
#NOI18N
btnRead.font=Times New Roman 14 12 12 12 12 Bold
btnWrite.text=Write
#NOI18N
btnWrite.font=Times New Roman 14 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 Bold
txtBellCount.text=
#NOI18N
txtBellCount.font=Times New Roman-Plain-14
_chkUseFlag_2.text=
#NOI18N
_txtMinute_0.font=Times New Roman 14 Plain
#NOI18N
_txtMinute_1.font=Times New Roman 14 12 Plain
#NOI18N
_txtMinute_2.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_3.font=Times New Roman 14 12 Plain
#NOI18N
_txtMinute_4.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_5.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_6.font=Times New Roman 14 12 Plain
#NOI18N
_txtMinute_7.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_8.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_9.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_10.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_11.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtMinute_12.font=Times New Roman 14 12 Plain
#NOI18N
_txtMinute_13.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_14.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_15.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_16.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_17.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtMinute_18.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtMinute_19.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_20.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtMinute_21.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtMinute_22.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtMinute_23.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
_txtHour_0.font=Times New Roman 14 Plain
#NOI18N
_txtHour_1.font=Times New Roman 14 12 Plain
#NOI18N
_txtHour_2.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_3.font=Times New Roman 14 12 Plain
#NOI18N
_txtHour_4.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_5.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_6.font=Times New Roman 14 12 Plain
#NOI18N
_txtHour_7.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_8.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_9.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_10.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_12.font=Times New Roman 14 12 Plain
#NOI18N
_txtHour_14.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_15.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_16.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_17.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtHour_18.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_20.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtHour_21.font=Times New Roman 14 12 12 12 Plain
#NOI18N
_txtHour_22.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtHour_23.font=Times New Roman 14 12 12 12 12 12 Plain
#NOI18N
_txtHour_11.font=Times New Roman 14 12 12 12 12 Plain
#NOI18N
_txtHour_13.font=Times New Roman 14 12 12 Plain
#NOI18N
_txtHour_19.font=Times New Roman 14 12 12 12 Plain
lblMessage.text=Message
Form.title=Bell Setting
