#NOI18N
lblMessage.font=Times New Roman-Bold-18
lblMessage.text=Message
#NOI18N
jLabel3.font=Times New Roman-Plain-14
jLabel3.text=Value:
jLabel4.text=Status/Info Parameter:
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 12 12 Bold
btnGetDeviceTime.text=Get Device Time
#NOI18N
btnGetDeviceTime.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnSetDeviceTime.text=Set Device Time
#NOI18N
btnSetDeviceTime.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnPowerOnDevice.text=Power On Device
#NOI18N
btnPowerOnDevice.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnPowerOffDevice.text=Power Off Device
#NOI18N
btnPowerOffDevice.font=Times New Roman 14 12 12 12 12 12 12 Bold
chkEnableDevice.text=
btnEnableDevice.text=Disable Device
#NOI18N
btnEnableDevice.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnGetDeviceInfo.text=Get Device Info
#NOI18N
btnGetDeviceInfo.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
#NOI18N
cmbParam.font=Times New Roman-Plain-14
#NOI18N
txtValue.font=Times New Roman-Plain-14
btnSetDeviceInfo.text=Set Device Info
#NOI18N
btnSetDeviceInfo.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnGetDeviceStatus.text=Get Device Status
#NOI18N
btnGetDeviceStatus.font=Times New Roman 14 12 12 12 12 12 12 Bold
Form.title=System Information
