# To change this template, choose Tools | Templates
# and open the template in the editor.

btnWrite.text=Write
#NOI18N
btnWrite.font=Times New Roman 14 12 12 12 12 Bold
btnRead.text=Read
#NOI18N
btnRead.font=Times New Roman 14 12 12 12 12 Bold
btnUpdate.text=Update
#NOI18N
btnUpdate.font=Times New Roman 14 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 Bold
#NOI18N
cmbTrStatus.font=Times New Roman 14 Plain
jLabel3.text=Start:
#NOI18N
jLabel3.font=Times New Roman 14 Plain
#NOI18N
txtStart.font=Times New Roman 14 Plain
#NOI18N
txtEnd.font=Times New Roman 14 Plain
jLabel2.text=In/Out Status:
#NOI18N
jLabel2.font=Times New Roman 14 Plain
jLabel1.text=End:
#NOI18N
jLabel1.font=Times New Roman 14 Plain
lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman 18 Bold
