
lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Bold-18
jLabel1.text=End:
jLabel3.text=Start:
txtEnd.text=
btnUpdate.text=Update
#NOI18N
btnUpdate.font=Times New Roman 14 12 12 Bold
btnRead.text=Read
#NOI18N
btnRead.font=Times New Roman 14 12 12 Bold
btnWrite.text=Write
#NOI18N
btnWrite.font=Times New Roman 14 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 Bold
#NOI18N
txtStart.font=Times New Roman-Plain-14
Form.title=Access Timezone
