# To change this template, choose Tools | Templates
# and open the template in the editor.

btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 Bold
btnWrite.text=Write
#NOI18N
btnWrite.font=Times New Roman 14 12 12 12 Bold
btnRead.text=Read
#NOI18N
btnRead.font=Times New Roman 14 12 12 12 Bold
lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman 18 Bold
btnUpdate.text=Update
#NOI18N
btnUpdate.font=Times New Roman 14 12 12 12 Bold
jLabel3.text=Department Name:
#NOI18N
jLabel3.font=Times New Roman 14 12 12 12 Plain
#NOI18N
txtDepartmentName.font=Times New Roman 14 Plain
