optNetwork.text=Network Device
#NOI18N
optNetwork.font=Times New Roman 14 Bold
txtPortNumber.text=5005
#NOI18N
txtPortNumber.font=Times New Roman 14 12 Plain
txtIPAddress.text=0.0.0.0
#NOI18N
txtIPAddress.font=Times New Roman 14 12 Plain
txtPassword.text=0
#NOI18N
txtPassword.font=Times New Roman 14 Plain
jLabel6.text=Port Number:
#NOI18N
jLabel6.font=Times New Roman 14 12 12 Plain
jLabel5.text=IP Address:
#NOI18N
jLabel5.font=Times New Roman 14 12 12 Plain
jLabel2.text=Password:
#NOI18N
jLabel2.font=Times New Roman 14 12 Plain
jPanel3.toolTipText=
#NOI18N
jPanel3.border.titleFont=Times New Roman 14 12 Bold
#NOI18N
jPanel3.border.titleColor=0, 0, 0
jPanel3.border.title=Network Device
optSerial.text=Serial Device
#NOI18N
optSerial.font=Times New Roman 14 Bold
jLabel10.text=Baudrate:
#NOI18N
jLabel10.font=Times New Roman 14 12 12 Plain
#NOI18N
cmbBaudrate.font=Times New Roman 14 12 12 Plain
jLabel9.text=Comm Port:
#NOI18N
jLabel9.font=Times New Roman 14 12 12 Plain
#NOI18N
cmbCommPort.font=Times New Roman 14 12 12 Plain
jPanel5.toolTipText=
#NOI18N
jPanel5.border.titleFont=Times New Roman 14 12 12 12 Bold
#NOI18N
jPanel5.border.titleColor=0, 0, 0
jPanel5.border.title=Serial Device
btnStartEventCapture.text=Start Event Capture
btnStopEventCapture.text=Stop Event Capture
btnClearList.text=Clear
#NOI18N
btnClearList.font=Times New Roman-Bold-14
#NOI18N
btnStopEventCapture.font=Times New Roman-Bold-14
#NOI18N
btnStartEventCapture.font=Times New Roman-Bold-14
