jLabel2.text=Period:
#NOI18N
jLabel2.font=Times New Roman-Plain-14
lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Bold-18
btnWrite.text=Write
#NOI18N
btnWrite.font=Times New Roman 14 12 12 12 12 12 Bold
btnRead.text=Read
#NOI18N
btnRead.font=Times New Roman 14 12 12 12 12 12 Bold
btnUpdate.text=Update
#NOI18N
btnUpdate.font=Times New Roman 14 12 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 12 Bold
#NOI18N
txtHoliday.font=Times New Roman 14 12 Plain
txtPeriod.text=
#NOI18N
txtPeriod.font=Times New Roman-Plain-14
Form.title=Holiday Setting
