#NOI18N
lblMessage.font=Times New Roman-Bold-18
lblMessage.text=Message
btnGetDoorStatus.text=Get Door Status
#NOI18N
btnGetDoorStatus.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnDoorOpen.text=Door Open
#NOI18N
btnDoorOpen.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnAutoRecover.text=Auto Recover
#NOI18N
btnAutoRecover.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnReboot.text=Reboot
#NOI18N
btnReboot.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
btnUncondOpen.text=UnCond Open
#NOI18N
btnUncondOpen.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnUncondClose.text=Uncond Close
#NOI18N
btnUncondClose.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnWarnCancel.text=Warn Cancel
#NOI18N
btnWarnCancel.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
Form.title=Lock Control
