# To change this template, choose Tools | Templates
# and open the template in the editor.

lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Bold-18
#NOI18N
btnDoorOpen1.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 Bold
btnDoorOpen1.text=Exit
#NOI18N
btnReadSLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadAllSLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnEmptySLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadAllGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnEmptyGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
jLabel5.font=Times New Roman 14 Plain
jLabel5.text=Log Data:
lblTotal.text=Total:
#NOI18N
lblTotal.font=Times New Roman-Plain-14
chkSearchAndDelete.text=and Delete
#NOI18N
chkSearchAndDelete.font=Times New Roman-Plain-14
chkReadMark.text=Read Mark
#NOI18N
chkReadMark.font=Times New Roman 14 Plain
Form.title=Log Management
