# To change this template, choose Tools | Templates
# and open the template in the editor.

lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Plain-18
#NOI18N
jLabel4.font=Times New Roman-Plain-14
jLabel4.text=Glyph Height:
jLabel5.text=Company Name:
#NOI18N
jLabel5.font=Times New Roman-Plain-14
jLabel6.text=Customer Name:
#NOI18N
jLabel6.font=Times New Roman-Plain-14
btnGetCustomerInfo.text=Get Customer Info
#NOI18N
btnGetCustomerInfo.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
btnSetCustomerInfo.text=Set Customer Info
#NOI18N
btnSetCustomerInfo.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
jLabel7.text=Sleep Message:
#NOI18N
jLabel7.font=Times New Roman-Plain-14
jLabel8.text=Glyph Width:
#NOI18N
jLabel8.font=Times New Roman-Plain-14
jLabel1.text=Font Height:
jLabel2.text=Font Width:
jLabel3.text=Font Weight
#NOI18N
jLabel1.font=Times New Roman-Plain-14
#NOI18N
jLabel2.font=Times New Roman-Plain-14
#NOI18N
jLabel3.font=Times New Roman-Plain-14
txtCompanyName.text=
#NOI18N
txtCompanyName.font=Times New Roman-Plain-14
txtCustomerName.text=
#NOI18N
txtCustomerName.font=Times New Roman-Plain-14
txtSleepMessage.text=
btnGetGlyphSize.text=Get Glyph Size
#NOI18N
btnGetGlyphSize.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
txtGlyphWidth.text=
#NOI18N
txtGlyphWidth.font=Times New Roman-Plain-14
txtGlyphHeight.text=
#NOI18N
txtGlyphHeight.font=Times New Roman-Plain-14
txtFontHeight.text=20
#NOI18N
txtFontHeight.font=Times New Roman-Plain-14
txtFontWidth.text=11
#NOI18N
txtFontWidth.font=Times New Roman-Plain-14
txtFontWeight.text=700
#NOI18N
txtFontWeight.font=Times New Roman-Plain-14
txtDebugOutFileName.text=C:/temp.bmp
#NOI18N
txtDebugOutFileName.font=Times New Roman-Plain-14
chkDebugOut.text=Debug Out
#NOI18N
chkDebugOut.font=Times New Roman-Plain-14
btnDebufFileBrowse.text=...
btnGetSleepMessage.text=Get Sleep Message
#NOI18N
btnGetSleepMessage.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
btnSetSleepMessage.text=Set Sleep Message
#NOI18N
btnSetSleepMessage.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 Bold
chkItalic.text=Italic
#NOI18N
chkItalic.font=Times New Roman-Plain-14
chkUnderline.text=Underline
#NOI18N
chkUnderline.font=Times New Roman-Plain-14
chkStrikeOut.text=StrikeOut
#NOI18N
chkStrikeOut.font=Times New Roman-Plain-14
