/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EnrollMngFrame.java
 *
 * Created on Aug 18, 2011, 5:38:54 PM
 */
package smack.comm.sample;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import smack.comm.SBXPCProxy;
import smack.comm.input.GetEnrollDataInput;
import smack.comm.input.GetUserNameInput;
import smack.comm.input.SetEnrollDataInput;
import smack.comm.input.SetUserNameInput;
import smack.comm.output.GetAllUserIDOutput;
import smack.comm.output.GetEnrollDataOutput;
import smack.comm.output.OneStringOutput;
import smack.comm.sample.global.EnrollDBUtil;
import smack.comm.sample.global.SysUtil;
import smack.comm.sample.global.UserEnrollData;

/**
 *
 * @author smackbio
 */
public class EnrollMngFrame extends javax.swing.JFrame{

    /** Creates new form EnrollMngFrame */
    public EnrollMngFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSetEnrollData = new javax.swing.JButton();
        btnGetEnrollData = new javax.swing.JButton();
        btnDeleteEnrollData = new javax.swing.JButton();
        btnSendAllEnrollData = new javax.swing.JButton();
        btnSetAllEnrollData = new javax.swing.JButton();
        btnGetAllEnrollData = new javax.swing.JButton();
        btnSetName = new javax.swing.JButton();
        btnGetName = new javax.swing.JButton();
        btnDeleteCompanyName = new javax.swing.JButton();
        btnSetCompanyName = new javax.swing.JButton();
        btnEnableUser = new javax.swing.JButton();
        btnGetEnrollInfo = new javax.swing.JButton();
        btnModifyDuressFp = new javax.swing.JButton();
        btnModifyPriviege = new javax.swing.JButton();
        btnClearAllData = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDeleteDb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtUserTz1 = new javax.swing.JTextField();
        txtUserTz2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkDisableUser = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEnrollData = new javax.swing.JList();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEmptyEnrollData = new javax.swing.JButton();
        cmbDuress = new javax.swing.JComboBox();
        cmbBackupNumber = new javax.swing.JComboBox();
        cmbPrivilege = new javax.swing.JComboBox();
        lblMessage = new javax.swing.JLabel();
        txtEnrollNum = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(EnrollMngFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSetEnrollData.setFont(resourceMap.getFont("btnSetEnrollData.font")); // NOI18N
        btnSetEnrollData.setText(resourceMap.getString("btnSetEnrollData.text")); // NOI18N
        btnSetEnrollData.setName("btnSetEnrollData"); // NOI18N
        btnSetEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 210, 30));

        btnGetEnrollData.setFont(resourceMap.getFont("btnGetEnrollData.font")); // NOI18N
        btnGetEnrollData.setText(resourceMap.getString("btnGetEnrollData.text")); // NOI18N
        btnGetEnrollData.setName("btnGetEnrollData"); // NOI18N
        btnGetEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 210, 30));

        btnDeleteEnrollData.setFont(resourceMap.getFont("btnDeleteEnrollData.font")); // NOI18N
        btnDeleteEnrollData.setText(resourceMap.getString("btnDeleteEnrollData.text")); // NOI18N
        btnDeleteEnrollData.setName("btnDeleteEnrollData"); // NOI18N
        btnDeleteEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnDeleteEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 210, 30));

        btnSendAllEnrollData.setVisible(false);
        btnSendAllEnrollData.setFont(resourceMap.getFont("btnSendAllEnrollData.font")); // NOI18N
        btnSendAllEnrollData.setText(resourceMap.getString("btnSendAllEnrollData.text")); // NOI18N
        btnSendAllEnrollData.setName("btnSendAllEnrollData"); // NOI18N
        getContentPane().add(btnSendAllEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 210, 30));

        btnSetAllEnrollData.setFont(resourceMap.getFont("btnSetAllEnrollData.font")); // NOI18N
        btnSetAllEnrollData.setText(resourceMap.getString("btnSetAllEnrollData.text")); // NOI18N
        btnSetAllEnrollData.setName("btnSetAllEnrollData"); // NOI18N
        btnSetAllEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetAllEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetAllEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 210, 30));

        btnGetAllEnrollData.setFont(resourceMap.getFont("btnGetAllEnrollData.font")); // NOI18N
        btnGetAllEnrollData.setText(resourceMap.getString("btnGetAllEnrollData.text")); // NOI18N
        btnGetAllEnrollData.setName("btnGetAllEnrollData"); // NOI18N
        btnGetAllEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetAllEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetAllEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, 210, 30));

        btnSetName.setFont(resourceMap.getFont("btnSetName.font")); // NOI18N
        btnSetName.setText(resourceMap.getString("btnSetName.text")); // NOI18N
        btnSetName.setName("btnSetName"); // NOI18N
        btnSetName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetNameMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 210, 30));

        btnGetName.setFont(resourceMap.getFont("btnGetName.font")); // NOI18N
        btnGetName.setText(resourceMap.getString("btnGetName.text")); // NOI18N
        btnGetName.setName("btnGetName"); // NOI18N
        btnGetName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetNameMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 210, 30));

        btnDeleteCompanyName.setFont(resourceMap.getFont("btnDeleteCompanyName.font")); // NOI18N
        btnDeleteCompanyName.setText(resourceMap.getString("btnDeleteCompanyName.text")); // NOI18N
        btnDeleteCompanyName.setName("btnDeleteCompanyName"); // NOI18N
        btnDeleteCompanyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteCompanyNameMouseClicked(evt);
            }
        });
        getContentPane().add(btnDeleteCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 210, 30));

        btnSetCompanyName.setFont(resourceMap.getFont("btnSetCompanyName.font")); // NOI18N
        btnSetCompanyName.setText(resourceMap.getString("btnSetCompanyName.text")); // NOI18N
        btnSetCompanyName.setName("btnSetCompanyName"); // NOI18N
        btnSetCompanyName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetCompanyNameMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 210, 30));

        btnEnableUser.setFont(resourceMap.getFont("btnEnableUser.font")); // NOI18N
        btnEnableUser.setText(resourceMap.getString("btnEnableUser.text")); // NOI18N
        btnEnableUser.setName("btnEnableUser"); // NOI18N
        btnEnableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnableUserMouseClicked(evt);
            }
        });
        getContentPane().add(btnEnableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 210, 30));

        btnGetEnrollInfo.setFont(resourceMap.getFont("btnGetEnrollInfo.font")); // NOI18N
        btnGetEnrollInfo.setText(resourceMap.getString("btnGetEnrollInfo.text")); // NOI18N
        btnGetEnrollInfo.setName("btnGetEnrollInfo"); // NOI18N
        btnGetEnrollInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetEnrollInfoMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetEnrollInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 210, 30));

        btnModifyDuressFp.setFont(resourceMap.getFont("btnModifyDuressFp.font")); // NOI18N
        btnModifyDuressFp.setText(resourceMap.getString("btnModifyDuressFp.text")); // NOI18N
        btnModifyDuressFp.setName("btnModifyDuressFp"); // NOI18N
        btnModifyDuressFp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyDuressFpMouseClicked(evt);
            }
        });
        getContentPane().add(btnModifyDuressFp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 210, 30));

        btnModifyPriviege.setFont(resourceMap.getFont("btnModifyPriviege.font")); // NOI18N
        btnModifyPriviege.setText(resourceMap.getString("btnModifyPriviege.text")); // NOI18N
        btnModifyPriviege.setName("btnModifyPriviege"); // NOI18N
        btnModifyPriviege.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyPriviegeMouseClicked(evt);
            }
        });
        getContentPane().add(btnModifyPriviege, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 210, 30));

        btnClearAllData.setFont(resourceMap.getFont("btnClearAllData.font")); // NOI18N
        btnClearAllData.setText(resourceMap.getString("btnClearAllData.text")); // NOI18N
        btnClearAllData.setName("btnClearAllData"); // NOI18N
        btnClearAllData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearAllDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnClearAllData, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 210, 30));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 210, 30));

        btnDeleteDb.setFont(resourceMap.getFont("btnDeleteDb.font")); // NOI18N
        btnDeleteDb.setText(resourceMap.getString("btnDeleteDb.text")); // NOI18N
        btnDeleteDb.setName("btnDeleteDb"); // NOI18N
        btnDeleteDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteDbMouseClicked(evt);
            }
        });
        getContentPane().add(btnDeleteDb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 130, 30));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblTotal.setFont(resourceMap.getFont("lblTotal.font")); // NOI18N
        lblTotal.setText(resourceMap.getString("lblTotal.text")); // NOI18N
        lblTotal.setName("lblTotal"); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        txtPassword.setFont(resourceMap.getFont("txtPassword.font")); // NOI18N
        txtPassword.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, -1));

        txtUserTz1.setFont(resourceMap.getFont("txtUserTz1.font")); // NOI18N
        txtUserTz1.setText(resourceMap.getString("txtUserTz1.text")); // NOI18N
        txtUserTz1.setName("txtUserTz1"); // NOI18N
        getContentPane().add(txtUserTz1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 70, -1));

        txtUserTz2.setFont(resourceMap.getFont("txtUserTz2.font")); // NOI18N
        txtUserTz2.setText(resourceMap.getString("txtUserTz2.text")); // NOI18N
        txtUserTz2.setName("txtUserTz2"); // NOI18N
        getContentPane().add(txtUserTz2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 70, -1));

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        chkDisableUser.setFont(resourceMap.getFont("chkDisableUser.font")); // NOI18N
        chkDisableUser.setText(resourceMap.getString("chkDisableUser.text")); // NOI18N
        chkDisableUser.setName("chkDisableUser"); // NOI18N
        getContentPane().add(chkDisableUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstEnrollData.setName("lstEnrollData"); // NOI18N
        jScrollPane1.setViewportView(lstEnrollData);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 260, 100));

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        btnEmptyEnrollData.setFont(resourceMap.getFont("btnEmptyEnrollData.font")); // NOI18N
        btnEmptyEnrollData.setText(resourceMap.getString("btnEmptyEnrollData.text")); // NOI18N
        btnEmptyEnrollData.setName("btnEmptyEnrollData"); // NOI18N
        btnEmptyEnrollData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptyEnrollDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmptyEnrollData, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 210, 30));

        cmbDuress.setFont(resourceMap.getFont("cmbDuress.font")); // NOI18N
        cmbDuress.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", " " }));
        cmbDuress.setName("cmbDuress"); // NOI18N
        getContentPane().add(cmbDuress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 90, -1));

        cmbBackupNumber.setFont(resourceMap.getFont("cmbBackupNumber.font")); // NOI18N
        cmbBackupNumber.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "10", "11", "14", " " }));
        cmbBackupNumber.setName("cmbBackupNumber"); // NOI18N
        getContentPane().add(cmbBackupNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, -1));

        cmbPrivilege.setFont(resourceMap.getFont("cmbPrivilege.font")); // NOI18N
        cmbPrivilege.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", " " }));
        cmbPrivilege.setName("cmbPrivilege"); // NOI18N
        getContentPane().add(cmbPrivilege, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 90, -1));

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 30));

        txtEnrollNum.setFont(resourceMap.getFont("txtEnrollNum.font")); // NOI18N
        txtEnrollNum.setText(resourceMap.getString("txtEnrollNum.text")); // NOI18N
        txtEnrollNum.setName("txtEnrollNum"); // NOI18N
        getContentPane().add(txtEnrollNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 90, -1));

        txtName.setColumns(24);
        txtName.setFont(resourceMap.getFont("txtUserName.font")); // NOI18N
        txtName.setText(resourceMap.getString("txtUserName.text")); // NOI18N
        txtName.setName("txtUserName"); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 190, 20));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1078)/2, (screenSize.height-388)/2, 1078, 388);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnGetEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetEnrollDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetEnrollDataInput input = new GetEnrollDataInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwEMachineNumber = SysUtil.MachineNumber;
        try{
            input.dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
        }catch(NumberFormatException ne)
        {
            ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
            JOptionPane.showMessageDialog(this, "Enroll number format is invalid.");
        }
        
        if(input.dwBackupNumber == 10)
            input.dwBackupNumber = 15;
        
        GetEnrollDataOutput output;
        
        output = SBXPCProxy.GetEnrollData(input);
        
        if(output.isSuccess())
        {
            cmbPrivilege.setSelectedIndex((int)output.dwMachinePrivilege);
            
            if(input.dwBackupNumber == 11) // Card number
            {
                txtPassword.setText(Long.toHexString(output.dwPassword));
            }else if(input.dwBackupNumber == 14) // User time zone
            {
                txtUserTz1.setText(String.valueOf(output.dwPassword / 256));
                txtUserTz2.setText(String.valueOf(output.dwPassword % 256));
            }else if(input.dwBackupNumber == 15) // User password
            {
                String userPassword = "";
                while(output.dwPassword > 0)
                {
                    userPassword += ((output.dwPassword & 0x0F) - 1);
                    output.dwPassword /= 16;
                }
                txtPassword.setText(userPassword);
            }else
            {
                DefaultListModel model = new DefaultListModel();
                lstEnrollData.setModel(model);
                for(int i = 0; i < output.dwEnrollData.length; i ++)
                    model.addElement(output.dwEnrollData[i]);
            }
            errorCode = 0;
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetEnrollDataMouseClicked

    private void btnSetEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetEnrollDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        SetEnrollDataInput input = new SetEnrollDataInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwEMachineNumber = SysUtil.MachineNumber;
        input.dwMachinePrivilege = cmbPrivilege.getSelectedIndex();
        try{
            input.dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
        }catch(NumberFormatException ne)
        {
            ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
            JOptionPane.showMessageDialog(this, "Enroll number format is invalid.");
        }
        
        if(input.dwBackupNumber == 10)
            input.dwBackupNumber = 15;
        
        if(input.dwBackupNumber == 11)  // Card Number
        {
            try{
                input.dwPassword = Long.parseLong(txtPassword.getText(), 16);
            }catch(NumberFormatException ne)
            {
                input.dwPassword = 0;
            }
        }else if(input.dwBackupNumber == 14) // User time zone
        {
            try{
                input.dwPassword = Long.parseLong(txtUserTz1.getText());
                input.dwPassword = input.dwPassword * 256 + Long.parseLong(txtUserTz2.getText());
            }catch(NumberFormatException ne)
            {
                input.dwPassword = 0;
            }
            
        }else if(input.dwBackupNumber == 15) // User password
        {
            input.dwPassword = 0;
            String pwd = txtPassword.getText();
            int i = Math.min(pwd.length(), 4);
            while(i > 0)
            {
                input.dwPassword = input.dwPassword * 16 + pwd.charAt(i-1) - '0' + 1;
                i --;
            }
        }else 
        {
            input.dwEnrollData = new int[lstEnrollData.getModel().getSize()];
            for(int i = 0; i < lstEnrollData.getModel().getSize(); i ++)
                input.dwEnrollData[i] = Integer.parseInt(lstEnrollData.getModel().getElementAt(i).toString());
        }
        
        ret = SBXPCProxy.SetEnrollData(input);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetEnrollDataMouseClicked

    private void btnDeleteEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteEnrollDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetEnrollDataInput input = new GetEnrollDataInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwEMachineNumber = SysUtil.MachineNumber;
        try{
            input.dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
        }catch(NumberFormatException ne)
        {
            ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
            JOptionPane.showMessageDialog(this, "Enroll number format is invalid.");
        }
        
        if(input.dwBackupNumber == 10)
            input.dwBackupNumber = 15;
        
        ret = SBXPCProxy.DeleteEnrollData(input);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnDeleteEnrollDataMouseClicked

    private void btnGetNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetNameMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetUserNameInput input = new GetUserNameInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        try{
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
        }catch(NumberFormatException ne)
        {
            input.dwEnrollNumber = 1;
            txtEnrollNum.setText("1");
        }
        
        OneStringOutput output;
        output = SBXPCProxy.GetUserName(input);
        
        if(output.isSuccess())
        {
            errorCode = 0;
            txtName.setText(output.value);
        }
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetNameMouseClicked

    private void btnSetNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetNameMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        SetUserNameInput input = new SetUserNameInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.setUserName(txtName.getText());
        try{
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
        }catch(NumberFormatException ne)
        {
            input.dwEnrollNumber = 1;
            txtEnrollNum.setText("0");
        }
        
        ret = SBXPCProxy.SetUserName(input);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetNameMouseClicked

    private void btnSetCompanyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetCompanyNameMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetCompanyName(SysUtil.MachineNumber, 1, txtName.getText());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetCompanyNameMouseClicked

    private void btnDeleteCompanyNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteCompanyNameMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetCompanyName(SysUtil.MachineNumber, 0, txtName.getText());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnDeleteCompanyNameMouseClicked

    private void btnEnableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnableUserMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetEnrollDataInput input = new GetEnrollDataInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwEMachineNumber = SysUtil.MachineNumber;
        try{
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
            input.dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
        }catch(NumberFormatException ne)
        {
            input.dwEnrollNumber = 1;
            txtEnrollNum.setText("1");
            input.dwBackupNumber = 0;
            cmbBackupNumber.setSelectedIndex(0);
        }
        
        ret = SBXPCProxy.EnableUser(input, !chkDisableUser.isSelected());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEnableUserMouseClicked

    private void btnModifyPriviegeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyPriviegeMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetEnrollDataInput input = new GetEnrollDataInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwEMachineNumber = SysUtil.MachineNumber;
        try{
            input.dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
            input.dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
        }catch(NumberFormatException ne)
        {
            input.dwEnrollNumber = 1;
            txtEnrollNum.setText("1");
            input.dwBackupNumber = 0;
            cmbBackupNumber.setSelectedIndex(0);
        }
        
        ret = SBXPCProxy.ModifyPrivilege(input, cmbPrivilege.getSelectedIndex());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnModifyPriviegeMouseClicked

    private void btnModifyDuressFpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyDuressFpMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        long dwEnrollNumber;
        long dwBackupNumber;
        try{
            dwEnrollNumber = Long.parseLong(txtEnrollNum.getText());
            dwBackupNumber = Long.parseLong(cmbBackupNumber.getSelectedItem().toString());
        }catch(NumberFormatException ne)
        {
            dwEnrollNumber = 1;
            txtEnrollNum.setText("1");
            dwBackupNumber = 0;
            cmbBackupNumber.setSelectedIndex(0);
        }
        
        ret = SBXPCProxy.ModifyDuressFP(SysUtil.MachineNumber, dwEnrollNumber, dwBackupNumber, cmbDuress.getSelectedIndex());
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnModifyDuressFpMouseClicked

    private void btnEmptyEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptyEnrollDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.EmptyEnrollData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEmptyEnrollDataMouseClicked

    private void btnClearAllDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearAllDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ClearKeeperData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnClearAllDataMouseClicked

    private void btnGetEnrollInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetEnrollInfoMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllUserID(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;
            GetAllUserIDOutput output;
            String element = "No.    EnNo   EMNo   Fp   Priv  Enable Duress";
            DefaultListModel listModel = new DefaultListModel();
            listModel.addElement(element);
            
            NumberFormat format2 = new DecimalFormat("00");
            NumberFormat format3 = new DecimalFormat("000");
            NumberFormat format5 = new DecimalFormat("00000");
            int count = 0;
            while(true)
            {
                output = SBXPCProxy.GetAllUserID(SysUtil.MachineNumber);
                if(!output.isSuccess()) break;
                element = format3.format(count) + "   ";
                element += format5.format(output.dwEnrollNumber) + "    ";
                element += format3.format(output.dwEMachineNumber) + "      ";
                element += format2.format(output.dwBackupNumber) + "    ";
                element += String.valueOf(output.dwMachinePrivilege) + "        ";
                element += String.valueOf(output.dwEnable % 256) + "        ";
                element += String.valueOf(output.dwEnable / 256);
                
                listModel.addElement(element);
                
                count ++;
            }
            lstEnrollData.setModel(listModel);
            lblTotal.setText("Total: " + count);
        }
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetEnrollInfoMouseClicked

    private void btnGetAllEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetAllEnrollDataMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllUserID(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;

            int count = 0;
            GetAllUserIDOutput userIdOutput;
            GetEnrollDataInput enrollDataInput = new GetEnrollDataInput();
            GetEnrollDataOutput enrollDataOutput;
            UserEnrollData enrollData = new UserEnrollData();
            while(true)
            {
                userIdOutput = SBXPCProxy.GetAllUserID(SysUtil.MachineNumber);
                
                if(!userIdOutput.isSuccess())
                    break;
                
                if(userIdOutput.dwBackupNumber >= 50)
                    continue;
                
                enrollDataInput.dwMachineNumber = SysUtil.MachineNumber;
                enrollDataInput.dwEMachineNumber = SysUtil.MachineNumber;
                enrollDataInput.dwEnrollNumber = userIdOutput.dwEnrollNumber;
                enrollDataInput.dwBackupNumber = userIdOutput.dwBackupNumber;
                
                enrollDataOutput = SBXPCProxy.GetEnrollData(enrollDataInput);
                
                if(enrollDataOutput.isSuccess())
                {
                    enrollData.machineNo = (int)SysUtil.MachineNumber;
                    enrollData.enrollNo = (int)enrollDataInput.dwEnrollNumber;
                    enrollData.fingerNo = (int)enrollDataInput.dwBackupNumber;
                    enrollData.password = (int)enrollDataOutput.dwPassword;
                    enrollData.privilege = (int)enrollDataOutput.dwMachinePrivilege;
                    enrollData.fpData = new int[enrollDataOutput.dwEnrollData.length];
                    System.arraycopy(enrollDataOutput.dwEnrollData, 0, enrollData.fpData, 0, enrollDataOutput.dwEnrollData.length);
                    try{
                        EnrollDBUtil.updateEnrollData(enrollData);
                        count ++;
                    }catch(SQLException se){
                        se.printStackTrace();
                    }
                }else
                {
                    errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
                    int selOpt = JOptionPane.showConfirmDialog(this, SysUtil.ErrorPrint(errorCode), "Continue?", JOptionPane.YES_NO_OPTION);
                    if(selOpt == JOptionPane.NO_OPTION)
                        break;
                }
            }
            lblTotal.setText("Total: " + count);
        }
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetAllEnrollDataMouseClicked

    private void btnSetAllEnrollDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetAllEnrollDataMouseClicked
        List<UserEnrollData> enrollDataList = new ArrayList<UserEnrollData>();
        try {
            EnrollDBUtil.getAllEnrollData(SysUtil.MachineNumber, enrollDataList);
        } catch (SQLException ex) {
            Logger.getLogger(EnrollMngFrame.class.getName()).log(Level.SEVERE, null, ex);
            return;
        }

        boolean ret;
        int errorCode = 0;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        Iterator<UserEnrollData> iter = enrollDataList.iterator();
        UserEnrollData enrollData;
        SetEnrollDataInput input;
        while(iter.hasNext())
        {
            input = new SetEnrollDataInput();
            enrollData = iter.next();
            input.dwMachineNumber = enrollData.machineNo;
            input.dwEMachineNumber = enrollData.machineNo;
            input.dwEnrollNumber = enrollData.enrollNo;
            input.dwBackupNumber = enrollData.fingerNo;
            input.dwMachinePrivilege = enrollData.privilege;
            input.dwPassword = enrollData.password;
            input.dwEnrollData = enrollData.fpData;
            
            ret = SBXPCProxy.SetEnrollData(input);
            
            if(ret)
                errorCode = 0;
            else
                errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }

        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetAllEnrollDataMouseClicked

    private void btnDeleteDbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteDbMouseClicked
        try {
            EnrollDBUtil.deleteAllEnrollData(SysUtil.MachineNumber);
            lblTotal.setText("Total: 0");
        } catch (SQLException ex) {
            Logger.getLogger(EnrollMngFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDeleteDbMouseClicked

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        if (Character.isLetter(evt.getKeyChar()))
        {
            String tempName = txtName.getText();
            txtName.replaceSelection(String.valueOf(evt.getKeyChar()));
            if (txtName.getText().length() >= 24)
                txtName.setText(tempName);
            evt.consume();
        }
    }//GEN-LAST:event_txtNameKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearAllData;
    private javax.swing.JButton btnDeleteCompanyName;
    private javax.swing.JButton btnDeleteDb;
    private javax.swing.JButton btnDeleteEnrollData;
    private javax.swing.JButton btnEmptyEnrollData;
    private javax.swing.JButton btnEnableUser;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetAllEnrollData;
    private javax.swing.JButton btnGetEnrollData;
    private javax.swing.JButton btnGetEnrollInfo;
    private javax.swing.JButton btnGetName;
    private javax.swing.JButton btnModifyDuressFp;
    private javax.swing.JButton btnModifyPriviege;
    private javax.swing.JButton btnSendAllEnrollData;
    private javax.swing.JButton btnSetAllEnrollData;
    private javax.swing.JButton btnSetCompanyName;
    private javax.swing.JButton btnSetEnrollData;
    private javax.swing.JButton btnSetName;
    private javax.swing.JCheckBox chkDisableUser;
    private javax.swing.JComboBox cmbBackupNumber;
    private javax.swing.JComboBox cmbDuress;
    private javax.swing.JComboBox cmbPrivilege;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList lstEnrollData;
    private javax.swing.JTextField txtEnrollNum;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserTz1;
    private javax.swing.JTextField txtUserTz2;
    // End of variables declaration//GEN-END:variables

    public void willExit() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}

