/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogMngFrame.java
 *
 * Created on Aug 20, 2011, 11:15:33 AM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import smack.comm.SBXPCProxy;
import smack.comm.data.GeneralLogData;
import smack.comm.data.SuperLogData;
import smack.comm.output.GeneralLogDataOutput;
import smack.comm.output.SuperLogDataOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class LogMngFrame extends javax.swing.JFrame {

    SLogDataListModel superLogListModel = new SLogDataListModel();
    GLogDataListModel generalLogListModel = new GLogDataListModel();
    
    private int prevSelectedRow = -1;
    /** Creates new form LogMngFrame */
    public LogMngFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogList = new javax.swing.JTable();
        btnDoorOpen1 = new javax.swing.JButton();
        btnReadSLogData = new javax.swing.JButton();
        btnReadAllSLogData = new javax.swing.JButton();
        btnEmptySLogData = new javax.swing.JButton();
        btnReadGLogData = new javax.swing.JButton();
        btnReadAllGLogData = new javax.swing.JButton();
        btnEmptyGLogData = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkSearchAndDelete = new javax.swing.JCheckBox();
        chkReadMark = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(LogMngFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 31));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblLogList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLogList.setName("tblLogList"); // NOI18N
        tblLogList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblLogList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 870, 350));

        btnDoorOpen1.setFont(resourceMap.getFont("btnDoorOpen1.font")); // NOI18N
        btnDoorOpen1.setText(resourceMap.getString("btnDoorOpen1.text")); // NOI18N
        btnDoorOpen1.setName("btnDoorOpen1"); // NOI18N
        btnDoorOpen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoorOpen1MouseClicked(evt);
            }
        });
        getContentPane().add(btnDoorOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 110, 50));

        btnReadSLogData.setFont(resourceMap.getFont("btnReadSLogData.font")); // NOI18N
        btnReadSLogData.setText("<html><center>Read<br>SLog Data</center></html>");
        btnReadSLogData.setName("btnReadSLogData"); // NOI18N
        btnReadSLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadSLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadSLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 110, 50));

        btnReadAllSLogData.setFont(resourceMap.getFont("btnReadAllSLogData.font")); // NOI18N
        btnReadAllSLogData.setText("<html><center>Read<br>All SLog Data<center></html>");
        btnReadAllSLogData.setName("btnReadAllSLogData"); // NOI18N
        btnReadAllSLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadAllSLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadAllSLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 110, 50));

        btnEmptySLogData.setFont(resourceMap.getFont("btnEmptySLogData.font")); // NOI18N
        btnEmptySLogData.setText("<html><center>Empty<br>SLog Data<center></html>");
        btnEmptySLogData.setName("btnEmptySLogData"); // NOI18N
        btnEmptySLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptySLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmptySLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 50));

        btnReadGLogData.setFont(resourceMap.getFont("btnReadGLogData.font")); // NOI18N
        btnReadGLogData.setText("<html><center>Read<br>GLog Data<center></html>");
        btnReadGLogData.setName("btnReadGLogData"); // NOI18N
        btnReadGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 110, 50));

        btnReadAllGLogData.setFont(resourceMap.getFont("btnReadAllGLogData.font")); // NOI18N
        btnReadAllGLogData.setText("<html><center>Read<br>All GLog Data<center></html>");
        btnReadAllGLogData.setName("btnReadAllGLogData"); // NOI18N
        btnReadAllGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadAllGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadAllGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 110, 50));

        btnEmptyGLogData.setFont(resourceMap.getFont("btnEmptyGLogData.font")); // NOI18N
        btnEmptyGLogData.setText("<html><center>Empty<br>GLog Data<center></html>");
        btnEmptyGLogData.setName("btnEmptyGLogData"); // NOI18N
        btnEmptyGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptyGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmptyGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 110, 50));

        lblTotal.setFont(resourceMap.getFont("lblTotal.font")); // NOI18N
        lblTotal.setText(resourceMap.getString("lblTotal.text")); // NOI18N
        lblTotal.setName("lblTotal"); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        chkSearchAndDelete.setFont(resourceMap.getFont("chkSearchAndDelete.font")); // NOI18N
        chkSearchAndDelete.setText(resourceMap.getString("chkSearchAndDelete.text")); // NOI18N
        chkSearchAndDelete.setName("chkSearchAndDelete"); // NOI18N
        getContentPane().add(chkSearchAndDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 55, -1, -1));

        chkReadMark.setFont(resourceMap.getFont("chkReadMark.font")); // NOI18N
        chkReadMark.setSelected(true);
        chkReadMark.setText(resourceMap.getString("chkReadMark.text")); // NOI18N
        chkReadMark.setName("chkReadMark"); // NOI18N
        getContentPane().add(chkReadMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 55, -1, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-910)/2, (screenSize.height-544)/2, 910, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnDoorOpen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoorOpen1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnDoorOpen1MouseClicked

    private void btnReadSLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadSLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadSuperLogData(SysUtil.MachineNumber, chkReadMark.isSelected());
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            SuperLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetSuperLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                superLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + superLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);

    }//GEN-LAST:event_btnReadSLogDataMouseClicked

    private void btnReadAllSLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadAllSLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllSLogData(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            SuperLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetAllSLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                superLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + superLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadAllSLogDataMouseClicked

    private void btnEmptySLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptySLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEmptySLogDataMouseClicked

    private void btnEmptyGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptyGLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEmptyGLogDataMouseClicked

    private void btnReadGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadGLogDataMouseClicked
        generalLogListModel.removeAll();
        tblLogList.setModel(generalLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadGeneralLogData(SysUtil.MachineNumber, chkReadMark.isSelected());
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            GeneralLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetGeneralLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                generalLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + generalLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadGLogDataMouseClicked

    private void btnReadAllGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadAllGLogDataMouseClicked
        generalLogListModel.removeAll();
        tblLogList.setModel(generalLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllGLogData(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            GeneralLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetAllGLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                generalLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + generalLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadAllGLogDataMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoorOpen1;
    private javax.swing.JButton btnEmptyGLogData;
    private javax.swing.JButton btnEmptySLogData;
    private javax.swing.JButton btnReadAllGLogData;
    private javax.swing.JButton btnReadAllSLogData;
    private javax.swing.JButton btnReadGLogData;
    private javax.swing.JButton btnReadSLogData;
    private javax.swing.JCheckBox chkReadMark;
    private javax.swing.JCheckBox chkSearchAndDelete;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblLogList;
    // End of variables declaration//GEN-END:variables
}

class SLogDataListModel extends AbstractTableModel
{
    final String[] COLUMN_TEXT = 
                    {
                        "TMNo",
                        "SEnlNo",
                        "SMNo",
                        "GEnlNo",
                        "GMNo",
                        "Manipulation",
                        "FpNo",
                        "DateTime",
                    };
    List<SuperLogData> logList;

    public void addSLogData(SuperLogData logData)
    {
        logList.add(logData);
        fireTableRowsInserted(logList.size()-1, logList.size()-1);
    }

    public void removeAll()
    {
        logList.removeAll(logList);
        fireTableDataChanged();
    }

    public SLogDataListModel(){
        logList = new ArrayList<SuperLogData>();
    }

    public int getRowCount() {
        return logList.size();
    }

    public int getColumnCount() {
        return COLUMN_TEXT.length;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        SuperLogData logData = logList.get(rowIndex);
        switch(columnIndex)
        {
            case 0:
                return logData.dwTMachineNumber;
            case 1:
                return logData.dwSEnrollNumber;
            case 2:
                return logData.dwSMachineNumber;
            case 3:
                return logData.dwGEnrollNumber;
            case 4:
                return logData.dwGMachineNumber;
            case 5:
            {
                String ret;
                switch((int)logData.dwManipulation)
                {
                case 3:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Enroll User";
                case 4:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Enroll Manager";
                case 5:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Fp Data";
                case 6:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Password";
                case 7:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Card Data";
                case 8:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete All LogData";
                case 9:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify System Info";
                case 10:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify System Time";
                case 11:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Log Setting";
                case 12:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Comm Setting";
                case 13:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Timezone Setting";
                default:
                    ret = "--Unknown--";
                }
                return ret;
            }
            case 6:
                if(logData.dwBackupNumber < 10)
                    return logData.dwBackupNumber;
                else if(logData.dwBackupNumber == 10)
                    return "Password";
                else
                    return "Card";
            case 7:
            {
                NumberFormat formatter = new DecimalFormat("00");
                String ret = String.valueOf(logData.dwYear) + "/" + formatter.format(logData.dwMonth) + "/" + formatter.format(logData.dwDay) + " ";
                ret += formatter.format(logData.dwHour) + ":" + formatter.format(logData.dwMinute) + ":" + formatter.format(logData.dwSecond);
                return ret;
            }
            default:
                return null;
        }
    }

    @Override
    public String getColumnName(int columnIndex) {
        return COLUMN_TEXT[columnIndex];
    }
}

class GLogDataListModel extends AbstractTableModel
{
    final String[] COLUMN_TEXT = 
                    {
                        "TMNo",
                        "EnrollNo",
                        "EMachineNo",
                        "VeriMode",
                        "DateTime",
                        "DaiGong",
                    };
    List<GeneralLogData> logList;

    public void addSLogData(GeneralLogData logData)
    {
        logList.add(logData);
        fireTableRowsInserted(logList.size()-1, logList.size()-1);
    }

    public void removeAll()
    {
        logList.removeAll(logList);
        fireTableDataChanged();
    }

    public GLogDataListModel(){
        logList = new ArrayList<GeneralLogData>();
    }

    public int getRowCount() {
        return logList.size();
    }

    public int getColumnCount() {
        return COLUMN_TEXT.length;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        GeneralLogData logData = logList.get(rowIndex);
        
        int attendStatus, antipassStatus, daigong, verifyMode;
        
        antipassStatus = (int)logData.dwVerifyMode / 65536;
        daigong = antipassStatus / 4;
        antipassStatus = antipassStatus % 4;
        verifyMode = (int)logData.dwVerifyMode % 65536;
        attendStatus = verifyMode / 256;
        verifyMode = verifyMode % 256;
        
        String strAttendStatus, strAntipassStatus, strVerifyMode;
        switch(attendStatus)
        {
            case 0: strAttendStatus = "_Duty On";        break;
            case 1: strAttendStatus = "_Duty Off";       break;
            case 2: strAttendStatus = "_Overtime On";    break;
            case 3: strAttendStatus = "_Overtime Off";   break;
            case 4: strAttendStatus = "_Go In";          break;
            case 5: strAttendStatus = "_Go Out";         break;
            default: strAttendStatus = "";
        }
        
        switch(antipassStatus)
        {
            case 1: strAntipassStatus = ":AP_In";     break;
            case 2: strAntipassStatus = ":AP_Out";    break;
            default: strAntipassStatus = "";
        }
        
        switch(verifyMode)
        {
            case 0: strVerifyMode = "FP+ID"; break;
            case 1: strVerifyMode = "FP"; break;
            case 2: strVerifyMode = "Password"; break;
            case 3: strVerifyMode = "Card"; break;
            case 4: strVerifyMode = "FP+Card"; break;
            case 5: strVerifyMode = "FP+Pwd"; break;
            case 6: strVerifyMode = "Card+Pwd"; break;
            case 7: strVerifyMode = "FP+Card+Pwd"; break;
            case 10: strVerifyMode = "Hand Lock"; break;
            case 11: strVerifyMode = "Prog Lock"; break;
            case 12: strVerifyMode = "Prog Open"; break;
            case 13: strVerifyMode = "Prog Close"; break;
            case 14: strVerifyMode = "Auto Recover"; break;
            case 20: strVerifyMode = "Lock Over"; break;
            case 21: strVerifyMode = "Illegal Open"; break;
            case 22: strVerifyMode = "Duress alarm"; break;
            case 23: strVerifyMode = "Tamper detect"; break;
            case 51: strVerifyMode = "FP"; break;
            case 52: strVerifyMode = "Password"; break;
            case 53: strVerifyMode = "Password"; break;
            case 101: strVerifyMode = "FP"; break;
            case 102: strVerifyMode = "Password"; break;
            case 103: strVerifyMode = "Password"; break;
            case 151: strVerifyMode = "FP"; break;
            case 152: strVerifyMode = "Password"; break;
            case 153: strVerifyMode = "Password"; break;
            default: strVerifyMode = ""; break;
        }

        switch(columnIndex)
        {
            case 0:
                return (logData.dwTMachineNumber == -1? "No Photo" : logData.dwTMachineNumber);
            case 1:
                return logData.dwEnrollNumber;
            case 2:
                return logData.dwEMachineNumber;
            case 3:
            case 4:
            {
                NumberFormat formatter = new DecimalFormat("00");
                String ret = String.valueOf(logData.dwYear) + "/" + formatter.format(logData.dwMonth) + "/" + formatter.format(logData.dwDay) + " ";
                ret += formatter.format(logData.dwHour) + ":" + formatter.format(logData.dwMinute) + ":" + formatter.format(logData.dwSecond);
                return ret;
            }
            case 5:
                return strVerifyMode + strAttendStatus + strAntipassStatus;
            default:
                return null;
        }
    }

    @Override
    public String getColumnName(int columnIndex) {
        return COLUMN_TEXT[columnIndex];
    }
}


