/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BellSettingFrame.java
 *
 * Created on Aug 19, 2011, 5:07:33 PM
 */
package smack.comm.sample;

import javax.swing.JCheckBox;
import javax.swing.JTextField;
import smack.comm.SBXPCProxy;
import smack.comm.output.GetBellTimeOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class BellSettingFrame extends javax.swing.JFrame {

    /** Creates new form BellSettingFrame */
    
    public static final int MAX_BELLCOUNT_DAY = 24;
    
    JTextField[] txtHour;
    JTextField[] txtMinute;
    JCheckBox[] chkUseFlag;
    
    GetBellTimeOutput dbBellSetting;
    
    public BellSettingFrame() {
        initComponents();
        initFrame();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtBellCount = new javax.swing.JTextField();
        _txtHour_0 = new javax.swing.JTextField();
        _txtMinute_0 = new javax.swing.JTextField();
        _chkUseFlag_2 = new javax.swing.JCheckBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        _chkUseFlag_0 = new javax.swing.JCheckBox();
        jLabel36 = new javax.swing.JLabel();
        _txtHour_1 = new javax.swing.JTextField();
        _txtMinute_1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        _txtHour_2 = new javax.swing.JTextField();
        _txtMinute_2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        _txtHour_3 = new javax.swing.JTextField();
        _txtMinute_3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        _txtHour_4 = new javax.swing.JTextField();
        _txtMinute_4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        _txtHour_5 = new javax.swing.JTextField();
        _txtMinute_5 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        _txtHour_6 = new javax.swing.JTextField();
        _txtMinute_6 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        _txtHour_7 = new javax.swing.JTextField();
        _txtMinute_7 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jTextField33 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        _txtHour_8 = new javax.swing.JTextField();
        _txtMinute_8 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        _txtHour_9 = new javax.swing.JTextField();
        _txtMinute_9 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        _txtHour_10 = new javax.swing.JTextField();
        _txtMinute_10 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        _txtHour_11 = new javax.swing.JTextField();
        _txtMinute_11 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField48 = new javax.swing.JTextField();
        jTextField49 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        _chkUseFlag_1 = new javax.swing.JCheckBox();
        _chkUseFlag_5 = new javax.swing.JCheckBox();
        _chkUseFlag_3 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        _chkUseFlag_4 = new javax.swing.JCheckBox();
        _chkUseFlag_8 = new javax.swing.JCheckBox();
        _chkUseFlag_6 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        _chkUseFlag_7 = new javax.swing.JCheckBox();
        _chkUseFlag_11 = new javax.swing.JCheckBox();
        _chkUseFlag_9 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        _chkUseFlag_10 = new javax.swing.JCheckBox();
        jLabel47 = new javax.swing.JLabel();
        _txtHour_12 = new javax.swing.JTextField();
        _txtMinute_12 = new javax.swing.JTextField();
        _chkUseFlag_14 = new javax.swing.JCheckBox();
        jLabel58 = new javax.swing.JLabel();
        jTextField52 = new javax.swing.JTextField();
        jTextField53 = new javax.swing.JTextField();
        _chkUseFlag_12 = new javax.swing.JCheckBox();
        jLabel59 = new javax.swing.JLabel();
        _txtHour_13 = new javax.swing.JTextField();
        _txtMinute_13 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jTextField56 = new javax.swing.JTextField();
        jTextField57 = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        _txtHour_14 = new javax.swing.JTextField();
        _txtMinute_14 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jTextField60 = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        _txtHour_15 = new javax.swing.JTextField();
        _txtMinute_15 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField64 = new javax.swing.JTextField();
        jTextField65 = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        _txtHour_16 = new javax.swing.JTextField();
        _txtMinute_16 = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jTextField68 = new javax.swing.JTextField();
        jTextField69 = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        _txtHour_17 = new javax.swing.JTextField();
        _txtMinute_17 = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        jTextField72 = new javax.swing.JTextField();
        jTextField73 = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        _txtHour_18 = new javax.swing.JTextField();
        _txtMinute_18 = new javax.swing.JTextField();
        jTextField76 = new javax.swing.JTextField();
        jTextField77 = new javax.swing.JTextField();
        jLabel70 = new javax.swing.JLabel();
        _txtHour_19 = new javax.swing.JTextField();
        _txtMinute_19 = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jTextField80 = new javax.swing.JTextField();
        jTextField81 = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        _txtHour_20 = new javax.swing.JTextField();
        _txtMinute_20 = new javax.swing.JTextField();
        jLabel73 = new javax.swing.JLabel();
        jTextField84 = new javax.swing.JTextField();
        jTextField85 = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        _txtHour_21 = new javax.swing.JTextField();
        _txtMinute_21 = new javax.swing.JTextField();
        jLabel75 = new javax.swing.JLabel();
        jTextField88 = new javax.swing.JTextField();
        jTextField89 = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        _txtHour_22 = new javax.swing.JTextField();
        _txtMinute_22 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        jTextField92 = new javax.swing.JTextField();
        jTextField93 = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        _txtHour_23 = new javax.swing.JTextField();
        _txtMinute_23 = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        jTextField96 = new javax.swing.JTextField();
        jTextField97 = new javax.swing.JTextField();
        jCheckBox19 = new javax.swing.JCheckBox();
        _chkUseFlag_13 = new javax.swing.JCheckBox();
        _chkUseFlag_17 = new javax.swing.JCheckBox();
        _chkUseFlag_15 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        _chkUseFlag_16 = new javax.swing.JCheckBox();
        _chkUseFlag_20 = new javax.swing.JCheckBox();
        _chkUseFlag_18 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        _chkUseFlag_19 = new javax.swing.JCheckBox();
        _chkUseFlag_23 = new javax.swing.JCheckBox();
        _chkUseFlag_21 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        _chkUseFlag_22 = new javax.swing.JCheckBox();
        btnExit = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnWrite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(BellSettingFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 630, 31));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, 20));

        jLabel4.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, 20));

        jLabel5.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 20));

        jLabel6.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 20));

        jLabel7.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, 20));

        jLabel8.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 20));

        jLabel9.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, 20));

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 20));

        jLabel11.setFont(resourceMap.getFont("jLabel11.font")); // NOI18N
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 100, -1, 20));

        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 20));

        jLabel13.setFont(resourceMap.getFont("jLabel13.font")); // NOI18N
        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 20));

        jLabel14.setFont(resourceMap.getFont("jLabel14.font")); // NOI18N
        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 20));

        jLabel15.setFont(resourceMap.getFont("jLabel15.font")); // NOI18N
        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        jLabel16.setFont(resourceMap.getFont("jLabel16.font")); // NOI18N
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        jLabel17.setFont(resourceMap.getFont("jLabel17.font")); // NOI18N
        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 20));

        jLabel18.setFont(resourceMap.getFont("jLabel18.font")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 20));

        jLabel19.setFont(resourceMap.getFont("jLabel19.font")); // NOI18N
        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jLabel20.setFont(resourceMap.getFont("jLabel20.font")); // NOI18N
        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 20));

        jLabel21.setFont(resourceMap.getFont("jLabel21.font")); // NOI18N
        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, 20));

        jLabel22.setFont(resourceMap.getFont("jLabel22.font")); // NOI18N
        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, 20));

        jLabel23.setFont(resourceMap.getFont("jLabel23.font")); // NOI18N
        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, 20));

        jLabel24.setFont(resourceMap.getFont("jLabel24.font")); // NOI18N
        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, 20));

        jLabel25.setFont(resourceMap.getFont("jLabel25.font")); // NOI18N
        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, 20));

        jLabel26.setFont(resourceMap.getFont("jLabel26.font")); // NOI18N
        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 20));

        jLabel27.setFont(resourceMap.getFont("jLabel27.font")); // NOI18N
        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, 20));

        jLabel28.setFont(resourceMap.getFont("jLabel28.font")); // NOI18N
        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, -1, 20));

        jLabel29.setFont(resourceMap.getFont("jLabel29.font")); // NOI18N
        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, 20));

        jLabel30.setFont(resourceMap.getFont("jLabel30.font")); // NOI18N
        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, 20));

        jLabel31.setFont(resourceMap.getFont("jLabel31.font")); // NOI18N
        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, 20));

        jLabel32.setFont(resourceMap.getFont("jLabel32.font")); // NOI18N
        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, 20));

        jLabel33.setFont(resourceMap.getFont("jLabel33.font")); // NOI18N
        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, 20));

        txtBellCount.setFont(resourceMap.getFont("txtBellCount.font")); // NOI18N
        txtBellCount.setText(resourceMap.getString("txtBellCount.text")); // NOI18N
        txtBellCount.setName("txtBellCount"); // NOI18N
        getContentPane().add(txtBellCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 40, -1));

        _txtHour_0.setFont(resourceMap.getFont("_txtHour_0.font")); // NOI18N
        _txtHour_0.setName("_txtHour_0"); // NOI18N
        getContentPane().add(_txtHour_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, -1));

        _txtMinute_0.setFont(resourceMap.getFont("_txtMinute_0.font")); // NOI18N
        _txtMinute_0.setName("_txtMinute_0"); // NOI18N
        getContentPane().add(_txtMinute_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, -1));

        _chkUseFlag_2.setText(resourceMap.getString("_chkUseFlag_2.text")); // NOI18N
        _chkUseFlag_2.setName("_chkUseFlag_2"); // NOI18N
        getContentPane().add(_chkUseFlag_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jLabel34.setFont(resourceMap.getFont("jLabel34.font")); // NOI18N
        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 20));

        jLabel35.setFont(resourceMap.getFont("jLabel35.font")); // NOI18N
        jLabel35.setText(resourceMap.getString("jLabel35.text")); // NOI18N
        jLabel35.setName("jLabel35"); // NOI18N
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, 20));

        jTextField4.setFont(resourceMap.getFont("jTextField4.font")); // NOI18N
        jTextField4.setName("jTextField4"); // NOI18N
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, -1));

        jTextField5.setFont(resourceMap.getFont("jTextField5.font")); // NOI18N
        jTextField5.setName("jTextField5"); // NOI18N
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 40, -1));

        _chkUseFlag_0.setName("_chkUseFlag_0"); // NOI18N
        getContentPane().add(_chkUseFlag_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel36.setFont(resourceMap.getFont("jLabel36.font")); // NOI18N
        jLabel36.setText(resourceMap.getString("jLabel36.text")); // NOI18N
        jLabel36.setName("jLabel36"); // NOI18N
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 130, -1, 20));

        _txtHour_1.setFont(resourceMap.getFont("_txtHour_1.font")); // NOI18N
        _txtHour_1.setName("_txtHour_1"); // NOI18N
        getContentPane().add(_txtHour_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, -1));

        _txtMinute_1.setFont(resourceMap.getFont("_txtMinute_1.font")); // NOI18N
        _txtMinute_1.setName("_txtMinute_1"); // NOI18N
        getContentPane().add(_txtMinute_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 40, -1));

        jLabel37.setFont(resourceMap.getFont("jLabel37.font")); // NOI18N
        jLabel37.setText(resourceMap.getString("jLabel37.text")); // NOI18N
        jLabel37.setName("jLabel37"); // NOI18N
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 20));

        jTextField8.setFont(resourceMap.getFont("jTextField8.font")); // NOI18N
        jTextField8.setName("jTextField8"); // NOI18N
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 40, -1));

        jTextField9.setFont(resourceMap.getFont("jTextField9.font")); // NOI18N
        jTextField9.setName("jTextField9"); // NOI18N
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 40, -1));

        jLabel38.setFont(resourceMap.getFont("jLabel38.font")); // NOI18N
        jLabel38.setText(resourceMap.getString("jLabel38.text")); // NOI18N
        jLabel38.setName("jLabel38"); // NOI18N
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 160, -1, 20));

        _txtHour_2.setFont(resourceMap.getFont("_txtHour_2.font")); // NOI18N
        _txtHour_2.setName("_txtHour_2"); // NOI18N
        getContentPane().add(_txtHour_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, -1));

        _txtMinute_2.setFont(resourceMap.getFont("_txtMinute_2.font")); // NOI18N
        _txtMinute_2.setName("_txtMinute_2"); // NOI18N
        getContentPane().add(_txtMinute_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 40, -1));

        jLabel39.setFont(resourceMap.getFont("jLabel39.font")); // NOI18N
        jLabel39.setText(resourceMap.getString("jLabel39.text")); // NOI18N
        jLabel39.setName("jLabel39"); // NOI18N
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, 20));

        jTextField12.setFont(resourceMap.getFont("jTextField12.font")); // NOI18N
        jTextField12.setName("jTextField12"); // NOI18N
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 40, -1));

        jTextField13.setFont(resourceMap.getFont("jTextField13.font")); // NOI18N
        jTextField13.setName("jTextField13"); // NOI18N
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 40, -1));

        jLabel40.setFont(resourceMap.getFont("jLabel40.font")); // NOI18N
        jLabel40.setText(resourceMap.getString("jLabel40.text")); // NOI18N
        jLabel40.setName("jLabel40"); // NOI18N
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 190, -1, 20));

        _txtHour_3.setFont(resourceMap.getFont("_txtHour_3.font")); // NOI18N
        _txtHour_3.setName("_txtHour_3"); // NOI18N
        getContentPane().add(_txtHour_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 40, -1));

        _txtMinute_3.setFont(resourceMap.getFont("_txtMinute_3.font")); // NOI18N
        _txtMinute_3.setName("_txtMinute_3"); // NOI18N
        getContentPane().add(_txtMinute_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 40, -1));

        jLabel41.setFont(resourceMap.getFont("jLabel41.font")); // NOI18N
        jLabel41.setText(resourceMap.getString("jLabel41.text")); // NOI18N
        jLabel41.setName("jLabel41"); // NOI18N
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, 20));

        jTextField16.setFont(resourceMap.getFont("jTextField16.font")); // NOI18N
        jTextField16.setName("jTextField16"); // NOI18N
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 40, -1));

        jTextField17.setFont(resourceMap.getFont("jTextField17.font")); // NOI18N
        jTextField17.setName("jTextField17"); // NOI18N
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 40, -1));

        jLabel42.setFont(resourceMap.getFont("jLabel42.font")); // NOI18N
        jLabel42.setText(resourceMap.getString("jLabel42.text")); // NOI18N
        jLabel42.setName("jLabel42"); // NOI18N
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 220, -1, 20));

        _txtHour_4.setFont(resourceMap.getFont("_txtHour_4.font")); // NOI18N
        _txtHour_4.setName("_txtHour_4"); // NOI18N
        getContentPane().add(_txtHour_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 40, -1));

        _txtMinute_4.setFont(resourceMap.getFont("_txtMinute_4.font")); // NOI18N
        _txtMinute_4.setName("_txtMinute_4"); // NOI18N
        getContentPane().add(_txtMinute_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 40, -1));

        jLabel43.setFont(resourceMap.getFont("jLabel43.font")); // NOI18N
        jLabel43.setText(resourceMap.getString("jLabel43.text")); // NOI18N
        jLabel43.setName("jLabel43"); // NOI18N
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, 20));

        jTextField20.setFont(resourceMap.getFont("jTextField20.font")); // NOI18N
        jTextField20.setName("jTextField20"); // NOI18N
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 40, -1));

        jTextField21.setFont(resourceMap.getFont("jTextField21.font")); // NOI18N
        jTextField21.setName("jTextField21"); // NOI18N
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 40, -1));

        jLabel44.setFont(resourceMap.getFont("jLabel44.font")); // NOI18N
        jLabel44.setText(resourceMap.getString("jLabel44.text")); // NOI18N
        jLabel44.setName("jLabel44"); // NOI18N
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 250, -1, 20));

        _txtHour_5.setFont(resourceMap.getFont("_txtHour_5.font")); // NOI18N
        _txtHour_5.setName("_txtHour_5"); // NOI18N
        getContentPane().add(_txtHour_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, -1));

        _txtMinute_5.setFont(resourceMap.getFont("_txtMinute_5.font")); // NOI18N
        _txtMinute_5.setName("_txtMinute_5"); // NOI18N
        getContentPane().add(_txtMinute_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 40, -1));

        jLabel45.setFont(resourceMap.getFont("jLabel45.font")); // NOI18N
        jLabel45.setText(resourceMap.getString("jLabel45.text")); // NOI18N
        jLabel45.setName("jLabel45"); // NOI18N
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, 20));

        jTextField24.setFont(resourceMap.getFont("jTextField24.font")); // NOI18N
        jTextField24.setName("jTextField24"); // NOI18N
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 40, -1));

        jTextField25.setFont(resourceMap.getFont("jTextField25.font")); // NOI18N
        jTextField25.setName("jTextField25"); // NOI18N
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 40, -1));

        jLabel46.setFont(resourceMap.getFont("jLabel46.font")); // NOI18N
        jLabel46.setText(resourceMap.getString("jLabel46.text")); // NOI18N
        jLabel46.setName("jLabel46"); // NOI18N
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 280, -1, 20));

        _txtHour_6.setFont(resourceMap.getFont("_txtHour_6.font")); // NOI18N
        _txtHour_6.setName("_txtHour_6"); // NOI18N
        getContentPane().add(_txtHour_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, -1));

        _txtMinute_6.setFont(resourceMap.getFont("_txtMinute_6.font")); // NOI18N
        _txtMinute_6.setName("_txtMinute_6"); // NOI18N
        getContentPane().add(_txtMinute_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 40, -1));

        jTextField28.setFont(resourceMap.getFont("jTextField28.font")); // NOI18N
        jTextField28.setName("jTextField28"); // NOI18N
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 40, -1));

        jTextField29.setFont(resourceMap.getFont("jTextField29.font")); // NOI18N
        jTextField29.setName("jTextField29"); // NOI18N
        getContentPane().add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 40, -1));

        jLabel48.setFont(resourceMap.getFont("jLabel48.font")); // NOI18N
        jLabel48.setText(resourceMap.getString("jLabel48.text")); // NOI18N
        jLabel48.setName("jLabel48"); // NOI18N
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 310, -1, 20));

        _txtHour_7.setFont(resourceMap.getFont("_txtHour_7.font")); // NOI18N
        _txtHour_7.setName("_txtHour_7"); // NOI18N
        getContentPane().add(_txtHour_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, -1));

        _txtMinute_7.setFont(resourceMap.getFont("_txtMinute_7.font")); // NOI18N
        _txtMinute_7.setName("_txtMinute_7"); // NOI18N
        getContentPane().add(_txtMinute_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 40, -1));

        jLabel49.setFont(resourceMap.getFont("jLabel49.font")); // NOI18N
        jLabel49.setText(resourceMap.getString("jLabel49.text")); // NOI18N
        jLabel49.setName("jLabel49"); // NOI18N
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, 20));

        jTextField32.setFont(resourceMap.getFont("jTextField32.font")); // NOI18N
        jTextField32.setName("jTextField32"); // NOI18N
        getContentPane().add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 40, -1));

        jTextField33.setFont(resourceMap.getFont("jTextField33.font")); // NOI18N
        jTextField33.setName("jTextField33"); // NOI18N
        getContentPane().add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 40, -1));

        jLabel50.setFont(resourceMap.getFont("jLabel50.font")); // NOI18N
        jLabel50.setText(resourceMap.getString("jLabel50.text")); // NOI18N
        jLabel50.setName("jLabel50"); // NOI18N
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 340, -1, 20));

        _txtHour_8.setFont(resourceMap.getFont("_txtHour_8.font")); // NOI18N
        _txtHour_8.setName("_txtHour_8"); // NOI18N
        getContentPane().add(_txtHour_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 40, -1));

        _txtMinute_8.setFont(resourceMap.getFont("_txtMinute_8.font")); // NOI18N
        _txtMinute_8.setName("_txtMinute_8"); // NOI18N
        getContentPane().add(_txtMinute_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 40, -1));

        jLabel51.setFont(resourceMap.getFont("jLabel51.font")); // NOI18N
        jLabel51.setText(resourceMap.getString("jLabel51.text")); // NOI18N
        jLabel51.setName("jLabel51"); // NOI18N
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, 20));

        jTextField36.setFont(resourceMap.getFont("jTextField36.font")); // NOI18N
        jTextField36.setName("jTextField36"); // NOI18N
        getContentPane().add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 40, -1));

        jTextField37.setFont(resourceMap.getFont("jTextField37.font")); // NOI18N
        jTextField37.setName("jTextField37"); // NOI18N
        getContentPane().add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 40, -1));

        jLabel52.setFont(resourceMap.getFont("jLabel52.font")); // NOI18N
        jLabel52.setText(resourceMap.getString("jLabel52.text")); // NOI18N
        jLabel52.setName("jLabel52"); // NOI18N
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 370, -1, 20));

        _txtHour_9.setFont(resourceMap.getFont("_txtHour_9.font")); // NOI18N
        _txtHour_9.setName("_txtHour_9"); // NOI18N
        getContentPane().add(_txtHour_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 40, -1));

        _txtMinute_9.setFont(resourceMap.getFont("_txtMinute_9.font")); // NOI18N
        _txtMinute_9.setName("_txtMinute_9"); // NOI18N
        getContentPane().add(_txtMinute_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 40, -1));

        jLabel53.setFont(resourceMap.getFont("jLabel53.font")); // NOI18N
        jLabel53.setText(resourceMap.getString("jLabel53.text")); // NOI18N
        jLabel53.setName("jLabel53"); // NOI18N
        getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, 20));

        jTextField40.setFont(resourceMap.getFont("jTextField40.font")); // NOI18N
        jTextField40.setName("jTextField40"); // NOI18N
        getContentPane().add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 40, -1));

        jTextField41.setFont(resourceMap.getFont("jTextField41.font")); // NOI18N
        jTextField41.setName("jTextField41"); // NOI18N
        getContentPane().add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 40, -1));

        jLabel54.setFont(resourceMap.getFont("jLabel54.font")); // NOI18N
        jLabel54.setText(resourceMap.getString("jLabel54.text")); // NOI18N
        jLabel54.setName("jLabel54"); // NOI18N
        getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 400, -1, 20));

        _txtHour_10.setFont(resourceMap.getFont("_txtHour_10.font")); // NOI18N
        _txtHour_10.setName("_txtHour_10"); // NOI18N
        getContentPane().add(_txtHour_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 40, -1));

        _txtMinute_10.setFont(resourceMap.getFont("_txtMinute_10.font")); // NOI18N
        _txtMinute_10.setName("_txtMinute_10"); // NOI18N
        getContentPane().add(_txtMinute_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 40, -1));

        jLabel55.setFont(resourceMap.getFont("jLabel55.font")); // NOI18N
        jLabel55.setText(resourceMap.getString("jLabel55.text")); // NOI18N
        jLabel55.setName("jLabel55"); // NOI18N
        getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, -1, 20));

        jTextField44.setFont(resourceMap.getFont("jTextField44.font")); // NOI18N
        jTextField44.setName("jTextField44"); // NOI18N
        getContentPane().add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 40, -1));

        jTextField45.setFont(resourceMap.getFont("jTextField45.font")); // NOI18N
        jTextField45.setName("jTextField45"); // NOI18N
        getContentPane().add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 40, -1));

        jLabel56.setFont(resourceMap.getFont("jLabel56.font")); // NOI18N
        jLabel56.setText(resourceMap.getString("jLabel56.text")); // NOI18N
        jLabel56.setName("jLabel56"); // NOI18N
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 430, -1, 20));

        _txtHour_11.setFont(resourceMap.getFont("_txtHour_11.font")); // NOI18N
        _txtHour_11.setName("_txtHour_11"); // NOI18N
        getContentPane().add(_txtHour_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 40, -1));

        _txtMinute_11.setFont(resourceMap.getFont("_txtMinute_11.font")); // NOI18N
        _txtMinute_11.setName("_txtMinute_11"); // NOI18N
        getContentPane().add(_txtMinute_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 40, -1));

        jLabel57.setFont(resourceMap.getFont("jLabel57.font")); // NOI18N
        jLabel57.setText(resourceMap.getString("jLabel57.text")); // NOI18N
        jLabel57.setName("jLabel57"); // NOI18N
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, 20));

        jTextField48.setFont(resourceMap.getFont("jTextField48.font")); // NOI18N
        jTextField48.setName("jTextField48"); // NOI18N
        getContentPane().add(jTextField48, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 40, -1));

        jTextField49.setFont(resourceMap.getFont("jTextField49.font")); // NOI18N
        jTextField49.setName("jTextField49"); // NOI18N
        getContentPane().add(jTextField49, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 40, -1));

        jCheckBox3.setName("jCheckBox3"); // NOI18N
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        _chkUseFlag_1.setName("_chkUseFlag_1"); // NOI18N
        getContentPane().add(_chkUseFlag_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        _chkUseFlag_5.setName("_chkUseFlag_5"); // NOI18N
        getContentPane().add(_chkUseFlag_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        _chkUseFlag_3.setName("_chkUseFlag_3"); // NOI18N
        getContentPane().add(_chkUseFlag_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jCheckBox7.setName("jCheckBox7"); // NOI18N
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        _chkUseFlag_4.setName("_chkUseFlag_4"); // NOI18N
        getContentPane().add(_chkUseFlag_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        _chkUseFlag_8.setName("_chkUseFlag_8"); // NOI18N
        getContentPane().add(_chkUseFlag_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, -1, -1));

        _chkUseFlag_6.setName("_chkUseFlag_6"); // NOI18N
        getContentPane().add(_chkUseFlag_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        jCheckBox11.setName("jCheckBox11"); // NOI18N
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        _chkUseFlag_7.setName("_chkUseFlag_7"); // NOI18N
        getContentPane().add(_chkUseFlag_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        _chkUseFlag_11.setName("_chkUseFlag_11"); // NOI18N
        getContentPane().add(_chkUseFlag_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        _chkUseFlag_9.setName("_chkUseFlag_9"); // NOI18N
        getContentPane().add(_chkUseFlag_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jCheckBox15.setName("jCheckBox15"); // NOI18N
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        _chkUseFlag_10.setName("_chkUseFlag_10"); // NOI18N
        getContentPane().add(_chkUseFlag_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, -1));

        jLabel47.setFont(resourceMap.getFont("jLabel47.font")); // NOI18N
        jLabel47.setText(resourceMap.getString("jLabel47.text")); // NOI18N
        jLabel47.setName("jLabel47"); // NOI18N
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 100, -1, 20));

        _txtHour_12.setFont(resourceMap.getFont("_txtHour_12.font")); // NOI18N
        _txtHour_12.setName("_txtHour_12"); // NOI18N
        getContentPane().add(_txtHour_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 40, -1));

        _txtMinute_12.setFont(resourceMap.getFont("_txtMinute_12.font")); // NOI18N
        _txtMinute_12.setName("_txtMinute_12"); // NOI18N
        getContentPane().add(_txtMinute_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, -1));

        _chkUseFlag_14.setName("_chkUseFlag_14"); // NOI18N
        getContentPane().add(_chkUseFlag_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel58.setFont(resourceMap.getFont("jLabel58.font")); // NOI18N
        jLabel58.setText(resourceMap.getString("jLabel58.text")); // NOI18N
        jLabel58.setName("jLabel58"); // NOI18N
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, 20));

        jTextField52.setFont(resourceMap.getFont("jTextField52.font")); // NOI18N
        jTextField52.setName("jTextField52"); // NOI18N
        getContentPane().add(jTextField52, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 40, -1));

        jTextField53.setFont(resourceMap.getFont("jTextField53.font")); // NOI18N
        jTextField53.setName("jTextField53"); // NOI18N
        getContentPane().add(jTextField53, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, -1));

        _chkUseFlag_12.setName("_chkUseFlag_12"); // NOI18N
        getContentPane().add(_chkUseFlag_12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel59.setFont(resourceMap.getFont("jLabel59.font")); // NOI18N
        jLabel59.setText(resourceMap.getString("jLabel59.text")); // NOI18N
        jLabel59.setName("jLabel59"); // NOI18N
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 130, -1, 20));

        _txtHour_13.setFont(resourceMap.getFont("_txtHour_13.font")); // NOI18N
        _txtHour_13.setName("_txtHour_13"); // NOI18N
        getContentPane().add(_txtHour_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 40, -1));

        _txtMinute_13.setFont(resourceMap.getFont("_txtMinute_13.font")); // NOI18N
        _txtMinute_13.setName("_txtMinute_13"); // NOI18N
        getContentPane().add(_txtMinute_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 40, -1));

        jLabel60.setFont(resourceMap.getFont("jLabel60.font")); // NOI18N
        jLabel60.setText(resourceMap.getString("jLabel60.text")); // NOI18N
        jLabel60.setName("jLabel60"); // NOI18N
        getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, 20));

        jTextField56.setFont(resourceMap.getFont("jTextField56.font")); // NOI18N
        jTextField56.setName("jTextField56"); // NOI18N
        getContentPane().add(jTextField56, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 40, -1));

        jTextField57.setFont(resourceMap.getFont("jTextField57.font")); // NOI18N
        jTextField57.setName("jTextField57"); // NOI18N
        getContentPane().add(jTextField57, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 40, -1));

        jLabel61.setFont(resourceMap.getFont("jLabel61.font")); // NOI18N
        jLabel61.setText(resourceMap.getString("jLabel61.text")); // NOI18N
        jLabel61.setName("jLabel61"); // NOI18N
        getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 160, -1, 20));

        _txtHour_14.setFont(resourceMap.getFont("_txtHour_14.font")); // NOI18N
        _txtHour_14.setName("_txtHour_14"); // NOI18N
        getContentPane().add(_txtHour_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 40, -1));

        _txtMinute_14.setFont(resourceMap.getFont("_txtMinute_14.font")); // NOI18N
        _txtMinute_14.setName("_txtMinute_14"); // NOI18N
        getContentPane().add(_txtMinute_14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 40, -1));

        jLabel62.setFont(resourceMap.getFont("jLabel62.font")); // NOI18N
        jLabel62.setText(resourceMap.getString("jLabel62.text")); // NOI18N
        jLabel62.setName("jLabel62"); // NOI18N
        getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 20));

        jTextField60.setFont(resourceMap.getFont("jTextField60.font")); // NOI18N
        jTextField60.setName("jTextField60"); // NOI18N
        getContentPane().add(jTextField60, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 40, -1));

        jTextField61.setFont(resourceMap.getFont("jTextField61.font")); // NOI18N
        jTextField61.setName("jTextField61"); // NOI18N
        getContentPane().add(jTextField61, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 40, -1));

        jLabel63.setFont(resourceMap.getFont("jLabel63.font")); // NOI18N
        jLabel63.setText(resourceMap.getString("jLabel63.text")); // NOI18N
        jLabel63.setName("jLabel63"); // NOI18N
        getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 190, -1, 20));

        _txtHour_15.setFont(resourceMap.getFont("_txtHour_15.font")); // NOI18N
        _txtHour_15.setName("_txtHour_15"); // NOI18N
        getContentPane().add(_txtHour_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 40, -1));

        _txtMinute_15.setFont(resourceMap.getFont("_txtMinute_15.font")); // NOI18N
        _txtMinute_15.setName("_txtMinute_15"); // NOI18N
        getContentPane().add(_txtMinute_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 40, -1));

        jLabel64.setFont(resourceMap.getFont("jLabel64.font")); // NOI18N
        jLabel64.setText(resourceMap.getString("jLabel64.text")); // NOI18N
        jLabel64.setName("jLabel64"); // NOI18N
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 20));

        jTextField64.setFont(resourceMap.getFont("jTextField64.font")); // NOI18N
        jTextField64.setName("jTextField64"); // NOI18N
        getContentPane().add(jTextField64, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 40, -1));

        jTextField65.setFont(resourceMap.getFont("jTextField65.font")); // NOI18N
        jTextField65.setName("jTextField65"); // NOI18N
        getContentPane().add(jTextField65, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 40, -1));

        jLabel65.setFont(resourceMap.getFont("jLabel65.font")); // NOI18N
        jLabel65.setText(resourceMap.getString("jLabel65.text")); // NOI18N
        jLabel65.setName("jLabel65"); // NOI18N
        getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 220, -1, 20));

        _txtHour_16.setFont(resourceMap.getFont("_txtHour_16.font")); // NOI18N
        _txtHour_16.setName("_txtHour_16"); // NOI18N
        getContentPane().add(_txtHour_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 40, -1));

        _txtMinute_16.setFont(resourceMap.getFont("_txtMinute_16.font")); // NOI18N
        _txtMinute_16.setName("_txtMinute_16"); // NOI18N
        getContentPane().add(_txtMinute_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 40, -1));

        jLabel66.setFont(resourceMap.getFont("jLabel66.font")); // NOI18N
        jLabel66.setText(resourceMap.getString("jLabel66.text")); // NOI18N
        jLabel66.setName("jLabel66"); // NOI18N
        getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 20));

        jTextField68.setFont(resourceMap.getFont("jTextField68.font")); // NOI18N
        jTextField68.setName("jTextField68"); // NOI18N
        getContentPane().add(jTextField68, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 40, -1));

        jTextField69.setFont(resourceMap.getFont("jTextField69.font")); // NOI18N
        jTextField69.setName("jTextField69"); // NOI18N
        getContentPane().add(jTextField69, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 40, -1));

        jLabel67.setFont(resourceMap.getFont("jLabel67.font")); // NOI18N
        jLabel67.setText(resourceMap.getString("jLabel67.text")); // NOI18N
        jLabel67.setName("jLabel67"); // NOI18N
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 250, -1, 20));

        _txtHour_17.setFont(resourceMap.getFont("_txtHour_17.font")); // NOI18N
        _txtHour_17.setName("_txtHour_17"); // NOI18N
        getContentPane().add(_txtHour_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 40, -1));

        _txtMinute_17.setFont(resourceMap.getFont("_txtMinute_17.font")); // NOI18N
        _txtMinute_17.setName("_txtMinute_17"); // NOI18N
        getContentPane().add(_txtMinute_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 40, -1));

        jLabel68.setFont(resourceMap.getFont("jLabel68.font")); // NOI18N
        jLabel68.setText(resourceMap.getString("jLabel68.text")); // NOI18N
        jLabel68.setName("jLabel68"); // NOI18N
        getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, -1, 20));

        jTextField72.setFont(resourceMap.getFont("jTextField72.font")); // NOI18N
        jTextField72.setName("jTextField72"); // NOI18N
        getContentPane().add(jTextField72, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 40, -1));

        jTextField73.setFont(resourceMap.getFont("jTextField73.font")); // NOI18N
        jTextField73.setName("jTextField73"); // NOI18N
        getContentPane().add(jTextField73, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 40, -1));

        jLabel69.setFont(resourceMap.getFont("jLabel69.font")); // NOI18N
        jLabel69.setText(resourceMap.getString("jLabel69.text")); // NOI18N
        jLabel69.setName("jLabel69"); // NOI18N
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 280, -1, 20));

        _txtHour_18.setFont(resourceMap.getFont("_txtHour_18.font")); // NOI18N
        _txtHour_18.setName("_txtHour_18"); // NOI18N
        getContentPane().add(_txtHour_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 40, -1));

        _txtMinute_18.setFont(resourceMap.getFont("_txtMinute_18.font")); // NOI18N
        _txtMinute_18.setName("_txtMinute_18"); // NOI18N
        getContentPane().add(_txtMinute_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 40, -1));

        jTextField76.setFont(resourceMap.getFont("jTextField76.font")); // NOI18N
        jTextField76.setName("jTextField76"); // NOI18N
        getContentPane().add(jTextField76, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 40, -1));

        jTextField77.setFont(resourceMap.getFont("jTextField77.font")); // NOI18N
        jTextField77.setName("jTextField77"); // NOI18N
        getContentPane().add(jTextField77, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 40, -1));

        jLabel70.setFont(resourceMap.getFont("jLabel70.font")); // NOI18N
        jLabel70.setText(resourceMap.getString("jLabel70.text")); // NOI18N
        jLabel70.setName("jLabel70"); // NOI18N
        getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 310, -1, 20));

        _txtHour_19.setFont(resourceMap.getFont("_txtHour_19.font")); // NOI18N
        _txtHour_19.setName("_txtHour_19"); // NOI18N
        getContentPane().add(_txtHour_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 40, -1));

        _txtMinute_19.setFont(resourceMap.getFont("_txtMinute_19.font")); // NOI18N
        _txtMinute_19.setName("_txtMinute_19"); // NOI18N
        getContentPane().add(_txtMinute_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 40, -1));

        jLabel71.setFont(resourceMap.getFont("jLabel71.font")); // NOI18N
        jLabel71.setText(resourceMap.getString("jLabel71.text")); // NOI18N
        jLabel71.setName("jLabel71"); // NOI18N
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, -1, 20));

        jTextField80.setFont(resourceMap.getFont("jTextField80.font")); // NOI18N
        jTextField80.setName("jTextField80"); // NOI18N
        getContentPane().add(jTextField80, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 40, -1));

        jTextField81.setFont(resourceMap.getFont("jTextField81.font")); // NOI18N
        jTextField81.setName("jTextField81"); // NOI18N
        getContentPane().add(jTextField81, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 40, -1));

        jLabel72.setFont(resourceMap.getFont("jLabel72.font")); // NOI18N
        jLabel72.setText(resourceMap.getString("jLabel72.text")); // NOI18N
        jLabel72.setName("jLabel72"); // NOI18N
        getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 340, -1, 20));

        _txtHour_20.setFont(resourceMap.getFont("_txtHour_20.font")); // NOI18N
        _txtHour_20.setName("_txtHour_20"); // NOI18N
        getContentPane().add(_txtHour_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 40, -1));

        _txtMinute_20.setFont(resourceMap.getFont("_txtMinute_20.font")); // NOI18N
        _txtMinute_20.setName("_txtMinute_20"); // NOI18N
        getContentPane().add(_txtMinute_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 40, -1));

        jLabel73.setFont(resourceMap.getFont("jLabel73.font")); // NOI18N
        jLabel73.setText(resourceMap.getString("jLabel73.text")); // NOI18N
        jLabel73.setName("jLabel73"); // NOI18N
        getContentPane().add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, -1, 20));

        jTextField84.setFont(resourceMap.getFont("jTextField84.font")); // NOI18N
        jTextField84.setName("jTextField84"); // NOI18N
        getContentPane().add(jTextField84, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 40, -1));

        jTextField85.setFont(resourceMap.getFont("jTextField85.font")); // NOI18N
        jTextField85.setName("jTextField85"); // NOI18N
        getContentPane().add(jTextField85, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 40, -1));

        jLabel74.setFont(resourceMap.getFont("jLabel74.font")); // NOI18N
        jLabel74.setText(resourceMap.getString("jLabel74.text")); // NOI18N
        jLabel74.setName("jLabel74"); // NOI18N
        getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 370, -1, 20));

        _txtHour_21.setFont(resourceMap.getFont("_txtHour_21.font")); // NOI18N
        _txtHour_21.setName("_txtHour_21"); // NOI18N
        getContentPane().add(_txtHour_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 40, -1));

        _txtMinute_21.setFont(resourceMap.getFont("_txtMinute_21.font")); // NOI18N
        _txtMinute_21.setName("_txtMinute_21"); // NOI18N
        getContentPane().add(_txtMinute_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 40, -1));

        jLabel75.setFont(resourceMap.getFont("jLabel75.font")); // NOI18N
        jLabel75.setText(resourceMap.getString("jLabel75.text")); // NOI18N
        jLabel75.setName("jLabel75"); // NOI18N
        getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, -1, 20));

        jTextField88.setFont(resourceMap.getFont("jTextField88.font")); // NOI18N
        jTextField88.setName("jTextField88"); // NOI18N
        getContentPane().add(jTextField88, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 40, -1));

        jTextField89.setFont(resourceMap.getFont("jTextField89.font")); // NOI18N
        jTextField89.setName("jTextField89"); // NOI18N
        getContentPane().add(jTextField89, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 40, -1));

        jLabel76.setFont(resourceMap.getFont("jLabel76.font")); // NOI18N
        jLabel76.setText(resourceMap.getString("jLabel76.text")); // NOI18N
        jLabel76.setName("jLabel76"); // NOI18N
        getContentPane().add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 400, -1, 20));

        _txtHour_22.setFont(resourceMap.getFont("_txtHour_22.font")); // NOI18N
        _txtHour_22.setName("_txtHour_22"); // NOI18N
        getContentPane().add(_txtHour_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 40, -1));

        _txtMinute_22.setFont(resourceMap.getFont("_txtMinute_22.font")); // NOI18N
        _txtMinute_22.setName("_txtMinute_22"); // NOI18N
        getContentPane().add(_txtMinute_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 40, -1));

        jLabel77.setFont(resourceMap.getFont("jLabel77.font")); // NOI18N
        jLabel77.setText(resourceMap.getString("jLabel77.text")); // NOI18N
        jLabel77.setName("jLabel77"); // NOI18N
        getContentPane().add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, -1, 20));

        jTextField92.setFont(resourceMap.getFont("jTextField92.font")); // NOI18N
        jTextField92.setName("jTextField92"); // NOI18N
        getContentPane().add(jTextField92, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 40, -1));

        jTextField93.setFont(resourceMap.getFont("jTextField93.font")); // NOI18N
        jTextField93.setName("jTextField93"); // NOI18N
        getContentPane().add(jTextField93, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 40, -1));

        jLabel78.setFont(resourceMap.getFont("jLabel78.font")); // NOI18N
        jLabel78.setText(resourceMap.getString("jLabel78.text")); // NOI18N
        jLabel78.setName("jLabel78"); // NOI18N
        getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 430, -1, 20));

        _txtHour_23.setFont(resourceMap.getFont("_txtHour_23.font")); // NOI18N
        _txtHour_23.setName("_txtHour_23"); // NOI18N
        getContentPane().add(_txtHour_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 40, -1));

        _txtMinute_23.setFont(resourceMap.getFont("_txtMinute_23.font")); // NOI18N
        _txtMinute_23.setName("_txtMinute_23"); // NOI18N
        getContentPane().add(_txtMinute_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 40, -1));

        jLabel79.setFont(resourceMap.getFont("jLabel79.font")); // NOI18N
        jLabel79.setText(resourceMap.getString("jLabel79.text")); // NOI18N
        jLabel79.setName("jLabel79"); // NOI18N
        getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, -1, 20));

        jTextField96.setFont(resourceMap.getFont("jTextField96.font")); // NOI18N
        jTextField96.setName("jTextField96"); // NOI18N
        getContentPane().add(jTextField96, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 40, -1));

        jTextField97.setFont(resourceMap.getFont("jTextField97.font")); // NOI18N
        jTextField97.setName("jTextField97"); // NOI18N
        getContentPane().add(jTextField97, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 40, -1));

        jCheckBox19.setName("jCheckBox19"); // NOI18N
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        _chkUseFlag_13.setName("_chkUseFlag_13"); // NOI18N
        getContentPane().add(_chkUseFlag_13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        _chkUseFlag_17.setName("_chkUseFlag_17"); // NOI18N
        getContentPane().add(_chkUseFlag_17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        _chkUseFlag_15.setName("_chkUseFlag_15"); // NOI18N
        getContentPane().add(_chkUseFlag_15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        jCheckBox23.setName("jCheckBox23"); // NOI18N
        getContentPane().add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, -1, -1));

        _chkUseFlag_16.setName("_chkUseFlag_16"); // NOI18N
        getContentPane().add(_chkUseFlag_16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        _chkUseFlag_20.setName("_chkUseFlag_20"); // NOI18N
        getContentPane().add(_chkUseFlag_20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        _chkUseFlag_18.setName("_chkUseFlag_18"); // NOI18N
        getContentPane().add(_chkUseFlag_18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        jCheckBox27.setName("jCheckBox27"); // NOI18N
        getContentPane().add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        _chkUseFlag_19.setName("_chkUseFlag_19"); // NOI18N
        getContentPane().add(_chkUseFlag_19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        _chkUseFlag_23.setName("_chkUseFlag_23"); // NOI18N
        getContentPane().add(_chkUseFlag_23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        _chkUseFlag_21.setName("_chkUseFlag_21"); // NOI18N
        getContentPane().add(_chkUseFlag_21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jCheckBox31.setName("jCheckBox31"); // NOI18N
        getContentPane().add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        _chkUseFlag_22.setName("_chkUseFlag_22"); // NOI18N
        getContentPane().add(_chkUseFlag_22, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 120, 30));

        btnRead.setFont(resourceMap.getFont("btnRead.font")); // NOI18N
        btnRead.setText(resourceMap.getString("btnRead.text")); // NOI18N
        btnRead.setName("btnRead"); // NOI18N
        btnRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadMouseClicked(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 120, 30));

        btnWrite.setFont(resourceMap.getFont("btnWrite.font")); // NOI18N
        btnWrite.setText(resourceMap.getString("btnWrite.text")); // NOI18N
        btnWrite.setName("btnWrite"); // NOI18N
        btnWrite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWriteMouseClicked(evt);
            }
        });
        getContentPane().add(btnWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 120, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-658)/2, (screenSize.height-560)/2, 658, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        dbBellSetting = SBXPCProxy.GetBellTime(SysUtil.MachineNumber, MAX_BELLCOUNT_DAY);
        
        if(dbBellSetting.isSuccess())
        {
            errorCode = 0;
            ShowBellSetting();
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadMouseClicked

    private void btnWriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        UIValue2Local();
        ret = SBXPCProxy.SetBellTime(SysUtil.MachineNumber, dbBellSetting.bellCount, dbBellSetting.bellInfoList);
        
        if(ret)
        {
            errorCode = 0;
            ShowBellSetting();
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
        
    }//GEN-LAST:event_btnWriteMouseClicked

    private void ShowBellSetting()
    {
        if(dbBellSetting == null)
            return;
        txtBellCount.setText(String.valueOf(dbBellSetting.bellCount));
        if(dbBellSetting.bellInfoList == null)
            return;
        for(int i = 0; i < MAX_BELLCOUNT_DAY; i ++)
        {
            chkUseFlag[i].setSelected(dbBellSetting.bellInfoList[i] == 1);
            txtHour[i].setText(String.valueOf(dbBellSetting.bellInfoList[i + MAX_BELLCOUNT_DAY]));
            txtMinute[i].setText(String.valueOf(dbBellSetting.bellInfoList[i + MAX_BELLCOUNT_DAY * 2]));
        }
    }
    
    private void UIValue2Local()
    {
        if(dbBellSetting == null)
            dbBellSetting = new GetBellTimeOutput();
        if(dbBellSetting.bellInfoList == null)
            dbBellSetting.bellInfoList = new byte[MAX_BELLCOUNT_DAY * 3];
        for(int i = 0; i < MAX_BELLCOUNT_DAY; i ++)
        {
            if(chkUseFlag[i].isSelected())
                dbBellSetting.bellInfoList[i] = 1;
            else
                dbBellSetting.bellInfoList[i] = 0;
            try{ dbBellSetting.bellInfoList[i + MAX_BELLCOUNT_DAY] = Byte.parseByte(txtHour[i].getText()); } catch(Exception e){}
            try{ dbBellSetting.bellInfoList[i + MAX_BELLCOUNT_DAY * 2] = Byte.parseByte(txtMinute[i].getText()); } catch(Exception e){}
        }
        try{ dbBellSetting.bellCount = Long.parseLong(txtBellCount.getText()); } catch(Exception e){}
    }
    
    private void initFrame()
    {
        txtHour = new JTextField[MAX_BELLCOUNT_DAY];
        txtMinute = new JTextField[MAX_BELLCOUNT_DAY];
        chkUseFlag = new JCheckBox[MAX_BELLCOUNT_DAY];
        
        txtHour[0] = _txtHour_0;
        txtHour[1] = _txtHour_1;
        txtHour[2] = _txtHour_2;
        txtHour[3] = _txtHour_3;
        txtHour[4] = _txtHour_4;
        txtHour[5] = _txtHour_5;
        txtHour[6] = _txtHour_6;
        txtHour[7] = _txtHour_7;
        txtHour[8] = _txtHour_8;
        txtHour[9] = _txtHour_9;
        txtHour[10] = _txtHour_10;
        txtHour[11] = _txtHour_11;
        txtHour[12] = _txtHour_12;
        txtHour[13] = _txtHour_13;
        txtHour[14] = _txtHour_14;
        txtHour[15] = _txtHour_15;
        txtHour[16] = _txtHour_16;
        txtHour[17] = _txtHour_17;
        txtHour[18] = _txtHour_18;
        txtHour[19] = _txtHour_19;
        txtHour[20] = _txtHour_20;
        txtHour[21] = _txtHour_21;
        txtHour[22] = _txtHour_22;
        txtHour[23] = _txtHour_23;

        txtMinute[0] = _txtMinute_0;
        txtMinute[1] = _txtMinute_1;
        txtMinute[2] = _txtMinute_2;
        txtMinute[3] = _txtMinute_3;
        txtMinute[4] = _txtMinute_4;
        txtMinute[5] = _txtMinute_5;
        txtMinute[6] = _txtMinute_6;
        txtMinute[7] = _txtMinute_7;
        txtMinute[8] = _txtMinute_8;
        txtMinute[9] = _txtMinute_9;
        txtMinute[10] = _txtMinute_10;
        txtMinute[11] = _txtMinute_11;
        txtMinute[12] = _txtMinute_12;
        txtMinute[13] = _txtMinute_13;
        txtMinute[14] = _txtMinute_14;
        txtMinute[15] = _txtMinute_15;
        txtMinute[16] = _txtMinute_16;
        txtMinute[17] = _txtMinute_17;
        txtMinute[18] = _txtMinute_18;
        txtMinute[19] = _txtMinute_19;
        txtMinute[20] = _txtMinute_20;
        txtMinute[21] = _txtMinute_21;
        txtMinute[22] = _txtMinute_22;
        txtMinute[23] = _txtMinute_23;
        
        chkUseFlag[0] = _chkUseFlag_0;
        chkUseFlag[1] = _chkUseFlag_1;
        chkUseFlag[2] = _chkUseFlag_2;
        chkUseFlag[3] = _chkUseFlag_3;
        chkUseFlag[4] = _chkUseFlag_4;
        chkUseFlag[5] = _chkUseFlag_5;
        chkUseFlag[6] = _chkUseFlag_6;
        chkUseFlag[7] = _chkUseFlag_7;
        chkUseFlag[8] = _chkUseFlag_8;
        chkUseFlag[9] = _chkUseFlag_9;
        chkUseFlag[10] = _chkUseFlag_10;
        chkUseFlag[11] = _chkUseFlag_11;
        chkUseFlag[12] = _chkUseFlag_12;
        chkUseFlag[13] = _chkUseFlag_13;
        chkUseFlag[14] = _chkUseFlag_14;
        chkUseFlag[15] = _chkUseFlag_15;
        chkUseFlag[16] = _chkUseFlag_16;
        chkUseFlag[17] = _chkUseFlag_17;
        chkUseFlag[18] = _chkUseFlag_18;
        chkUseFlag[19] = _chkUseFlag_19;
        chkUseFlag[20] = _chkUseFlag_20;
        chkUseFlag[21] = _chkUseFlag_21;
        chkUseFlag[22] = _chkUseFlag_22;
        chkUseFlag[23] = _chkUseFlag_23;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox _chkUseFlag_0;
    private javax.swing.JCheckBox _chkUseFlag_1;
    private javax.swing.JCheckBox _chkUseFlag_10;
    private javax.swing.JCheckBox _chkUseFlag_11;
    private javax.swing.JCheckBox _chkUseFlag_12;
    private javax.swing.JCheckBox _chkUseFlag_13;
    private javax.swing.JCheckBox _chkUseFlag_14;
    private javax.swing.JCheckBox _chkUseFlag_15;
    private javax.swing.JCheckBox _chkUseFlag_16;
    private javax.swing.JCheckBox _chkUseFlag_17;
    private javax.swing.JCheckBox _chkUseFlag_18;
    private javax.swing.JCheckBox _chkUseFlag_19;
    private javax.swing.JCheckBox _chkUseFlag_2;
    private javax.swing.JCheckBox _chkUseFlag_20;
    private javax.swing.JCheckBox _chkUseFlag_21;
    private javax.swing.JCheckBox _chkUseFlag_22;
    private javax.swing.JCheckBox _chkUseFlag_23;
    private javax.swing.JCheckBox _chkUseFlag_3;
    private javax.swing.JCheckBox _chkUseFlag_4;
    private javax.swing.JCheckBox _chkUseFlag_5;
    private javax.swing.JCheckBox _chkUseFlag_6;
    private javax.swing.JCheckBox _chkUseFlag_7;
    private javax.swing.JCheckBox _chkUseFlag_8;
    private javax.swing.JCheckBox _chkUseFlag_9;
    private javax.swing.JTextField _txtHour_0;
    private javax.swing.JTextField _txtHour_1;
    private javax.swing.JTextField _txtHour_10;
    private javax.swing.JTextField _txtHour_11;
    private javax.swing.JTextField _txtHour_12;
    private javax.swing.JTextField _txtHour_13;
    private javax.swing.JTextField _txtHour_14;
    private javax.swing.JTextField _txtHour_15;
    private javax.swing.JTextField _txtHour_16;
    private javax.swing.JTextField _txtHour_17;
    private javax.swing.JTextField _txtHour_18;
    private javax.swing.JTextField _txtHour_19;
    private javax.swing.JTextField _txtHour_2;
    private javax.swing.JTextField _txtHour_20;
    private javax.swing.JTextField _txtHour_21;
    private javax.swing.JTextField _txtHour_22;
    private javax.swing.JTextField _txtHour_23;
    private javax.swing.JTextField _txtHour_3;
    private javax.swing.JTextField _txtHour_4;
    private javax.swing.JTextField _txtHour_5;
    private javax.swing.JTextField _txtHour_6;
    private javax.swing.JTextField _txtHour_7;
    private javax.swing.JTextField _txtHour_8;
    private javax.swing.JTextField _txtHour_9;
    private javax.swing.JTextField _txtMinute_0;
    private javax.swing.JTextField _txtMinute_1;
    private javax.swing.JTextField _txtMinute_10;
    private javax.swing.JTextField _txtMinute_11;
    private javax.swing.JTextField _txtMinute_12;
    private javax.swing.JTextField _txtMinute_13;
    private javax.swing.JTextField _txtMinute_14;
    private javax.swing.JTextField _txtMinute_15;
    private javax.swing.JTextField _txtMinute_16;
    private javax.swing.JTextField _txtMinute_17;
    private javax.swing.JTextField _txtMinute_18;
    private javax.swing.JTextField _txtMinute_19;
    private javax.swing.JTextField _txtMinute_2;
    private javax.swing.JTextField _txtMinute_20;
    private javax.swing.JTextField _txtMinute_21;
    private javax.swing.JTextField _txtMinute_22;
    private javax.swing.JTextField _txtMinute_23;
    private javax.swing.JTextField _txtMinute_3;
    private javax.swing.JTextField _txtMinute_4;
    private javax.swing.JTextField _txtMinute_5;
    private javax.swing.JTextField _txtMinute_6;
    private javax.swing.JTextField _txtMinute_7;
    private javax.swing.JTextField _txtMinute_8;
    private javax.swing.JTextField _txtMinute_9;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnWrite;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField48;
    private javax.swing.JTextField jTextField49;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField52;
    private javax.swing.JTextField jTextField53;
    private javax.swing.JTextField jTextField56;
    private javax.swing.JTextField jTextField57;
    private javax.swing.JTextField jTextField60;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextField64;
    private javax.swing.JTextField jTextField65;
    private javax.swing.JTextField jTextField68;
    private javax.swing.JTextField jTextField69;
    private javax.swing.JTextField jTextField72;
    private javax.swing.JTextField jTextField73;
    private javax.swing.JTextField jTextField76;
    private javax.swing.JTextField jTextField77;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField80;
    private javax.swing.JTextField jTextField81;
    private javax.swing.JTextField jTextField84;
    private javax.swing.JTextField jTextField85;
    private javax.swing.JTextField jTextField88;
    private javax.swing.JTextField jTextField89;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextField92;
    private javax.swing.JTextField jTextField93;
    private javax.swing.JTextField jTextField96;
    private javax.swing.JTextField jTextField97;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtBellCount;
    // End of variables declaration//GEN-END:variables
}
