/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DepartmentFrame.java
 *
 * Created on Aug 26, 2011, 6:32:37 PM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.AbstractListModel;
import smack.comm.SBXPCProxy;
import smack.comm.output.OneStringOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class DepartmentFrame extends javax.swing.JFrame {

    DepartmentListModel listModel = new DepartmentListModel();
    
    /** Creates new form DepartmentFrame */
    public DepartmentFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDepartment = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDepartment = new javax.swing.JList();
        btnExit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnWrite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(DepartmentFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 553, 31));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        txtDepartment.setFont(resourceMap.getFont("txtDepartment.font")); // NOI18N
        txtDepartment.setName("txtDepartment"); // NOI18N
        getContentPane().add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 250, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstDepartment.setModel(listModel);
        lstDepartment.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDepartment.setName("lstDepartment"); // NOI18N
        lstDepartment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDepartmentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstDepartment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 450, 370));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 90, 40));

        btnUpdate.setFont(resourceMap.getFont("btnUpdate.font")); // NOI18N
        btnUpdate.setText(resourceMap.getString("btnUpdate.text")); // NOI18N
        btnUpdate.setName("btnUpdate"); // NOI18N
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 90, 40));

        btnRead.setFont(resourceMap.getFont("btnRead.font")); // NOI18N
        btnRead.setText(resourceMap.getString("btnRead.text")); // NOI18N
        btnRead.setName("btnRead"); // NOI18N
        btnRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadMouseClicked(evt);
            }
        });
        getContentPane().add(btnRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 90, 40));

        btnWrite.setFont(resourceMap.getFont("btnWrite.font")); // NOI18N
        btnWrite.setText(resourceMap.getString("btnWrite.text")); // NOI18N
        btnWrite.setName("btnWrite"); // NOI18N
        btnWrite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWriteMouseClicked(evt);
            }
        });
        getContentPane().add(btnWrite, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 90, 40));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-581)/2, (screenSize.height-516)/2, 581, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void lstDepartmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDepartmentMouseClicked
        DepartmentName depart = (DepartmentName)lstDepartment.getSelectedValue();
        txtDepartment.setText(depart.departmentName);
    }//GEN-LAST:event_lstDepartmentMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        listModel.setElementAt(lstDepartment.getSelectedIndex(), txtDepartment.getText());
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            this.lblMessage.setText("No Device");
            return;
        }

        for (int i = 0; i < DepartmentListModel.DEPT_COUNT; i++)
        {
            OneStringOutput output = SBXPCProxy.GetDepartName(SysUtil.MachineNumber, i, 0L);
            if (output.isSuccess())
            {
                this.listModel.setElementAt(i, output.value);
                errorCode = 0;
            }else {
                errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
            }
            this.lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        }

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadMouseClicked

    private void btnWriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWriteMouseClicked
        boolean ret;
        int errorCode = 0;
        
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            this.lblMessage.setText("No Device");
            return;
        }

        for (int i = 0; i < DepartmentListModel.DEPT_COUNT; i++)
        {
            DepartmentName depart = (DepartmentName)this.listModel.getElementAt(i);
            ret = SBXPCProxy.SetDepartName(SysUtil.MachineNumber, i, 0, depart.departmentName);
            if (ret)
                errorCode = 0;
            else
                errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
            
        this.lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnWriteMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnWrite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JList lstDepartment;
    private javax.swing.JFormattedTextField txtDepartment;
    // End of variables declaration//GEN-END:variables

    public class DepartmentListModel extends AbstractListModel
    {
        public static final int DEPT_COUNT = 20;
        DepartmentName[] departmentNameList = new DepartmentName[DEPT_COUNT];

        public DepartmentListModel()
        {
            for (int i = 0; i < DEPT_COUNT; i++)
            this.departmentNameList[i] = new DepartmentName(i);
        }

        public void setElementAt(int index, String departmentName)
        {
            if ((index < 0) || (index >= DEPT_COUNT))
                return;
            this.departmentNameList[index].departmentName = departmentName;
            fireContentsChanged(this, index, index);
        }

        @Override
        public int getSize() {
            return DEPT_COUNT;
        }

        @Override
        public Object getElementAt(int index) {
            return this.departmentNameList[index];
        }
    }

    public class DepartmentName
    {
        public final int index;
        public String departmentName;

        public DepartmentName(int index)
        {
            this.index = index;
            this.departmentName = "";
        }

        @Override
        public String toString()
        {
            NumberFormat formatter = new DecimalFormat("00");
            String ret = "[No.] " + formatter.format(this.index) + " ";
            ret = ret + "[Name] " + this.departmentName;
            return ret;
        }
    }
}
