/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LockControlFrame.java
 *
 * Created on Aug 20, 2011, 10:51:12 AM
 */
package smack.comm.sample;

import smack.comm.SBXPCProxy;
import smack.comm.output.OneLongOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class LockControlFrame extends javax.swing.JFrame {

    /** Creates new form LockControlFrame */
    public LockControlFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnUncondClose = new javax.swing.JButton();
        btnGetDoorStatus = new javax.swing.JButton();
        btnDoorOpen = new javax.swing.JButton();
        btnAutoRecover = new javax.swing.JButton();
        btnUncondOpen = new javax.swing.JButton();
        btnWarnCancel = new javax.swing.JButton();
        btnReboot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(LockControlFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 490, 31));

        btnUncondClose.setFont(resourceMap.getFont("btnUncondClose.font")); // NOI18N
        btnUncondClose.setText(resourceMap.getString("btnUncondClose.text")); // NOI18N
        btnUncondClose.setName("btnUncondClose"); // NOI18N
        btnUncondClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUncondCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnUncondClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 150, 30));

        btnGetDoorStatus.setFont(resourceMap.getFont("btnGetDoorStatus.font")); // NOI18N
        btnGetDoorStatus.setText(resourceMap.getString("btnGetDoorStatus.text")); // NOI18N
        btnGetDoorStatus.setName("btnGetDoorStatus"); // NOI18N
        btnGetDoorStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetDoorStatusMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetDoorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 30));

        btnDoorOpen.setFont(resourceMap.getFont("btnDoorOpen.font")); // NOI18N
        btnDoorOpen.setText(resourceMap.getString("btnDoorOpen.text")); // NOI18N
        btnDoorOpen.setName("btnDoorOpen"); // NOI18N
        btnDoorOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoorOpenMouseClicked(evt);
            }
        });
        getContentPane().add(btnDoorOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 150, 30));

        btnAutoRecover.setFont(resourceMap.getFont("btnAutoRecover.font")); // NOI18N
        btnAutoRecover.setText(resourceMap.getString("btnAutoRecover.text")); // NOI18N
        btnAutoRecover.setName("btnAutoRecover"); // NOI18N
        btnAutoRecover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAutoRecoverMouseClicked(evt);
            }
        });
        getContentPane().add(btnAutoRecover, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 150, 30));

        btnUncondOpen.setFont(resourceMap.getFont("btnUncondOpen.font")); // NOI18N
        btnUncondOpen.setText(resourceMap.getString("btnUncondOpen.text")); // NOI18N
        btnUncondOpen.setName("btnUncondOpen"); // NOI18N
        btnUncondOpen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUncondOpenMouseClicked(evt);
            }
        });
        getContentPane().add(btnUncondOpen, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 150, 30));

        btnWarnCancel.setFont(resourceMap.getFont("btnWarnCancel.font")); // NOI18N
        btnWarnCancel.setText(resourceMap.getString("btnWarnCancel.text")); // NOI18N
        btnWarnCancel.setName("btnWarnCancel"); // NOI18N
        btnWarnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWarnCancelMouseClicked(evt);
            }
        });
        getContentPane().add(btnWarnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 150, 30));

        btnReboot.setFont(resourceMap.getFont("btnReboot.font")); // NOI18N
        btnReboot.setText(resourceMap.getString("btnReboot.text")); // NOI18N
        btnReboot.setName("btnReboot"); // NOI18N
        btnReboot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRebootMouseClicked(evt);
            }
        });
        getContentPane().add(btnReboot, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 150, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-518)/2, (screenSize.height-219)/2, 518, 219);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnGetDoorStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetDoorStatusMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        OneLongOutput output;
        output = SBXPCProxy.GetDoorStatus(SysUtil.MachineNumber);
        
        if(output.isSuccess())
        {
            String message;
            switch((int)output.dwValue)
            {
                case 1: message = "Uncond Door Open State";    break;
                case 2: message = "Uncond Door Close State";   break;
                case 3: message = "Door Open State";           break;
                case 4: message = "Auto Recover State";        break;
                case 5: message = "Door Close State";          break;
                case 6: message = "Watching for Close";        break;
                case 7: message = "Illegal open";              break;
                default:message = "User State ";               break;
            }
            lblMessage.setText(message);
            errorCode = 0;
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
            lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        }
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetDoorStatusMouseClicked

    private void btnDoorOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoorOpenMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 3);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnDoorOpenMouseClicked

    private void btnUncondOpenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUncondOpenMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 1);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnUncondOpenMouseClicked

    private void btnAutoRecoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAutoRecoverMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 4);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnAutoRecoverMouseClicked

    private void btnUncondCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUncondCloseMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 2);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnUncondCloseMouseClicked

    private void btnRebootMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRebootMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 5);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnRebootMouseClicked

    private void btnWarnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWarnCancelMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.SetDoorStatus(SysUtil.MachineNumber, 6);
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnWarnCancelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoRecover;
    private javax.swing.JButton btnDoorOpen;
    private javax.swing.JButton btnGetDoorStatus;
    private javax.swing.JButton btnReboot;
    private javax.swing.JButton btnUncondClose;
    private javax.swing.JButton btnUncondOpen;
    private javax.swing.JButton btnWarnCancel;
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
