/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SystemInfoFrame.java
 *
 * Created on Aug 19, 2011, 9:53:22 PM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import smack.comm.SBXPCProxy;
import smack.comm.input.DeviceInfoStatusInput;
import smack.comm.output.GetDeviceTimeOutput;
import smack.comm.output.OneLongOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class SystemInfoFrame extends javax.swing.JFrame {

    /** Creates new form SystemInfoFrame */
    public SystemInfoFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnGetDeviceTime = new javax.swing.JButton();
        btnSetDeviceTime = new javax.swing.JButton();
        btnPowerOnDevice = new javax.swing.JButton();
        btnPowerOffDevice = new javax.swing.JButton();
        btnEnableDevice = new javax.swing.JButton();
        btnGetDeviceStatus = new javax.swing.JButton();
        btnGetDeviceInfo = new javax.swing.JButton();
        btnSetDeviceInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbParam = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtValue = new javax.swing.JFormattedTextField();
        chkEnableDevice = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(SystemInfoFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 560, 31));

        btnExit.setFont(resourceMap.getFont("btnExit.font")); // NOI18N
        btnExit.setText(resourceMap.getString("btnExit.text")); // NOI18N
        btnExit.setName("btnExit"); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 150, 30));

        btnGetDeviceTime.setFont(resourceMap.getFont("btnGetDeviceTime.font")); // NOI18N
        btnGetDeviceTime.setText(resourceMap.getString("btnGetDeviceTime.text")); // NOI18N
        btnGetDeviceTime.setName("btnGetDeviceTime"); // NOI18N
        btnGetDeviceTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetDeviceTimeMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetDeviceTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, 30));

        btnSetDeviceTime.setFont(resourceMap.getFont("btnSetDeviceTime.font")); // NOI18N
        btnSetDeviceTime.setText(resourceMap.getString("btnSetDeviceTime.text")); // NOI18N
        btnSetDeviceTime.setName("btnSetDeviceTime"); // NOI18N
        btnSetDeviceTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetDeviceTimeMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetDeviceTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 30));

        btnPowerOnDevice.setFont(resourceMap.getFont("btnPowerOnDevice.font")); // NOI18N
        btnPowerOnDevice.setText(resourceMap.getString("btnPowerOnDevice.text")); // NOI18N
        btnPowerOnDevice.setName("btnPowerOnDevice"); // NOI18N
        btnPowerOnDevice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPowerOnDeviceMouseClicked(evt);
            }
        });
        getContentPane().add(btnPowerOnDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 150, 30));

        btnPowerOffDevice.setFont(resourceMap.getFont("btnPowerOffDevice.font")); // NOI18N
        btnPowerOffDevice.setText(resourceMap.getString("btnPowerOffDevice.text")); // NOI18N
        btnPowerOffDevice.setName("btnPowerOffDevice"); // NOI18N
        btnPowerOffDevice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPowerOffDeviceMouseClicked(evt);
            }
        });
        getContentPane().add(btnPowerOffDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 150, 30));

        btnEnableDevice.setFont(resourceMap.getFont("btnEnableDevice.font")); // NOI18N
        btnEnableDevice.setText(resourceMap.getString("btnEnableDevice.text")); // NOI18N
        btnEnableDevice.setName("btnEnableDevice"); // NOI18N
        btnEnableDevice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnableDeviceMouseClicked(evt);
            }
        });
        getContentPane().add(btnEnableDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 150, 30));

        btnGetDeviceStatus.setFont(resourceMap.getFont("btnGetDeviceStatus.font")); // NOI18N
        btnGetDeviceStatus.setText(resourceMap.getString("btnGetDeviceStatus.text")); // NOI18N
        btnGetDeviceStatus.setName("btnGetDeviceStatus"); // NOI18N
        btnGetDeviceStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetDeviceStatusMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetDeviceStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 150, 30));

        btnGetDeviceInfo.setFont(resourceMap.getFont("btnGetDeviceInfo.font")); // NOI18N
        btnGetDeviceInfo.setText(resourceMap.getString("btnGetDeviceInfo.text")); // NOI18N
        btnGetDeviceInfo.setName("btnGetDeviceInfo"); // NOI18N
        btnGetDeviceInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetDeviceInfoMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetDeviceInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 30));

        btnSetDeviceInfo.setFont(resourceMap.getFont("btnSetDeviceInfo.font")); // NOI18N
        btnSetDeviceInfo.setText(resourceMap.getString("btnSetDeviceInfo.text")); // NOI18N
        btnSetDeviceInfo.setName("btnSetDeviceInfo"); // NOI18N
        btnSetDeviceInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetDeviceInfoMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetDeviceInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 150, 30));

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 20));

        cmbParam.setFont(resourceMap.getFont("cmbParam.font")); // NOI18N
        cmbParam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", " " }));
        cmbParam.setName("cmbParam"); // NOI18N
        getContentPane().add(cmbParam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 70, -1));

        jLabel4.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        txtValue.setFont(resourceMap.getFont("txtValue.font")); // NOI18N
        txtValue.setName("txtValue"); // NOI18N
        getContentPane().add(txtValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 190, -1));

        chkEnableDevice.setText(resourceMap.getString("chkEnableDevice.text")); // NOI18N
        chkEnableDevice.setName("chkEnableDevice"); // NOI18N
        getContentPane().add(chkEnableDevice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 65, 20, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-589)/2, (screenSize.height-274)/2, 589, 274);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnGetDeviceTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetDeviceTimeMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        GetDeviceTimeOutput output;
        output = SBXPCProxy.GetDeviceTime(SysUtil.MachineNumber);
        
        NumberFormat formatter = new DecimalFormat("00");
        if(output.isSuccess())
        {
            String timeString = output.dwYear + "/" + formatter.format(output.dwMonth) + "/" + formatter.format(output.dwDay) + " ";
            timeString += formatter.format(output.dwHour) + ":" + formatter.format(output.dwMinute) + ":" + formatter.format(output.dwSecond);
            lblMessage.setText(timeString);
            errorCode = 0;
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
            lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        }
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetDeviceTimeMouseClicked

    private void btnSetDeviceTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetDeviceTimeMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret  = SBXPCProxy.SetDeviceTime(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetDeviceTimeMouseClicked

    private void btnPowerOnDeviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPowerOnDeviceMouseClicked
        SBXPCProxy.PowerOnAllDevice(SysUtil.MachineNumber);
    }//GEN-LAST:event_btnPowerOnDeviceMouseClicked

    private void btnPowerOffDeviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPowerOffDeviceMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret  = SBXPCProxy.PowerOffDevice(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnPowerOffDeviceMouseClicked

    private void btnEnableDeviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnableDeviceMouseClicked
        boolean ret;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        if(chkEnableDevice.isSelected())
        {
            ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
            
            if(!ret)
            {
                lblMessage.setText(SysUtil.NO_DEVICE);
                return;
            }
            
            lblMessage.setText("Enable Device Success");
            btnEnableDevice.setText("Disable Device");
            chkEnableDevice.setSelected(false);
        }else
        {
            ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
            
            if(!ret)
            {
                lblMessage.setText(SysUtil.NO_DEVICE);
                return;
            }
            
            lblMessage.setText("Disable Device Success");
            btnEnableDevice.setText("Enable Device");
            chkEnableDevice.setSelected(true);
        }
    }//GEN-LAST:event_btnEnableDeviceMouseClicked

    private void btnGetDeviceInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetDeviceInfoMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        DeviceInfoStatusInput input = new DeviceInfoStatusInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwInfoStatusIndex = cmbParam.getSelectedIndex() + 1;
        
        OneLongOutput output;
        output = SBXPCProxy.GetDeviceInfo(input);
        
        if(output.isSuccess())
        {
            errorCode = 0;
            String message = "";
            switch((int)input.dwInfoStatusIndex)
            {
                case 1:  message = "(1) = ManagerCount = " + output.dwValue; break;
                case 2:  message = "(2) = Device ID = " + output.dwValue; break;
                case 3:  message = "(3) = Language = " + output.dwValue; break;
                case 4:  message = "(4) = PowerOffTime = " + output.dwValue; break;
                case 5:  message = "(5) = Lock release time = " + output.dwValue; break;
                case 6:  message = "(6) = GLogWarning = " + output.dwValue; break;
                case 7:  message = "(7) = SLogWarning = " + output.dwValue; break;
                case 8:  message = "(8) = ReVerifyTime = " + output.dwValue; break;
                case 9:  message = "(9) = Baudrate = " + output.dwValue; break;
                case 10: message = "(10) = Parity check = " + output.dwValue; break;
                case 11: message = "(11) = Stop bit = " + output.dwValue; break;
                case 12: message = "(12) = Date Seperator = " + output.dwValue; break;
                case 13: message = "(13) = Identificatin mode = " + output.dwValue; break;
                case 14: message = "(14) = LockOperate = " + output.dwValue; break;
                case 15: message = "(15) = Door sensor type = " + output.dwValue; break;
                case 16: message = "(16) = Door open time limit = " + output.dwValue; break;
                case 17: message = "(17) = Anti-pass = " + output.dwValue; break;
                case 18: message = "(18) = Auto sleep time = " + output.dwValue; break;
                case 19: message = "(19) = Daylight offset = " + output.dwValue; break;
                case 20: message = "(20) = UDP Server = " + SysUtil.pubLongToIPAddr(output.dwValue);
                case 21: message = "(21) = DHCP Use = " + output.dwValue; break;
                case 22: message = "(22) = NOT SUPPORTED = ";
                case 23: message = "(23) = Manager PC IP Address = " + SysUtil.pubLongToIPAddr(output.dwValue);
                case 24: message = "(24) = Event Send Type = " + output.dwValue; break;
            }
            lblMessage.setText(message);
        }
        else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
            lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        }
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetDeviceInfoMouseClicked

    private void btnSetDeviceInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetDeviceInfoMouseClicked
        boolean ret;
        int errorCode;
        DeviceInfoStatusInput input = new DeviceInfoStatusInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwInfoStatusIndex = cmbParam.getSelectedIndex() + 1;
        
        long dwValue;
        
        try{
            dwValue = Long.parseLong(txtValue.getText());
        }catch(Exception e)
        {
            lblMessage.setText("Invalid Format!");
            return;
        }
        
        if(input.dwInfoStatusIndex == 20 || input.dwInfoStatusIndex == 23)
            dwValue = SysUtil.pugIPAddrToLong(txtValue.getText());
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        
        ret = SBXPCProxy.SetDeviceInfo(input, dwValue);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetDeviceInfoMouseClicked

    private void btnGetDeviceStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetDeviceStatusMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        DeviceInfoStatusInput input = new DeviceInfoStatusInput();
        input.dwMachineNumber = SysUtil.MachineNumber;
        input.dwInfoStatusIndex = cmbParam.getSelectedIndex() + 1;
        
        OneLongOutput output;
        output = SBXPCProxy.GetDeviceStatus(input);
        
        if(output.isSuccess())
        {
            errorCode = 0;
            String message = "";
            switch((int)input.dwInfoStatusIndex)
            {
                case 1:  message = "(1) = Manager count = " + output.dwValue; break;
                case 2:  message = "(2) = User count = " + output.dwValue; break;
                case 3:  message = "(3) = Fp count = " + output.dwValue; break;
                case 4:  message = "(4) = Password count = " + output.dwValue; break;
                case 5:  message = "(5) = SLog count = " + output.dwValue; break;
                case 6:  message = "(6) = GLog count = " + output.dwValue; break;
                case 7:  message = "(7) = Card count = " + output.dwValue; break;
                case 8:  message = "(8) = Alarm status = " + output.dwValue; break;
            }
            lblMessage.setText(message);
        }
        else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
            lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        }
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetDeviceStatusMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnableDevice;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetDeviceInfo;
    private javax.swing.JButton btnGetDeviceStatus;
    private javax.swing.JButton btnGetDeviceTime;
    private javax.swing.JButton btnPowerOffDevice;
    private javax.swing.JButton btnPowerOnDevice;
    private javax.swing.JButton btnSetDeviceInfo;
    private javax.swing.JButton btnSetDeviceTime;
    private javax.swing.JCheckBox chkEnableDevice;
    private javax.swing.JComboBox cmbParam;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JFormattedTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
