jLabel1.text=Backup Number:
jLabel2.text=Enroll Number:
jLabel4.text=Duress:
jLabel5.text=Privilege:
jLabel6.text=UserTz3:
jLabel10.text=UserTz4:
jLabel9.text=User Depart:
jLabel8.text=UserTz2:
jLabel7.text=UserTz1:
jLabel11.text=UserTz5:
jLabel13.text=Card or Password:
jLabel14.text=Enroll Data:
jPanel1.border.border.title=User Photo Related
#NOI18N
jPanel1.border.border.titleFont=Times New Roman-Plain-14
#NOI18N
jPanel1.border.border.titleColor=0, 0, 0
jLabel12.text=Name:
txtPassword.text=
chkDisableUser.text=Disable User
txtUserTz1.text=
txtUserTz2.text=
txtUserTz3.text=
txtUserTz4.text=
txtUserDepart.text=
txtUserPhotoFile.text=
lblUserPhoto.text=
btnDeleteDb.text=Delete DB
#NOI18N
btnDeleteDb.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
btnGetEnrollData.text=Get Enroll Data
#NOI18N
btnGetEnrollData.font=Times New Roman 14 12 12 12 12 12 Bold
btnSetEnrollData.text=Set Enroll Data
#NOI18N
btnSetEnrollData.font=Times New Roman 14 12 12 12 12 Bold
btnDeleteEnrollData.text=Delete Enroll Data
#NOI18N
btnDeleteEnrollData.font=Times New Roman 14 12 12 12 12 12 Bold
btnGetAllEnrollData.text=Get All Enroll Data
#NOI18N
btnGetAllEnrollData.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnSetAllEnrollData.text=Set All Enroll Data
#NOI18N
btnSetAllEnrollData.font=Times New Roman 14 12 12 12 12 12 Bold
btnGetName.text=Get Name Data
#NOI18N
btnGetName.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnSetName.text=Set Name Data
#NOI18N
btnSetName.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnSetCompanyName.text=Set Company Name
#NOI18N
btnSetCompanyName.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnDeleteCompanyName.text=Delete Company Name
#NOI18N
btnDeleteCompanyName.font=Times New Roman 14 12 12 12 12 12 Bold
btnGetEnrollInfo.text=Get Enroll Info
#NOI18N
btnGetEnrollInfo.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnEnableUser.text=Enable User
#NOI18N
btnEnableUser.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnModifyPriviege.text=Modify Privilege
#NOI18N
btnModifyPriviege.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnModifyDuressFp.text=Modify Duress FP
#NOI18N
btnModifyDuressFp.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnUserPhoto.text=Get User Photo
#NOI18N
btnUserPhoto.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
btnSetUserPhoto.text=Set User Photo
#NOI18N
btnSetUserPhoto.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnDeleteUserPhoto.text=Delete User Photo
#NOI18N
btnDeleteUserPhoto.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnEmptyEnrollData.text=Empty Enroll Data
#NOI18N
btnEmptyEnrollData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 12 Bold
btnClearAllData.text=Clear All Data(E, GL, SL)
#NOI18N
btnClearAllData.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 Bold
txtUserTz5.text=
lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Bold-18
#NOI18N
txtPassword.font=Times New Roman-Plain-14
#NOI18N
cmbBackupNumber.font=Times New Roman-Plain-14
#NOI18N
cmbPrivilege.font=Times New Roman-Plain-14
#NOI18N
cmbDuress.font=Times New Roman-Plain-14
#NOI18N
txtUserTz1.font=Times New Roman-Plain-14
#NOI18N
txtUserTz2.font=Times New Roman-Plain-14
#NOI18N
txtUserTz3.font=Times New Roman-Plain-14
#NOI18N
txtUserTz4.font=Times New Roman-Plain-14
#NOI18N
txtUserTz5.font=Times New Roman-Plain-14
#NOI18N
txtUserDepart.font=Times New Roman-Plain-14
#NOI18N
txtUserPhotoFile.font=Times New Roman-Plain-14
#NOI18N
chkDisableUser.font=Times New Roman-Plain-14
#NOI18N
jLabel2.font=Times New Roman-Plain-14
#NOI18N
jLabel13.font=Times New Roman-Plain-14
#NOI18N
jLabel1.font=Times New Roman-Plain-14
#NOI18N
jLabel5.font=Times New Roman-Plain-14
#NOI18N
jLabel4.font=Times New Roman-Plain-14
#NOI18N
jLabel7.font=Times New Roman-Plain-14
#NOI18N
jLabel8.font=Times New Roman-Plain-14
#NOI18N
jLabel6.font=Times New Roman-Plain-14
txtEnrollNum.text=1
#NOI18N
txtEnrollNum.font=Times New Roman-Plain-14
#NOI18N
jLabel12.font=Times New Roman-Plain-14
#NOI18N
jLabel14.font=Times New Roman-Plain-14
#NOI18N
jLabel10.font=Times New Roman-Plain-14
#NOI18N
jLabel11.font=Times New Roman-Plain-14
#NOI18N
jLabel9.font=Times New Roman-Plain-14
#NOI18N
btnSendAllEnrollData.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnSendAllEnrollData.text=Send All Enroll Data
txtName.text=
lblTotal.text=Total:
#NOI18N
lblTotal.font=Times New Roman-Plain-14
btnUserPhotoBrowse.text=...
Form.title=Enroll Management
