# To change this template, choose Tools | Templates
# and open the template in the editor.

lblMessage.text=Message
#NOI18N
lblMessage.font=Times New Roman-Bold-18
#NOI18N
btnDoorOpen1.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 Bold
btnDoorOpen1.text=Exit
#NOI18N
btnReadSLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadAllSLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnEmptySLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnReadAllGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnEmptyGLogData.font=Times New Roman 14 12 12 12 12 12 12 12 12 12 12 Bold
#NOI18N
jLabel5.font=Times New Roman 14 Plain
jLabel5.text=Log Data:
lblTotal.text=Total:
#NOI18N
lblTotal.font=Times New Roman-Plain-14
chkSearchAndDelete.text=and Delete
#NOI18N
chkSearchAndDelete.font=Times New Roman-Plain-14
chkReadMark.text=Read Mark
#NOI18N
chkReadMark.font=Times New Roman 14 Plain
jPanel1.border.title=GLog Search Range
#NOI18N
jPanel1.border.titleColor=0, 0, 0
#NOI18N
jPanel1.border.titleFont=Times New Roman-Plain-14
#NOI18N
jLabel6.font=Times New Roman 14 12 Plain
jLabel6.text=Start:
jLabel7.text=End:
#NOI18N
jLabel7.font=Times New Roman 14 12 Plain
chkUseSearchRange.text=Use Search Range
#NOI18N
chkUseSearchRange.font=Times New Roman 14 Plain
txtStart.text=
txtEnd.text=
#NOI18N
txtEnd.font=Times New Roman-Plain-14
setSearchRange.text=Set Range
#NOI18N
setSearchRange.font=Tahoma-Bold-11
lblGLogPhoto.text=
chkShowGLogPhoto.text=Show GLog Photo
Form.title=Log Management
