# Resources for the MainFrameView class

# top-level menus

fileMenu.text = File
helpMenu.text = Help

# @Action resources

showAboutBox.Action.text = &About...
showAboutBox.Action.shortDescription = Show the application's information dialog

# status bar resources

StatusBar.messageTimeout = 5000
StatusBar.busyAnimationRate = 30
StatusBar.idleIcon = busyicons/idle-icon.png
StatusBar.busyIcons[0]  = busyicons/busy-icon0.png
StatusBar.busyIcons[1]  = busyicons/busy-icon1.png
StatusBar.busyIcons[2]  = busyicons/busy-icon2.png
StatusBar.busyIcons[3]  = busyicons/busy-icon3.png
StatusBar.busyIcons[4]  = busyicons/busy-icon4.png
StatusBar.busyIcons[5]  = busyicons/busy-icon5.png
StatusBar.busyIcons[6]  = busyicons/busy-icon6.png
StatusBar.busyIcons[7]  = busyicons/busy-icon7.png
StatusBar.busyIcons[8]  = busyicons/busy-icon8.png
StatusBar.busyIcons[9]  = busyicons/busy-icon9.png
StatusBar.busyIcons[10] = busyicons/busy-icon10.png
StatusBar.busyIcons[11] = busyicons/busy-icon11.png
StatusBar.busyIcons[12] = busyicons/busy-icon12.png
StatusBar.busyIcons[13] = busyicons/busy-icon13.png
StatusBar.busyIcons[14] = busyicons/busy-icon14.png
connectPanel.toolTipText=
#NOI18N
connectPanel.border.titleFont=Times New Roman-Bold-14
connectPanel.border.title=Connect
#NOI18N
connectPanel.border.titleColor=0, 0, 0
jLabel1.text=Machine Number:
#NOI18N
jLabel1.font=Times New Roman-Plain-14
#NOI18N
jLabel3.font=Arial-Plain-24
jLabel3.text=SBXPC Sample
#NOI18N
jLabel3.foreground=255, 0, 0
#NOI18N
jLabel4.font=Arial 24-Italic-14
jLabel4.text=SB3600
#NOI18N
jLabel4.foreground=0, 0, 255
btnOpen.text=Open
#NOI18N
btnOpen.font=Times New Roman 14 Bold
btnClose.text=Close
#NOI18N
btnClose.font=Times New Roman 14 Bold
#NOI18N
jLabel2.font=Times New Roman 14 Plain
jLabel2.text=Password:
jLabel5.text=IP Address:
#NOI18N
jLabel5.font=Times New Roman 14 12 Plain
jLabel6.text=Port Number:
#NOI18N
jLabel6.font=Times New Roman 14 12 Plain
lblDeviceUID.text=Device UID:
lblDeviceUID.font=Times New Roman 14 12 Plain
txtIPAddress.text=192.168.1.224
#NOI18N
txtIPAddress.font=Times New Roman 14 Plain
txtPortNumber.text=5005
txtDeviceUID.font=Times New Roman 14 Plain
txtDeviceUID.text=447214D080691010
#NOI18N
txtPortNumber.font=Times New Roman 14 Plain
txtPassword.text=0
#NOI18N
txtPassword.font=Times New Roman-Plain-14
jLabel10.text=Baudrate:
#NOI18N
jLabel10.font=Times New Roman 14 12 Plain
jLabel9.text=Comm Port:
#NOI18N
jLabel9.font=Times New Roman 14 12 Plain
SerialDevicePanel.toolTipText=
#NOI18N
SerialDevicePanel.border.titleFont=Times New Roman 14 12 12 Bold
#NOI18N
SerialDevicePanel.border.titleColor=0, 0, 0
NetworkPanel.toolTipText=
#NOI18N
NetworkPanel.border.titleFont=Times New Roman 14 Bold
#NOI18N
NetworkPanel.border.titleColor=0, 0, 0
NetworkPanel.border.title=Network Device
btnEnroll.text=Enroll Data Management
#NOI18N
btnEnroll.font=Times New Roman 14 12 12 12 Bold
btnSysInfo.text=System Info
#NOI18N
btnSysInfo.font=Times New Roman 14 12 12 12 Bold
btnLockControl.text=Lock Control
#NOI18N
btnLockControl.font=Times New Roman 14 12 12 Bold
btnBellTime.text=Bell Time
#NOI18N
btnBellTime.font=Times New Roman 14 12 12 12 12 Bold
btnTrMode.text=Log TZone
#NOI18N
btnTrMode.font=Times New Roman 14 12 12 12 Bold
btnProductCode.text=Get SN
#NOI18N
btnProductCode.font=Times New Roman 14 12 12 12 12 12 Bold
btnAccessTz.text=AccessTZone
#NOI18N
btnAccessTz.font=Times New Roman 14 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 Bold
#NOI18N
cmbMachineNumber.font=Times New Roman-Plain-14
#NOI18N
cmbCommPort.font=Times New Roman 14 12 Plain
#NOI18N
cmbBaudrate.font=Times New Roman 14 12 Plain
optSerial.text=Serial Device
optNetwork.text=Network Device
optViaP2P.text=via P2P
#NOI18N
optNetwork.font=Times New Roman-Bold-14
ManagementPanel.toolTipText=
#NOI18N
ManagementPanel.border.titleFont=Times New Roman 14 12 Bold
#NOI18N
ManagementPanel.border.titleColor=0, 0, 0
ManagementPanel.border.title=Management Group
btnModeTZone.text=ScreenSaver
#NOI18N
btnModeTZone.font=Times New Roman 14 12 12 12 12 12 12 Bold
btnHoliday.text=Daigong
#NOI18N
btnHoliday.font=Times New Roman 14 12 12 12 12 Bold
btnEventCapture.text=Event Capture
#NOI18N
btnEventCapture.font=Times New Roman 14 12 12 Bold
btnDepartment.text=Department
#NOI18N
btnDepartment.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
btnLog.text=Log Data Management
#NOI18N
btnLog.font=Times New Roman 14 12 12 12 Bold
SerialDevicePanel.border.title=Serial Device
