// dispids.h : header file for OCX disp ids

#ifndef _DISP_IDS_H_
#define _DISP_IDS_H_

// Properties
#define DISPID_COMMPORT					1
#define DISPID_BAUDRATE					2
#define DISPID_READMARK					3

// Methods
#define DISPID_SETMACHINETYPE			4
#define DISPID_DOTNET					5

#define DISPID_GETENROLLDATA			6
#define DISPID_GETENROLLDATA1			7
#define DISPID_SETENROLLDATA			8
#define DISPID_SETENROLLDATA1			9
#define DISPID_DELETEENROLLDATA			10
#define DISPID_READSUPERLOGDATA			11
#define DISPID_GETSUPERLOGDATA			12
#define DISPID_READGENERALLOGDATA		13
#define DISPID_GETGENERALLOGDATA		14
#define DISPID_READALLSLOGDATA			15
#define DISPID_GETALLSLOGDATA			16
#define DISPID_READALLGLOGDATA			17
#define DISPID_GETALLGLOGDATA			18
#define DISPID_GETDEVICESTATUS			19
#define DISPID_GETDEVICEINFO			20
#define DISPID_SETDEVICEINFO			21
#define DISPID_ENABLEDEVICE				22
#define DISPID_ENABLEUSER				23
#define DISPID_GETDEVICETIME			24
#define DISPID_SETDEVICETIME			25
#define DISPID_POWERONALLDEVICE			26
#define DISPID_POWEROFFDEVICE			27
#define DISPID_MODIFYPRIVILEGE			28
#define DISPID_READALLUSERID			29
#define DISPID_GETALLUSERID				30
#define DISPID_GETSERIALNUMBER			31
#define DISPID_GETBACKUPNUMBER			32
#define DISPID_GETPRODUCTCODE			33
#define DISPID_CLEARKEEPERDATA			34
#define DISPID_EMPTYENROLLDATA			35
#define DISPID_EMPTYGENERALLOGDATA		36
#define DISPID_EMPTYSUPERLOGDATA		37
#define DISPID_GETUSERNAME				38
#define DISPID_GETUSERNAME1				39
#define DISPID_SETUSERNAME				40
#define DISPID_SETUSERNAME1				41
#define DISPID_GETCOMPANYNAME			42
#define DISPID_GETCOMPANYNAME1			43
#define DISPID_SETCOMPANYNAME			44
#define DISPID_SETCOMPANYNAME1			45
#define DISPID_GETDOORSTATUS			46
#define DISPID_SETDOORSTATUS			47
#define DISPID_GETBELLTIME				48
#define DISPID_SETBELLTIME				49
#define DISPID_CONNECTSERIAL			50
#define DISPID_CONNECTTCPIP				51
#define DISPID_DISCONNECT				52
#define DISPID_SETIPADDRESS				53
#define DISPID_OPENCOMMPORT				54
#define DISPID_CLOSECOMMPORT			55
#define DISPID_GETLASTERROR				56
#define DISPID_GENERALOPERATIONXML		57
#define DISPID_GETDEVICELONGINFO		58
#define DISPID_SETDEVICELONGINFO		59
#define DISPID_MODIFYDURESSFP			60
#define DISPID_GETMACHINEIP				61
#define DISPID_GETDEPARTNAME			62
#define DISPID_SETDEPARTNAME			63

#define DISPID_STARTEVENTCAPTURE		64
#define DISPID_STOPEVENTCAPTURE			65

// XML Helpers
#define DISPID_XML_HELPER_OFFSET		66
#define DISPID_XML_PARSEINT				(DISPID_XML_HELPER_OFFSET + 0)
#define DISPID_XML_PARSELONG			(DISPID_XML_HELPER_OFFSET + 1)
#define DISPID_XML_PARSEBOOLEAN			(DISPID_XML_HELPER_OFFSET + 2)
#define DISPID_XML_PARSESTRING			(DISPID_XML_HELPER_OFFSET + 3)
#define DISPID_XML_PARSEBINARYBYTE		(DISPID_XML_HELPER_OFFSET + 4)
#define DISPID_XML_PARSEBINARYWORD		(DISPID_XML_HELPER_OFFSET + 5)
#define DISPID_XML_PARSEBINARYLONG		(DISPID_XML_HELPER_OFFSET + 6)
#define DISPID_XML_PARSEBINARYUNICODE	(DISPID_XML_HELPER_OFFSET + 7)
#define DISPID_XML_ADDINT				(DISPID_XML_HELPER_OFFSET + 8)
#define DISPID_XML_ADDLONG				(DISPID_XML_HELPER_OFFSET + 9)
#define DISPID_XML_ADDBOOLEAN			(DISPID_XML_HELPER_OFFSET + 10)
#define DISPID_XML_ADDSTRING			(DISPID_XML_HELPER_OFFSET + 11)
#define DISPID_XML_ADDBINARYBYTE		(DISPID_XML_HELPER_OFFSET + 12)
#define DISPID_XML_ADDBINARYWORD		(DISPID_XML_HELPER_OFFSET + 13)
#define DISPID_XML_ADDBINARYLONG		(DISPID_XML_HELPER_OFFSET + 14)
#define DISPID_XML_ADDBINARYUNICODE		(DISPID_XML_HELPER_OFFSET + 15)
#define DISPID_XML_ADDBINARYGLYPH		(DISPID_XML_HELPER_OFFSET + 16)

#define DISPID_CONNECTP2P				(DISPID_XML_HELPER_OFFSET + 17)
#define DISPID_PREPAREP2P				(DISPID_XML_HELPER_OFFSET + 18)

#define DISPID_XML_ADDBINARYNAMEGLYPH	(DISPID_XML_HELPER_OFFSET + 19)
#define DISPID_XML_PARSEMULTIUNICODE	(DISPID_XML_HELPER_OFFSET + 20)

#define DISPID_SETDEVICETIME1			(DISPID_XML_HELPER_OFFSET + 21)
#define DISPID_DISCONNECT1				(DISPID_XML_HELPER_OFFSET + 22)
#define DISPID_DISCONNECTALL			(DISPID_XML_HELPER_OFFSET + 23)
#define DISPID_GENERALOPERATIONXML1		(DISPID_XML_HELPER_OFFSET + 24)
#define DISPID_USEINTERNALREDRAW		(DISPID_XML_HELPER_OFFSET + 25)

#define DISPID_GETINTERNALFWVER			(DISPID_XML_HELPER_OFFSET + 26)

// Log Management with Position
#define DISPID_READGLOGWITHPOS			(DISPID_XML_HELPER_OFFSET + 27)
#define DISPID_READSLOGWITHPOS			(DISPID_XML_HELPER_OFFSET + 28)
#define DISPID_GETDEVICEUNIQUEID		(DISPID_XML_HELPER_OFFSET + 29)
#define DISPID_GETDEVICEUNIQUEID1		(DISPID_XML_HELPER_OFFSET + 30)
#define DISPID_GETDEVICEMODEL			(DISPID_XML_HELPER_OFFSET + 31)
#define DISPID_XML_PARSEBINARYANSI2UNICODE	(DISPID_XML_HELPER_OFFSET + 32)

// Event Handlers
#define EVENTID_ONRECEIVEEVENTXML		1

#endif // _DISP_IDS_H_