/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EventCaptureFrame.java
 *
 * Created on Aug 26, 2011, 7:05:46 PM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import smack.comm.SBXPCProxy;
import smack.comm.SBXPCXMLEventListener;
import smack.comm.output.OneStringOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class EventCaptureFrame extends javax.swing.JFrame implements SBXPCXMLEventListener{

    DefaultListModel listModel = new DefaultListModel();
    
    /** Creates new form EventCaptureFrame */
    public EventCaptureFrame() {
        initComponents();
        lstEventList.setModel(listModel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDevices = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        cmbCommPort = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbBaudrate = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        optSerial = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIPAddress = new javax.swing.JTextField();
        txtPortNumber = new javax.swing.JTextField();
        optNetwork = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        btnStartCapture = new javax.swing.JButton();
        btnStopCapture = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEventList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(EventCaptureFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel5.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel5.border.titleFont"), resourceMap.getColor("jPanel5.border.titleColor"))); // NOI18N
        jPanel5.setToolTipText(resourceMap.getString("jPanel5.toolTipText")); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbCommPort.setFont(resourceMap.getFont("cmbCommPort.font")); // NOI18N
        cmbCommPort.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USB", "COM1", "COM2", "COM3", "COM4", "COM5", "COM6", " " }));
        cmbCommPort.setEnabled(false);
        cmbCommPort.setName("cmbCommPort"); // NOI18N
        jPanel5.add(cmbCommPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 20));

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 20));

        cmbBaudrate.setFont(resourceMap.getFont("cmbBaudrate.font")); // NOI18N
        cmbBaudrate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9600", "19200", "38400", "57600", "115200", " " }));
        cmbBaudrate.setSelectedIndex(4);
        cmbBaudrate.setEnabled(false);
        cmbBaudrate.setName("cmbBaudrate"); // NOI18N
        jPanel5.add(cmbBaudrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 20));

        jLabel10.setFont(resourceMap.getFont("jLabel10.font")); // NOI18N
        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        btnGroupDevices.add(optSerial);
        optSerial.setFont(resourceMap.getFont("optSerial.font")); // NOI18N
        optSerial.setText(resourceMap.getString("optSerial.text")); // NOI18N
        optSerial.setName("optSerial"); // NOI18N
        optSerial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                optSerialStateChanged(evt);
            }
        });
        jPanel5.add(optSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 270, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel3.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel3.border.titleFont"), resourceMap.getColor("jPanel3.border.titleColor"))); // NOI18N
        jPanel3.setToolTipText(resourceMap.getString("jPanel3.toolTipText")); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtIPAddress.setFont(resourceMap.getFont("txtIPAddress.font")); // NOI18N
        txtIPAddress.setText(resourceMap.getString("txtIPAddress.text")); // NOI18N
        txtIPAddress.setName("txtIPAddress"); // NOI18N
        jPanel3.add(txtIPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 150, -1));

        txtPortNumber.setFont(resourceMap.getFont("txtPortNumber.font")); // NOI18N
        txtPortNumber.setText(resourceMap.getString("txtPortNumber.text")); // NOI18N
        txtPortNumber.setName("txtPortNumber"); // NOI18N
        jPanel3.add(txtPortNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        btnGroupDevices.add(optNetwork);
        optNetwork.setFont(resourceMap.getFont("optNetwork.font")); // NOI18N
        optNetwork.setSelected(true);
        optNetwork.setText(resourceMap.getString("optNetwork.text")); // NOI18N
        optNetwork.setName("optNetwork"); // NOI18N
        optNetwork.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                optNetworkStateChanged(evt);
            }
        });
        jPanel3.add(optNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 270, 130));

        btnClear.setFont(resourceMap.getFont("btnClear.font")); // NOI18N
        btnClear.setText(resourceMap.getString("btnClear.text")); // NOI18N
        btnClear.setName("btnClear"); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 30));

        btnStartCapture.setFont(resourceMap.getFont("btnStartCapture.font")); // NOI18N
        btnStartCapture.setText(resourceMap.getString("btnStartCapture.text")); // NOI18N
        btnStartCapture.setName("btnStartCapture"); // NOI18N
        btnStartCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartCaptureMouseClicked(evt);
            }
        });
        getContentPane().add(btnStartCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 30));

        btnStopCapture.setFont(resourceMap.getFont("btnStopCapture.font")); // NOI18N
        btnStopCapture.setText(resourceMap.getString("btnStopCapture.text")); // NOI18N
        btnStopCapture.setEnabled(false);
        btnStopCapture.setName("btnStopCapture"); // NOI18N
        btnStopCapture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStopCaptureMouseClicked(evt);
            }
        });
        getContentPane().add(btnStopCapture, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, 30));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        lstEventList.setFont(resourceMap.getFont("lstEventList.font")); // NOI18N
        lstEventList.setName("lstEventList"); // NOI18N
        jScrollPane1.setViewportView(lstEventList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 680, 280));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-713)/2, (screenSize.height-526)/2, 713, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void optSerialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_optSerialStateChanged
        if(optSerial.isSelected())
            switchConnectMode(false);
}//GEN-LAST:event_optSerialStateChanged

    private void optNetworkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_optNetworkStateChanged
        if(optNetwork.isSelected())
            switchConnectMode(true);
}//GEN-LAST:event_optNetworkStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        listModel.clear();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnStartCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartCaptureMouseClicked
        SBXPCProxy.addXMLListener(this);
        if (this.optNetwork.isSelected())
            SBXPCProxy.StartEventCapture(0L, SysUtil.pugIPAddrToLong(this.txtIPAddress.getText()), Long.parseLong(this.txtPortNumber.getText()));
        else
            SBXPCProxy.StartEventCapture(1L, this.cmbCommPort.getSelectedIndex() + 1, Long.parseLong(this.cmbBaudrate.getSelectedItem().toString()));
        optSerial.setEnabled(false);
        optNetwork.setEnabled(false);
        btnStopCapture.setEnabled(true);
        btnStartCapture.setEnabled(false);
    }//GEN-LAST:event_btnStartCaptureMouseClicked

    private void btnStopCaptureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStopCaptureMouseClicked
        SBXPCProxy.removeXMLListener(this);
        SBXPCProxy.StopEventCapture();
        switchConnectMode(this.optNetwork.isSelected());
        optSerial.setEnabled(true);
        optNetwork.setEnabled(true);
        btnStopCapture.setEnabled(false);
        btnStartCapture.setEnabled(true);
    }//GEN-LAST:event_btnStopCaptureMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupDevices;
    private javax.swing.JButton btnStartCapture;
    private javax.swing.JButton btnStopCapture;
    private javax.swing.JComboBox cmbBaudrate;
    private javax.swing.JComboBox cmbCommPort;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstEventList;
    private javax.swing.JRadioButton optNetwork;
    private javax.swing.JRadioButton optSerial;
    private javax.swing.JTextField txtIPAddress;
    private javax.swing.JTextField txtPortNumber;
    // End of variables declaration//GEN-END:variables

    private void switchConnectMode(boolean bNetwork)
    {
        cmbCommPort.setEnabled(!bNetwork);
        cmbBaudrate.setEnabled(!bNetwork);
        txtIPAddress.setEnabled(bNetwork);
        txtPortNumber.setEnabled(bNetwork);
    }

    @Override
    public void OnReceiveEventXML(String eventXML) {
        
        int year, month, day, hour, minute, second, weekday;
        String strMachineType = ""; String strEventType = "";
        String str1 = ""; String str2 = ""; String str3 = ""; String str4 = "";
        String strXML = eventXML;

        year = SBXPCProxy.XML_ParseInt(strXML, "Year");
        month = SBXPCProxy.XML_ParseInt(strXML, "Month");
        day = SBXPCProxy.XML_ParseInt(strXML, "Day");
        hour = SBXPCProxy.XML_ParseInt(strXML, "Hour");
        minute = SBXPCProxy.XML_ParseInt(strXML, "Minute");
        second = SBXPCProxy.XML_ParseInt(strXML, "Second");
        weekday = SBXPCProxy.XML_ParseInt(strXML, "Weekday");

        int machinId = SBXPCProxy.XML_ParseInt(strXML, "MachineID");

        OneStringOutput output = SBXPCProxy.XML_ParseString(strXML, "MachineType"); strMachineType = output.value;
        output = SBXPCProxy.XML_ParseString(strXML, "EventType"); strEventType = output.value;

        NumberFormat datetimeFormat = new DecimalFormat("00");
        NumberFormat idFormat = new DecimalFormat("00000");
        String eventItemString = datetimeFormat.format(year) + "-";
        eventItemString = eventItemString + datetimeFormat.format(month) + "-";
        eventItemString = eventItemString + datetimeFormat.format(day) + " ";
        eventItemString = eventItemString + datetimeFormat.format(hour) + ":";
        eventItemString = eventItemString + datetimeFormat.format(minute);
        eventItemString = eventItemString + datetimeFormat.format(second);
        
        eventItemString = eventItemString + "[" + strMachineType + ":";
        eventItemString = eventItemString + machinId + "] ";
        eventItemString = eventItemString + strEventType + ", ";

        if ("Management Log".equals(strEventType))
        {
            int managerId = SBXPCProxy.XML_ParseInt(strXML, "ManagerID");
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "Action");
            int result = (int)SBXPCProxy.XML_ParseLong(strXML, "Result");
            eventItemString = eventItemString + "Manager ID = " + idFormat.format(managerId) + ",";
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId) + ",";
            eventItemString = eventItemString + "Action = " + output.value + ", ";
            eventItemString = eventItemString + "Result = " + result;
        } else if ("Time Log".equals(strEventType))
        {
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "AttendanceStatus"); str1 = output.value;
            output = SBXPCProxy.XML_ParseString(strXML, "VerificationMode"); str2 = output.value;
            output = SBXPCProxy.XML_ParseString(strXML, "AntipassStatus"); str3 = output.value;
            output = SBXPCProxy.XML_ParseString(strXML, "Photo"); str4 = output.value;
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId);
            eventItemString = eventItemString + "AttendanceStatus = " + str1 + ", ";
            eventItemString = eventItemString + "VerificationMode = " + str2 + ", ";
            eventItemString = eventItemString + "AntipassStatus = " + str3 + ", ";
            eventItemString = eventItemString + "Photo = " + str4;
        } else if ("Verification Success".equals(strEventType))
        {
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "VerificationMode");
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId);
            eventItemString = eventItemString + "VerificationMode = " + output.value;
        } else if ("Verification Failure".equals(strEventType))
        {
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "VerificationMode"); str1 = output.value;
            output = SBXPCProxy.XML_ParseString(strXML, "ReasonOfFailure"); str2 = output.value;
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId) + ",";
            eventItemString = eventItemString + "VerificationMode = " + str1 + ", ";
            eventItemString = eventItemString + "ReasonOfFailure = " + str2;
        } else if ("Alarm On".equals(strEventType))
        {
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "AlarmType");
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId);
            eventItemString = eventItemString + "AlarmType = " + output.value;
        } else if ("Alarm Off".equals(strEventType))
        {
            int userId = SBXPCProxy.XML_ParseInt(strXML, "UserID");
            output = SBXPCProxy.XML_ParseString(strXML, "AlarmType"); str1 = output.value;
            output = SBXPCProxy.XML_ParseString(strXML, "AlarmOffMethod"); str2 = output.value;
            eventItemString = eventItemString + "User ID = " + idFormat.format(userId);
            eventItemString = eventItemString + "AlarmType = " + str1 + ", ";
            eventItemString = eventItemString + "AlarmOffMethod = " + str2;
        } else if ("DoorBell".equals(strEventType))
        {
            output = SBXPCProxy.XML_ParseString(strXML, "InputType");
            eventItemString = eventItemString + "Input Type = " + output.value;
        }
        
        SwingUtilities.invokeLater(new AddItemStringProc(eventItemString));
    }
    
    private class AddItemStringProc implements Runnable
    {
        private String itemString;

        public AddItemStringProc(String itemString)
        {
            this.itemString = itemString;
        }

        public void run() {
            listModel.addElement(itemString);
        }
        
    }
            
}
