/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LogMngFrame.java
 *
 * Created on Aug 20, 2011, 11:15:33 AM
 */
package smack.comm.sample;

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;
import smack.comm.SBXPCProxy;
import smack.comm.data.GeneralLogData;
import smack.comm.data.SuperLogData;
import smack.comm.output.GeneralLogDataOutput;
import smack.comm.output.OneStringOutput;
import smack.comm.output.SuperLogDataOutput;
import smack.comm.output.XMLParseBinaryByteOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author smackbio
 */
public class LogMngFrame extends javax.swing.JFrame {

    SLogDataListModel superLogListModel = new SLogDataListModel();
    GLogDataListModel generalLogListMOdel = new GLogDataListModel();
    
    private int prevSelectedRow = -1;
    /** Creates new form LogMngFrame */
    public LogMngFrame() {
        initComponents();
        txtStart.setValue(new Date());
        txtEnd.setValue(new Date());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogList = new javax.swing.JTable();
        btnDoorOpen1 = new javax.swing.JButton();
        btnReadSLogData = new javax.swing.JButton();
        btnReadAllSLogData = new javax.swing.JButton();
        btnEmptySLogData = new javax.swing.JButton();
        btnReadGLogData = new javax.swing.JButton();
        btnReadAllGLogData = new javax.swing.JButton();
        btnEmptyGLogData = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chkShowGLogPhoto = new javax.swing.JCheckBox();
        chkSearchAndDelete = new javax.swing.JCheckBox();
        chkReadMark = new javax.swing.JCheckBox();
        lblGLogPhoto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkUseSearchRange = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        setSearchRange = new javax.swing.JButton();
        txtStart = new javax.swing.JFormattedTextField();
        txtEnd = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(LogMngFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 880, 31));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tblLogList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLogList.setName("tblLogList"); // NOI18N
        tblLogList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLogList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLogListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLogList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, 710, 350));

        btnDoorOpen1.setFont(resourceMap.getFont("btnDoorOpen1.font")); // NOI18N
        btnDoorOpen1.setText(resourceMap.getString("btnDoorOpen1.text")); // NOI18N
        btnDoorOpen1.setName("btnDoorOpen1"); // NOI18N
        btnDoorOpen1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoorOpen1MouseClicked(evt);
            }
        });
        getContentPane().add(btnDoorOpen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 110, 50));

        btnReadSLogData.setFont(resourceMap.getFont("btnReadSLogData.font")); // NOI18N
        btnReadSLogData.setText("<html><center>Read<br>SLog Data</center></html>");
        btnReadSLogData.setName("btnReadSLogData"); // NOI18N
        btnReadSLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadSLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadSLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 110, 50));

        btnReadAllSLogData.setFont(resourceMap.getFont("btnReadAllSLogData.font")); // NOI18N
        btnReadAllSLogData.setText("<html><center>Read<br>All SLog Data<center></html>");
        btnReadAllSLogData.setName("btnReadAllSLogData"); // NOI18N
        btnReadAllSLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadAllSLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadAllSLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 110, 50));

        btnEmptySLogData.setFont(resourceMap.getFont("btnEmptySLogData.font")); // NOI18N
        btnEmptySLogData.setText("<html><center>Empty<br>SLog Data<center></html>");
        btnEmptySLogData.setName("btnEmptySLogData"); // NOI18N
        btnEmptySLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptySLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmptySLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 110, 50));

        btnReadGLogData.setFont(resourceMap.getFont("btnReadGLogData.font")); // NOI18N
        btnReadGLogData.setText("<html><center>Read<br>GLog Data<center></html>");
        btnReadGLogData.setName("btnReadGLogData"); // NOI18N
        btnReadGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 110, 50));

        btnReadAllGLogData.setFont(resourceMap.getFont("btnReadAllGLogData.font")); // NOI18N
        btnReadAllGLogData.setText("<html><center>Read<br>All GLog Data<center></html>");
        btnReadAllGLogData.setName("btnReadAllGLogData"); // NOI18N
        btnReadAllGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReadAllGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnReadAllGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 110, 50));

        btnEmptyGLogData.setFont(resourceMap.getFont("btnEmptyGLogData.font")); // NOI18N
        btnEmptyGLogData.setText("<html><center>Empty<br>GLog Data<center></html>");
        btnEmptyGLogData.setName("btnEmptyGLogData"); // NOI18N
        btnEmptyGLogData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmptyGLogDataMouseClicked(evt);
            }
        });
        getContentPane().add(btnEmptyGLogData, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 110, 50));

        lblTotal.setFont(resourceMap.getFont("lblTotal.font")); // NOI18N
        lblTotal.setText(resourceMap.getString("lblTotal.text")); // NOI18N
        lblTotal.setName("lblTotal"); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 20));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        chkShowGLogPhoto.setText(resourceMap.getString("chkShowGLogPhoto.text")); // NOI18N
        chkShowGLogPhoto.setName("chkShowGLogPhoto"); // NOI18N
        getContentPane().add(chkShowGLogPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 55, -1, -1));

        chkSearchAndDelete.setFont(resourceMap.getFont("chkSearchAndDelete.font")); // NOI18N
        chkSearchAndDelete.setText(resourceMap.getString("chkSearchAndDelete.text")); // NOI18N
        chkSearchAndDelete.setName("chkSearchAndDelete"); // NOI18N
        getContentPane().add(chkSearchAndDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 55, -1, -1));

        chkReadMark.setFont(resourceMap.getFont("chkReadMark.font")); // NOI18N
        chkReadMark.setSelected(true);
        chkReadMark.setText(resourceMap.getString("chkReadMark.text")); // NOI18N
        chkReadMark.setName("chkReadMark"); // NOI18N
        getContentPane().add(chkReadMark, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 55, -1, -1));

        lblGLogPhoto.setText(resourceMap.getString("lblGLogPhoto.text")); // NOI18N
        lblGLogPhoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblGLogPhoto.setName("lblGLogPhoto"); // NOI18N
        getContentPane().add(lblGLogPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 160, 140));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, resourceMap.getString("jPanel1.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, resourceMap.getFont("jPanel1.border.titleFont"), resourceMap.getColor("jPanel1.border.titleColor"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        chkUseSearchRange.setFont(resourceMap.getFont("chkUseSearchRange.font")); // NOI18N
        chkUseSearchRange.setText(resourceMap.getString("chkUseSearchRange.text")); // NOI18N
        chkUseSearchRange.setName("chkUseSearchRange"); // NOI18N

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        setSearchRange.setFont(resourceMap.getFont("setSearchRange.font")); // NOI18N
        setSearchRange.setText(resourceMap.getString("setSearchRange.text")); // NOI18N
        setSearchRange.setName("setSearchRange"); // NOI18N
        setSearchRange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setSearchRangeMouseClicked(evt);
            }
        });

        txtStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtStart.setText(resourceMap.getString("txtStart.text")); // NOI18N
        txtStart.setFont(resourceMap.getFont("txtEnd.font")); // NOI18N
        txtStart.setName("txtStart"); // NOI18N

        txtEnd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));
        txtEnd.setText(resourceMap.getString("txtEnd.text")); // NOI18N
        txtEnd.setFont(resourceMap.getFont("txtEnd.font")); // NOI18N
        txtEnd.setName("txtEnd"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkUseSearchRange)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtStart, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(setSearchRange, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addComponent(txtEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkUseSearchRange)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(setSearchRange, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 160, 190));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-910)/2, (screenSize.height-544)/2, 910, 544);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnDoorOpen1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoorOpen1MouseClicked
        this.dispose();
    }//GEN-LAST:event_btnDoorOpen1MouseClicked

    private void btnReadSLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadSLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadSuperLogData(SysUtil.MachineNumber, chkReadMark.isSelected());
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            SuperLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetSuperLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                superLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + superLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);

    }//GEN-LAST:event_btnReadSLogDataMouseClicked

    private void btnReadAllSLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadAllSLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllSLogData(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            SuperLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetAllSLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                superLogListModel.addSLogData(output);
            }
            lblTotal.setText("Total: " + superLogListModel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadAllSLogDataMouseClicked

    private void btnEmptySLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptySLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.EmptySuperLogData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEmptySLogDataMouseClicked

    private void btnEmptyGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmptyGLogDataMouseClicked
        superLogListModel.removeAll();
        tblLogList.setModel(superLogListModel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);
        
        if(ret)
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnEmptyGLogDataMouseClicked

    private void btnReadGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadGLogDataMouseClicked
        generalLogListMOdel.removeAll();
        tblLogList.setModel(generalLogListMOdel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadGeneralLogData(SysUtil.MachineNumber, chkReadMark.isSelected());
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            GeneralLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetGeneralLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                generalLogListMOdel.addSLogData(output);
            }
            lblTotal.setText("Total: " + generalLogListMOdel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadGLogDataMouseClicked

    private void btnReadAllGLogDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReadAllGLogDataMouseClicked
        generalLogListMOdel.removeAll();
        tblLogList.setModel(generalLogListMOdel);
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        ret = SBXPCProxy.ReadAllGLogData(SysUtil.MachineNumber);
        
        if(ret)
        {
            errorCode = 0;
            
            if(chkSearchAndDelete.isSelected())
                ret = SBXPCProxy.EmptyGeneralLogData(SysUtil.MachineNumber);

            lblMessage.setText("Getting...");
            invalidate();
            
            GeneralLogDataOutput output;
            while(true)
            {
                output = SBXPCProxy.GetAllGLogData(SysUtil.MachineNumber);
                
                if(!output.isSuccess()) break;
                
                generalLogListMOdel.addSLogData(output);
            }
            lblTotal.setText("Total: " + generalLogListMOdel.getRowCount());
        }else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnReadAllGLogDataMouseClicked

    private void setSearchRangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setSearchRangeMouseClicked
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        OneStringOutput output;
        
        output = SysUtil.MakeXMLCommandHeader("SetGLogSearchRange");
        output = SBXPCProxy.XML_AddBoolean(output.value, "UseSearchRange", chkUseSearchRange.isSelected());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime((Date)txtStart.getValue());
        output = SBXPCProxy.XML_AddLong(output.value, "StartYear", calendar.get(Calendar.YEAR));
        output = SBXPCProxy.XML_AddLong(output.value, "StartMonth", calendar.get(Calendar.MONTH) + 1);
        output = SBXPCProxy.XML_AddLong(output.value, "StartDate", calendar.get(Calendar.DATE));
        calendar.setTime((Date)txtEnd.getValue());
        output = SBXPCProxy.XML_AddLong(output.value, "EndYear", calendar.get(Calendar.YEAR));
        output = SBXPCProxy.XML_AddLong(output.value, "EndMonth", calendar.get(Calendar.MONTH) + 1);
        output = SBXPCProxy.XML_AddLong(output.value, "EndDate", calendar.get(Calendar.DATE));
        
        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        
        if(output.isSuccess())
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_setSearchRangeMouseClicked

    private void tblLogListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLogListMouseClicked
        if(!chkShowGLogPhoto.isSelected()) return;
        int selectedRow = tblLogList.getSelectedRow();
        if(!(tblLogList.getModel() instanceof GLogDataListModel)) return;            
        if(selectedRow == prevSelectedRow) return;
        prevSelectedRow = selectedRow;

        lblGLogPhoto.setIcon(null);
        
        if("No Photo".equals(tblLogList.getValueAt(selectedRow, 0)))
            return;
        
        boolean ret;
        int errorCode;
        
        lblMessage.setText(SysUtil.WORKING);
        invalidate();
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);
        
        if(!ret)
        {
            lblMessage.setText(SysUtil.NO_DEVICE);
            return;
        }
        
        long photoPos = Long.parseLong(tblLogList.getValueAt(selectedRow, 0).toString());
        OneStringOutput output;
        output = SysUtil.MakeXMLCommandHeader("GetGLogPhotoData");
        output = SBXPCProxy.XML_AddLong(output.value, "PhotoPos", photoPos);
        
        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        
        if(output.isSuccess())
        {
            errorCode = 0;
            XMLParseBinaryByteOutput parseOutput;
            parseOutput = SBXPCProxy.XML_ParseBinaryByte(output.value, "PhotoData", SysUtil.COMPRESSED_PHOTO_SIZE);
            if(parseOutput.isSuccess())
                lblGLogPhoto.setIcon(new ImageIcon(parseOutput.pData, "TEMP_GLOG_PHOTO"));
        }
        else
        {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }
        
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));
        
        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_tblLogListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoorOpen1;
    private javax.swing.JButton btnEmptyGLogData;
    private javax.swing.JButton btnEmptySLogData;
    private javax.swing.JButton btnReadAllGLogData;
    private javax.swing.JButton btnReadAllSLogData;
    private javax.swing.JButton btnReadGLogData;
    private javax.swing.JButton btnReadSLogData;
    private javax.swing.JCheckBox chkReadMark;
    private javax.swing.JCheckBox chkSearchAndDelete;
    private javax.swing.JCheckBox chkShowGLogPhoto;
    private javax.swing.JCheckBox chkUseSearchRange;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGLogPhoto;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JButton setSearchRange;
    private javax.swing.JTable tblLogList;
    private javax.swing.JFormattedTextField txtEnd;
    private javax.swing.JFormattedTextField txtStart;
    // End of variables declaration//GEN-END:variables
}

class SLogDataListModel extends AbstractTableModel
{
    final String[] COLUMN_TEXT = 
                    {
                        "TMNo",
                        "SEnlNo",
                        "SMNo",
                        "GEnlNo",
                        "GMNo",
                        "Manipulation",
                        "FpNo",
                        "DateTime",
                    };
    List<SuperLogData> logList;

    public void addSLogData(SuperLogData logData)
    {
        logList.add(logData);
        fireTableRowsInserted(logList.size()-1, logList.size()-1);
    }

    public void removeAll()
    {
        logList.removeAll(logList);
        fireTableDataChanged();
    }

    public SLogDataListModel(){
        logList = new ArrayList<SuperLogData>();
    }

    public int getRowCount() {
        return logList.size();
    }

    public int getColumnCount() {
        return COLUMN_TEXT.length;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        SuperLogData logData = logList.get(rowIndex);
        switch(columnIndex)
        {
            case 0:
                return logData.dwTMachineNumber;
            case 1:
                return logData.dwSEnrollNumber;
            case 2:
                return logData.dwSMachineNumber;
            case 3:
                return logData.dwGEnrollNumber;
            case 4:
                return logData.dwGMachineNumber;
            case 5:
            {
                String ret;
                switch((int)logData.dwManipulation)
                {
                case 3:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Enroll User";
                case 4:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Enroll Manager";
                case 5:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Fp Data";
                case 6:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Password";
                case 7:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete Card Data";
                case 8:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Delete All LogData";
                case 9:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify System Info";
                case 10:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify System Time";
                case 11:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Log Setting";
                case 12:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Comm Setting";
                case 13:
                    ret = String.valueOf(logData.dwManipulation) + "--" + "Modify Timezone Setting";
                default:
                    ret = "--Unknown--";
                }
                return ret;
            }
            case 6:
                if(logData.dwBackupNumber < 10)
                    return logData.dwBackupNumber;
                else if(logData.dwBackupNumber == 10)
                    return "Password";
                else
                    return "Card";
            case 7:
            {
                NumberFormat formatter = new DecimalFormat("00");
                String ret = String.valueOf(logData.dwYear) + "/" + formatter.format(logData.dwMonth) + "/" + formatter.format(logData.dwDay) + " ";
                ret += formatter.format(logData.dwHour) + ":" + formatter.format(logData.dwMinute) + ":" + formatter.format(logData.dwSecond);
                return ret;
            }
            default:
                return null;
        }
    }

    @Override
    public String getColumnName(int columnIndex) {
        return COLUMN_TEXT[columnIndex];
    }
}

class GLogDataListModel extends AbstractTableModel
{
    final String[] COLUMN_TEXT = 
                    {
                        "PhotoNo",
                        "EnrollNo",
                        "EMachineNo",
                        "VeriMode",
                        "DateTime",
                        "DaiGong",
                    };
    List<GeneralLogData> logList;

    public void addSLogData(GeneralLogData logData)
    {
        logList.add(logData);
        fireTableRowsInserted(logList.size()-1, logList.size()-1);
    }

    public void removeAll()
    {
        logList.removeAll(logList);
        fireTableDataChanged();
    }

    public GLogDataListModel(){
        logList = new ArrayList<GeneralLogData>();
    }

    public int getRowCount() {
        return logList.size();
    }

    public int getColumnCount() {
        return COLUMN_TEXT.length;
    }

    public Object getValueAt(int rowIndex, int columnIndex) {
        GeneralLogData logData = logList.get(rowIndex);
        
        int attendStatus, antipassStatus, daigong, verifyMode;
        
        antipassStatus = (int)logData.dwVerifyMode / 65536;
        daigong = antipassStatus / 4;
        antipassStatus = antipassStatus % 4;
        verifyMode = (int)logData.dwVerifyMode % 65536;
        attendStatus = verifyMode / 256;
        verifyMode = verifyMode % 256;
        
        String strAttendStatus, strAntipassStatus, strVerifyMode;
        switch(attendStatus)
        {
            case 0: strAttendStatus = "_Duty On";        break;
            case 1: strAttendStatus = "_Duty Off";       break;
            case 2: strAttendStatus = "_Overtime On";    break;
            case 3: strAttendStatus = "_Overtime Off";   break;
            case 4: strAttendStatus = "_Go In";          break;
            case 5: strAttendStatus = "_Go Out";         break;
            default: strAttendStatus = "";
        }
        
        switch(antipassStatus)
        {
            case 1: strAntipassStatus = ":AP_In";     break;
            case 2: strAntipassStatus = ":AP_Out";    break;
            default: strAntipassStatus = "";
        }
        
        switch(verifyMode)
        {
            case 0: strVerifyMode = "FP+ID"; break;
            case 1: strVerifyMode = "FP"; break;
            case 2: strVerifyMode = "Password"; break;
            case 3: strVerifyMode = "Card"; break;
            case 4: strVerifyMode = "FP+Card"; break;
            case 5: strVerifyMode = "FP+Pwd"; break;
            case 6: strVerifyMode = "Card+Pwd"; break;
            case 7: strVerifyMode = "FP+Card+Pwd"; break;
            case 10: strVerifyMode = "Hand Lock"; break;
            case 11: strVerifyMode = "Prog Lock"; break;
            case 12: strVerifyMode = "Prog Open"; break;
            case 13: strVerifyMode = "Prog Close"; break;
            case 14: strVerifyMode = "Auto Recover"; break;
            case 20: strVerifyMode = "Lock Over"; break;
            case 21: strVerifyMode = "Illegal Open"; break;
            case 22: strVerifyMode = "Duress alarm"; break;
            case 23: strVerifyMode = "Tamper detect"; break;
            case 51: strVerifyMode = "FP"; break;
            case 52: strVerifyMode = "Password"; break;
            case 53: strVerifyMode = "Password"; break;
            case 101: strVerifyMode = "FP"; break;
            case 102: strVerifyMode = "Password"; break;
            case 103: strVerifyMode = "Password"; break;
            case 151: strVerifyMode = "FP"; break;
            case 152: strVerifyMode = "Password"; break;
            case 153: strVerifyMode = "Password"; break;
            default: strVerifyMode = ""; break;
        }

        switch(columnIndex)
        {
            case 0:
                return (logData.dwTMachineNumber == -1? "No Photo" : logData.dwTMachineNumber);
            case 1:
                return logData.dwEnrollNumber;
            case 2:
                return logData.dwEMachineNumber;
            case 3:
            case 4:
            {
                NumberFormat formatter = new DecimalFormat("00");
                String ret = String.valueOf(logData.dwYear) + "/" + formatter.format(logData.dwMonth) + "/" + formatter.format(logData.dwDay) + " ";
                ret += formatter.format(logData.dwHour) + ":" + formatter.format(logData.dwMinute) + ":" + formatter.format(logData.dwSecond);
                return ret;
            }
            case 5:
                return strVerifyMode + strAttendStatus + strAntipassStatus;
            default:
                return null;
        }
    }

    @Override
    public String getColumnName(int columnIndex) {
        return COLUMN_TEXT[columnIndex];
    }
}


