/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScreenSaverFrame.java
 *
 * Created on Aug 26, 2011, 8:04:16 PM
 */
package smack.comm.sample;

import java.io.File;
import smack.comm.SBXPCProxy;
import smack.comm.output.OneStringOutput;
import smack.comm.sample.global.SysUtil;

/**
 *
 * @author Administrator
 */
public class ScreenSaverFrame extends javax.swing.JFrame {

    /** Creates new form ScreenSaverFrame */
    public ScreenSaverFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserDebugOutFile = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtGlyphHeight = new javax.swing.JTextField();
        txtGlyphWidth = new javax.swing.JTextField();
        btnSetCustomerInfo = new javax.swing.JButton();
        btnEventCapture2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFontWidth = new javax.swing.JTextField();
        txtDebugOutFile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFontWeight = new javax.swing.JTextField();
        btnGetCustomerInfo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSleepMessage = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        btnEventCapture4 = new javax.swing.JButton();
        btnGetSleepMessage = new javax.swing.JButton();
        btnSetSleepMessage = new javax.swing.JButton();
        chkDebugOut = new javax.swing.JCheckBox();
        chkItalic = new javax.swing.JCheckBox();
        chkUnderline = new javax.swing.JCheckBox();
        chkStrikeOut = new javax.swing.JCheckBox();
        txtFontHeight = new javax.swing.JTextField();
        btnGetGlyphSize = new javax.swing.JButton();

        fileChooserDebugOutFile.setName("fileChooserDebugOutFile"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(smack.comm.sample.MainFrame.class).getContext().getResourceMap(ScreenSaverFrame.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        txtCompanyName.setFont(resourceMap.getFont("txtCompanyName.font")); // NOI18N
        txtCompanyName.setText(resourceMap.getString("txtCompanyName.text")); // NOI18N
        txtCompanyName.setName("txtCompanyName"); // NOI18N
        getContentPane().add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 210, -1));

        txtCustomerName.setFont(resourceMap.getFont("txtCustomerName.font")); // NOI18N
        txtCustomerName.setText(resourceMap.getString("txtCustomerName.text")); // NOI18N
        txtCustomerName.setName("txtCustomerName"); // NOI18N
        getContentPane().add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 210, -1));

        lblMessage.setFont(resourceMap.getFont("lblMessage.font")); // NOI18N
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setText(resourceMap.getString("lblMessage.text")); // NOI18N
        lblMessage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblMessage.setName("lblMessage"); // NOI18N
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 490, 30));

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        txtGlyphHeight.setFont(resourceMap.getFont("txtGlyphHeight.font")); // NOI18N
        txtGlyphHeight.setText(resourceMap.getString("txtGlyphHeight.text")); // NOI18N
        txtGlyphHeight.setName("txtGlyphHeight"); // NOI18N
        getContentPane().add(txtGlyphHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 90, -1));

        txtGlyphWidth.setFont(resourceMap.getFont("txtGlyphWidth.font")); // NOI18N
        txtGlyphWidth.setText(resourceMap.getString("txtGlyphWidth.text")); // NOI18N
        txtGlyphWidth.setName("txtGlyphWidth"); // NOI18N
        getContentPane().add(txtGlyphWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 90, -1));

        btnSetCustomerInfo.setFont(resourceMap.getFont("btnSetCustomerInfo.font")); // NOI18N
        btnSetCustomerInfo.setText(resourceMap.getString("btnSetCustomerInfo.text")); // NOI18N
        btnSetCustomerInfo.setName("btnSetCustomerInfo"); // NOI18N
        btnSetCustomerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetCustomerInfoMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetCustomerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 160, 30));

        btnEventCapture2.setFont(resourceMap.getFont("btnEventCapture2.font")); // NOI18N
        btnEventCapture2.setText(resourceMap.getString("btnEventCapture2.text")); // NOI18N
        btnEventCapture2.setName("btnEventCapture2"); // NOI18N
        btnEventCapture2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEventCapture2MouseClicked(evt);
            }
        });
        getContentPane().add(btnEventCapture2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 500, 110, 30));

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel7.setFont(resourceMap.getFont("jLabel7.font")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        txtFontWidth.setFont(resourceMap.getFont("txtFontWidth.font")); // NOI18N
        txtFontWidth.setText(resourceMap.getString("txtFontWidth.text")); // NOI18N
        txtFontWidth.setName("txtFontWidth"); // NOI18N
        getContentPane().add(txtFontWidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 90, -1));

        txtDebugOutFile.setFont(resourceMap.getFont("txtDebugOutFile.font")); // NOI18N
        txtDebugOutFile.setText(resourceMap.getString("txtDebugOutFile.text")); // NOI18N
        txtDebugOutFile.setName("txtDebugOutFile"); // NOI18N
        getContentPane().add(txtDebugOutFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 250, -1));

        jLabel8.setFont(resourceMap.getFont("jLabel8.font")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        txtFontWeight.setFont(resourceMap.getFont("txtFontWeight.font")); // NOI18N
        txtFontWeight.setText(resourceMap.getString("txtFontWeight.text")); // NOI18N
        txtFontWeight.setName("txtFontWeight"); // NOI18N
        getContentPane().add(txtFontWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 90, -1));

        btnGetCustomerInfo.setFont(resourceMap.getFont("btnGetCustomerInfo.font")); // NOI18N
        btnGetCustomerInfo.setText(resourceMap.getString("btnGetCustomerInfo.text")); // NOI18N
        btnGetCustomerInfo.setName("btnGetCustomerInfo"); // NOI18N
        btnGetCustomerInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetCustomerInfoMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetCustomerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 160, 30));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        txtSleepMessage.setColumns(20);
        txtSleepMessage.setFont(resourceMap.getFont("txtSleepMessage.font")); // NOI18N
        txtSleepMessage.setRows(5);
        txtSleepMessage.setText(resourceMap.getString("txtSleepMessage.text")); // NOI18N
        txtSleepMessage.setName("txtSleepMessage"); // NOI18N
        jScrollPane1.setViewportView(txtSleepMessage);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 290, 60));

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        btnEventCapture4.setFont(resourceMap.getFont("btnEventCapture4.font")); // NOI18N
        btnEventCapture4.setText(resourceMap.getString("btnEventCapture4.text")); // NOI18N
        btnEventCapture4.setName("btnEventCapture4"); // NOI18N
        btnEventCapture4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEventCapture4MouseClicked(evt);
            }
        });
        getContentPane().add(btnEventCapture4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 30, -1));

        btnGetSleepMessage.setFont(resourceMap.getFont("btnGetSleepMessage.font")); // NOI18N
        btnGetSleepMessage.setText(resourceMap.getString("btnGetSleepMessage.text")); // NOI18N
        btnGetSleepMessage.setName("btnGetSleepMessage"); // NOI18N
        btnGetSleepMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetSleepMessageMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetSleepMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 160, 30));

        btnSetSleepMessage.setFont(resourceMap.getFont("btnSetSleepMessage.font")); // NOI18N
        btnSetSleepMessage.setText(resourceMap.getString("btnSetSleepMessage.text")); // NOI18N
        btnSetSleepMessage.setName("btnSetSleepMessage"); // NOI18N
        btnSetSleepMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetSleepMessageMouseClicked(evt);
            }
        });
        getContentPane().add(btnSetSleepMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 160, 30));

        chkDebugOut.setFont(resourceMap.getFont("chkDebugOut.font")); // NOI18N
        chkDebugOut.setText(resourceMap.getString("chkDebugOut.text")); // NOI18N
        chkDebugOut.setName("chkDebugOut"); // NOI18N
        getContentPane().add(chkDebugOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        chkItalic.setFont(resourceMap.getFont("chkItalic.font")); // NOI18N
        chkItalic.setText(resourceMap.getString("chkItalic.text")); // NOI18N
        chkItalic.setName("chkItalic"); // NOI18N
        getContentPane().add(chkItalic, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        chkUnderline.setFont(resourceMap.getFont("chkUnderline.font")); // NOI18N
        chkUnderline.setText(resourceMap.getString("chkUnderline.text")); // NOI18N
        chkUnderline.setName("chkUnderline"); // NOI18N
        getContentPane().add(chkUnderline, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, -1, -1));

        chkStrikeOut.setFont(resourceMap.getFont("chkStrikeOut.font")); // NOI18N
        chkStrikeOut.setText(resourceMap.getString("chkStrikeOut.text")); // NOI18N
        chkStrikeOut.setName("chkStrikeOut"); // NOI18N
        getContentPane().add(chkStrikeOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        txtFontHeight.setFont(resourceMap.getFont("txtFontHeight.font")); // NOI18N
        txtFontHeight.setText(resourceMap.getString("txtFontHeight.text")); // NOI18N
        txtFontHeight.setName("txtFontHeight"); // NOI18N
        getContentPane().add(txtFontHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 90, -1));

        btnGetGlyphSize.setFont(resourceMap.getFont("btnGetGlyphSize.font")); // NOI18N
        btnGetGlyphSize.setText(resourceMap.getString("btnGetGlyphSize.text")); // NOI18N
        btnGetGlyphSize.setName("btnGetGlyphSize"); // NOI18N
        btnGetGlyphSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetGlyphSizeMouseClicked(evt);
            }
        });
        getContentPane().add(btnGetGlyphSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 160, 30));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-518)/2, (screenSize.height-588)/2, 518, 588);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEventCapture2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventCapture2MouseClicked
        dispose();
    }//GEN-LAST:event_btnEventCapture2MouseClicked

    private void btnGetCustomerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetCustomerInfoMouseClicked
        boolean ret;
        int errorCode = 0;
        
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            lblMessage.setText("No Device");
            return;
        }

        OneStringOutput output = SysUtil.MakeXMLCommandHeader("GetCustomerInfo");

        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        if (output.isSuccess())
        {
            OneStringOutput parseOutput = SBXPCProxy.XML_ParseBinaryUnicode(output.value, "CustomerName", 128L);
            txtCustomerName.setText(parseOutput.value);
            parseOutput = SBXPCProxy.XML_ParseBinaryUnicode(output.value, "CompanyName", 128L);
            txtCompanyName.setText(parseOutput.value);
            errorCode = 0;
        }else {
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }

        lblMessage.setText(SysUtil.ErrorPrint(errorCode));

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetCustomerInfoMouseClicked

    private void btnSetCustomerInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetCustomerInfoMouseClicked
        boolean ret;
        int errorCode = 0;
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            lblMessage.setText("No Device");
            return;
        }

        OneStringOutput output = SysUtil.MakeXMLCommandHeader("SetCustomerInfo");
        output = SBXPCProxy.XML_AddBinaryUnicode(output.value, "CustomerName", txtCustomerName.getText());
        output = SBXPCProxy.XML_AddBinaryUnicode(output.value, "CompanyName", txtCompanyName.getText());

        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        if (output.isSuccess())
            errorCode = 0;
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
    
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetCustomerInfoMouseClicked

    private void btnGetGlyphSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetGlyphSizeMouseClicked
        boolean ret;
        int errorCode = 0;
        int glyphWidth, glyphHeight;
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            lblMessage.setText("No Device");
            return;
        }

        OneStringOutput output = SysUtil.MakeXMLCommandHeader("GetSleepMsgGlyphSize");

        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        if (output.isSuccess())
        {
            errorCode = 0;

            glyphWidth = SBXPCProxy.XML_ParseInt(output.value, "Width");
            glyphHeight = SBXPCProxy.XML_ParseInt(output.value, "Height");
            txtGlyphWidth.setText(String.valueOf(glyphWidth));
            txtGlyphHeight.setText(String.valueOf(glyphHeight));
        }
        else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
    
        lblMessage.setText(SysUtil.ErrorPrint(errorCode));

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetGlyphSizeMouseClicked

    private void btnGetSleepMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetSleepMessageMouseClicked
        boolean ret;
        int errorCode = 0;
        
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            lblMessage.setText("No Device");
            return;
        }

        OneStringOutput output = SysUtil.MakeXMLCommandHeader("GetSleepMessage");

        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        if (output.isSuccess())
        {
            errorCode = 0;

            OneStringOutput parseOutput = SBXPCProxy.XML_ParseBinaryUnicode(output.value, "SleepMessage", 256L);
            txtSleepMessage.setText(parseOutput.value);
        }else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;

        lblMessage.setText(SysUtil.ErrorPrint(errorCode));

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnGetSleepMessageMouseClicked

    private void btnSetSleepMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetSleepMessageMouseClicked
        boolean ret;
        int errorCode;
        int glyphWidth, glyphHeight;
        
        lblMessage.setText("Working...");
        invalidate();

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, false);

        if (!ret)
        {
            lblMessage.setText("No Device");
            return;
        }

        OneStringOutput output = SysUtil.MakeXMLCommandHeader("GetSleepMsgGlyphSize");

        output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
        if (output.isSuccess())
        {
            glyphWidth = SBXPCProxy.XML_ParseInt(output.value, "Width");
            glyphHeight = SBXPCProxy.XML_ParseInt(output.value, "Height");

            OneStringOutput fontXML = new OneStringOutput();
            fontXML.value = "";
            fontXML = SBXPCProxy.XML_AddString(fontXML.value, "FaceName", "Arial");
            fontXML = SBXPCProxy.XML_AddInt(fontXML.value, "Height", Integer.parseInt(txtFontHeight.getText()));
            fontXML = SBXPCProxy.XML_AddInt(fontXML.value, "Width", Integer.parseInt(txtFontWidth.getText()));
            fontXML = SBXPCProxy.XML_AddInt(fontXML.value, "Weight", Integer.parseInt(txtFontWeight.getText()));
            fontXML = SBXPCProxy.XML_AddBoolean(fontXML.value, "Italic", chkItalic.isSelected());
            fontXML = SBXPCProxy.XML_AddBoolean(fontXML.value, "Underline", chkUnderline.isSelected());
            fontXML = SBXPCProxy.XML_AddBoolean(fontXML.value, "StrikeOut", chkStrikeOut.isSelected());

            if (chkDebugOut.isSelected()) 
                fontXML = SBXPCProxy.XML_AddString(fontXML.value, "DebugOut", txtDebugOutFile.getText());
            
            String sleepMessage = txtSleepMessage.getText();

            output = SysUtil.MakeXMLCommandHeader("SetSleepMessage");
            output = SBXPCProxy.XML_AddBinaryGlyph(output.value, sleepMessage, glyphWidth, glyphHeight, fontXML.value);

            output = SBXPCProxy.GeneralOperationXML(SysUtil.MachineNumber, output.value);
            
            if (output.isSuccess())
                errorCode = 0;
            else
                errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;
        }else
            errorCode = (int)SBXPCProxy.GetLastError(SysUtil.MachineNumber).dwValue;

        lblMessage.setText(SysUtil.ErrorPrint(errorCode));

        ret = SBXPCProxy.EnableDevice(SysUtil.MachineNumber, true);
    }//GEN-LAST:event_btnSetSleepMessageMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MainFrame.getApplication().getMainFrame().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnEventCapture4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventCapture4MouseClicked
        fileChooserDebugOutFile.showSaveDialog(this);
        File selectedFile = fileChooserDebugOutFile.getSelectedFile();
        
        if(selectedFile == null) return;
        txtDebugOutFile.setText(selectedFile.getPath());
    }//GEN-LAST:event_btnEventCapture4MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEventCapture2;
    private javax.swing.JButton btnEventCapture4;
    private javax.swing.JButton btnGetCustomerInfo;
    private javax.swing.JButton btnGetGlyphSize;
    private javax.swing.JButton btnGetSleepMessage;
    private javax.swing.JButton btnSetCustomerInfo;
    private javax.swing.JButton btnSetSleepMessage;
    private javax.swing.JCheckBox chkDebugOut;
    private javax.swing.JCheckBox chkItalic;
    private javax.swing.JCheckBox chkStrikeOut;
    private javax.swing.JCheckBox chkUnderline;
    private javax.swing.JFileChooser fileChooserDebugOutFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtDebugOutFile;
    private javax.swing.JTextField txtFontHeight;
    private javax.swing.JTextField txtFontWeight;
    private javax.swing.JTextField txtFontWidth;
    private javax.swing.JTextField txtGlyphHeight;
    private javax.swing.JTextField txtGlyphWidth;
    private javax.swing.JTextArea txtSleepMessage;
    // End of variables declaration//GEN-END:variables
}
