#NOI18N
lblMessage.font=Times New Roman-Bold-18
lblMessage.text=Message
jLabel4.text=Product Code:
#NOI18N
jLabel5.font=Times New Roman-Plain-18
jLabel5.text=Serial Number:
jLabel6.text=Backup Number:
#NOI18N
btnGetSerialNumber.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnGetBackupNumber.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
#NOI18N
btnGetProductCode.font=Times New Roman 14 12 12 12 12 12 12 12 12 Bold
btnExit.text=Exit
#NOI18N
btnExit.font=Times New Roman 14 12 12 12 12 12 12 12 Bold
txtSerialNumber.text=
txtBackupNumber.text=
#NOI18N
txtBackupNumber.font=Times New Roman-Plain-18
txtProductCode.text=
#NOI18N
jTextField2.font=Times New Roman-Plain-18
Form.title=Product Code
